### PR TITLE
LPS-131205 Update ChatWootSDK to window.onload

### PR DESCRIPTION
**Pull request by kevenleone**
Issue: https://issues.liferay.com/browse/LPS-131205

Bug: https://issues.liferay.com/secure/attachment/403274/ActualResult_2021Apr26_LPS-131205.mp4

Fix: 

https://user-images.githubusercontent.com/22279592/116327586-7b950580-a79d-11eb-8b54-6aadeb6e6803.mov

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test

**Comment by kevenleone** [comment]
ci:test:sf

**Review by joseabelenda — APPROVED** [review]

**Comment by joseabelenda** [comment]
Thanks @kevenleone!

**Pull request closed without merging**
