### PR TITLE
LPS-189645 [EVP] Fix the error message that makes it impossible to click on ellipsis button

### PR DESCRIPTION
**Pull request by Mylena-Rodrigues**
Ticket: [LPS-189645](https://liferay.atlassian.net/browse/LPS-189645)

### CODE REVIEW

**Comment by Mylena-Rodrigues** [comment]
ci:test:sf

**Comment by Mylena-Rodrigues** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
ci:forward

**Comment by Mylena-Rodrigues** [comment]
Link: [brianchandotcom#137605](https://github.com/brianchandotcom/liferay-portal/pull/137605)

**Pull request closed without merging**
