### PR TITLE
LPS-172459 [PRM] Fix error message on 'Invoice Amount' field

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
https://issues.liferay.com/browse/LPS-172459

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
LGTM!

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
