### PR TITLE
LPS-172801 - [Raylife Ap] The columns headers cannot be sorted

### PR DESCRIPTION
**Pull request by eduardo-diniz**
Task: [LPS-172801](https://issues.liferay.com/browse/LPS-172801)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Review by joanagrego — CHANGES_REQUESTED** [review]
Good job! To finish it, please change de commit name for "LPS-172801 Fix columns headers"

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
