### PR TITLE
LPS-185468 [PRM] Deal reg fix submit

### PR DESCRIPTION
**Pull request by DiogoNo**

### CODE REVIEW

**Comment by DiogoNo** [comment]
ci:test:sf

**Comment by DiogoNo** [comment]
ci:test:solutions-acceptance

**Comment by AfonsoHSantos** [comment]
The test failures aren't related with this PR.

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @DiogoNo

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
