### PR TITLE
LPS-196476 [PRM] Event program is misplaced on Event Activity Type

### PR DESCRIPTION
**Pull request by Manda-vit**

### CODE REVIEW

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:relevant

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @Manda-vit

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
