### PR TITLE
LPS-163227 Fix Page Template

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:forward

**Comment by EuniceTravassos** [comment]
Just starting reviewing :)

**Comment by EuniceTravassos** [comment]
Just starting reviewing :)

**Comment by nNilton** [comment]
ci:reevaluate:1377401_5237

**Comment by nNilton** [comment]
ci:reevaluate:1377401_5237

**Comment by nNilton** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/2264

**Pull request closed without merging**
