### PR TITLE
LPS-192260 [CP 2.0] Team member removed from first page instead of team member from 2nd page

### PR DESCRIPTION
**Pull request by Mylena-Rodrigues**
Ticket: [LPS-192260](https://liferay.atlassian.net/browse/LPS-192260)

### CODE REVIEW

**Comment by Mylena-Rodrigues** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by Mylena-Rodrigues** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:stop

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/138796

**Pull request closed without merging**
