### PR TITLE
LPS-161195 [Raylife D2C] Add captcha validation

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-161195](https://issues.liferay.com/browse/LPS-161195)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @joanagrego

**Review by silasbsi — APPROVED** [review]
LGTM :+1: Thanks @joanagrego

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
