### PR TITLE
LPS-175428 [EVP] Remove the view of the Financial User from the Report screen

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-175428](https://issues.liferay.com/browse/LPS-175428)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark: Good job @juliocezar96

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
