### PR TITLE
LPS-167118 [Site Initializer] _updateObjectDefinitionAccountEntryRestricted

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:forward

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:forward

**Comment by nNilton** [comment]
Could you check this failures? @thaiscabrals

**Comment by thaiscabrals** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
Rebase error in BundleSiteInitializerTest
Please resent @joseabelenda

**Pull request closed without merging**
