### PR TITLE
LPS-187212 [PRM] Add the "Approved" and "Paid" info for the MDF Request and Claim List

### PR DESCRIPTION
**Pull request by ytuik**
https://liferay.atlassian.net/browse/LPS-186115

### CODE REVIEW

**Comment by ytuik** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:solutions-acceptance

**Comment by thaynam** [comment]
ci:test:stable

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
Resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/4342

**Pull request closed without merging**
