### PR TITLE
LPS-164018 Commenting an answer with an moderation user needs to reload the page to appears pending status

### PR DESCRIPTION
**Pull request by manuelecastro**
[LPS-164018](https://issues.liferay.com/browse/LPS-164018)

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
Thank you for submiting this PR, @manuelecastro 🎉

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
