### PR TITLE
LPS-177074 TR2 Automated Test | master

### PR DESCRIPTION
**Pull request by joelrocha68**
[LPS-177074](https://issues.liferay.com/browse/LPS-177074)

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:stop

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by nikki-pru** [comment]
Testing here: https://github.com/pt-liferay-solutions/liferay-portal/pull/3651

**Pull request closed without merging**
