### PR TITLE
LPS-160630 [Raylife AP] Table access correction

### PR DESCRIPTION
**Pull request by juliocezarjc**
Impedibug: [LPS-160630](https://issues.liferay.com/browse/LPS-160630)

### CODE REVIEW

**Comment by juliocezarjc** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Nice job! :arrow_up:

**Review by silasbsi — APPROVED** [review]
LGTM :1st_place_medal: thanks @juliocezarjc

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
