### PR TITLE
LPS-148635 [Site Initializer] create _addWidgetTemplates

### PR DESCRIPTION
**Pull request by thiagooliveiraaa**

### CODE REVIEW

**Comment by thiagooliveiraaa** [comment]
ci:test:sf

**Comment by thiagooliveiraaa** [comment]
ci:test:relevant

**Comment by thiagooliveiraaa** [comment]
ci:test:relevant

**Comment by thiagooliveiraaa** [comment]
ci:test:sf

**Comment by thiagooliveiraaa** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/1015

**Pull request closed without merging**
