### PR TITLE
LPS-185067 Fixing testray administrator role wrong behavior

### PR DESCRIPTION
**Pull request by EugenioAntunes**
[LPS-185015](https://issues.liferay.com/browse/LPS-185015)
[LPS-185067](https://issues.liferay.com/browse/LPS-185067)
[LPS-183685](https://issues.liferay.com/browse/LPS-183685)

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:forward

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Pull request closed without merging**
