### PR TITLE
LPS-189216 [Marketplace] Fix 'Resend' button remains on page even if user accepts invitation

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-189216](https://liferay.atlassian.net/browse/LPS-189216)

### CODE REVIEW

**Comment by juliocezar96** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-189216 [Impedibug] The 'Resend' button remains on the page even if the user accepts the invite</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-189216">[Impedibug] The 'Resend' button remains on the page even if the user accepts the invite</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Impedibug</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Medium</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Support QA</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Luana Silva</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

4 files changed, 52 insertions(+), 25 deletions(-)

**Comment by claricebrasil** [comment]
ci:test:sf

**Review by claricebrasil — CHANGES_REQUESTED** [review]

**Review by welitonpe — CHANGES_REQUESTED** [review]

**Comment by juliocezar96** [comment]
ci:test:sf

**Review by welitonpe — APPROVED** [review]
Good Job :fire:

**Comment by juliocezar96** [comment]
ci:test:stable

**Comment by claricebrasil** [comment]
ci:stop

**Comment by claricebrasil** [comment]
ci:forward:force

**Comment by juliocezar96** [comment]
ci:forward:force

**Pull request closed without merging**
