### PR TITLE
LPS-194529 [Impedibug] [Marketplace] Fix Missing informations on the Solutions Pages

### PR DESCRIPTION
**Pull request by claricebrasil**

### CODE REVIEW

**Comment by claricebrasil** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by claricebrasil** [comment]
ci:test:relevant

**Comment by LuanaKSilva** [comment]
Hey @claricebrasil, the flaws pointed out in the tests have nothing to do with your PR. Putting it forward.

**Pull request closed without merging**
