### PR TITLE
LPS-186894 Fix CI Routine | Customer Portal 2.0 

### PR DESCRIPTION
**Pull request by styller1**
Ticket With index from test:
[LPS-186894](https://issues.liferay.com/browse/LPS-186894)

### CODE REVIEW

**Comment by styller1** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:sf

**Review by luanakarla — APPROVED** [review]
Hey @styller1, thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by luanakarla** [comment]
ci:forward

**Pull request closed without merging**
