### PR TITLE
LPS-177454 Remove Feature Flag LPS-165491

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:solutions-acceptance

**Comment by nikki-pru** [comment]
ci:test:questions

**Comment by kevenleone** [comment]
Do not forward until https://issues.liferay.com/browse/LPS-177052 be fixed, it's a blocker for Liferay.dev

**Comment by nikki-pru** [comment]
ci:test:solutions-acceptance

**Comment by jairmedeiros** [comment]
rebasing: https://github.com/pt-liferay-solutions/liferay-portal/pull/4138

**Pull request closed without merging**
