### PR TITLE
LPS-176548 Apply filter logic

### PR DESCRIPTION
**Pull request by Elvinho**

### CODE REVIEW

**Comment by Elvinho** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-176548 [FE] Apply filter</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-176548">[FE] Apply filter</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>SE Support</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Elvison Victor</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-176547 [FE] Create layout filter</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-176547">[FE] Create layout filter</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>SE Support</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Elvison Victor</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

3 files changed, 7 insertions(+), 1 deletion(-)

**Comment by kevenleone** [comment]
ci:test:sf

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Review by rafaelfs98 — APPROVED** [review]
LGTM :fire:

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Review by welitonpe — APPROVED** [review]
LGTM :fire:

**Pull request closed without merging**
