### PR TITLE
LPS-191861 [Marketplace] Added custom field from Marketplace Cloud

### PR DESCRIPTION
**Pull request by welitonpe**
**[LPS-191861](https://liferay.atlassian.net/browse/LPS-191861)**

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by welitonpe** [comment]
ci:test:sf

**Review by claricebrasil — APPROVED** [review]
Great job!

**Comment by claricebrasil** [comment]
ci:forward

**Review by juliocezar96 — APPROVED** [review]
Nice job! 🤙

**Comment by welitonpe** [comment]
ci:stop

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by welitonpe** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
