### PR TITLE
LPS-167840 buildLang

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by caiosouza15** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:reevaluate:1307401_5586

**Comment by kevenleone** [comment]
ci:forward

**Comment by nNilton** [comment]
ci;test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
