### PR TITLE
[LPS-140166 & LPS-140183] [CP 2.0] Fix Activation Keys component

### PR DESCRIPTION
**Pull request by iagochaves**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
LGTM 🔥

**Comment by joseabelenda** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by luanakarla** [comment]
Just starting reviewing :)

**Comment by igordmf** [comment]
Just starting reviewing :)

**Pull request closed without merging**
