### PR TITLE
LPS-170979 [Site Initializer] Segments-experience duplicates elements in page

### PR DESCRIPTION
**Pull request by TamyrisTorres**

### CODE REVIEW

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:reevaluate:1257401_5857

**Comment by nNilton** [comment]
ci:forward

**Comment by nNilton** [comment]
ci:forward

**Pull request closed without merging**
