### PR TITLE
LPS-159245 [Raylife AP] fix vehicle info style

### PR DESCRIPTION
**Pull request by silasbsi**
Sub-task: [LPS-159245](https://issues.liferay.com/browse/LPS-159245)

### CODE REVIEW

**Review by joanagrego — APPROVED** [review]
Great job! :up:

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @silasbsi

**Comment by pedro-michel** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
