### PR TITLE
LPS-173958 [Site Initializer] Change _addOrUpdateObjectFields from JSONObject to JSONArray

### PR DESCRIPTION
**Pull request by TamyrisTorres**

### CODE REVIEW

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:forward

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
