### PR TITLE
LPS-157149 Automated tests - Testray 2

### PR DESCRIPTION
**Pull request by joelrocha68**
[LPS-157149](https://issues.liferay.com/browse/LPS-157149)

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Review by AfonsoHSantos — CHANGES_REQUESTED** [review]

**Review by AfonsoHSantos — APPROVED** [review]

**Comment by barrosdennys** [comment]
ci:forward

**Comment by joelrocha68** [comment]
ci:stop

**Comment by joelrocha68** [comment]
ci:forward

**Pull request closed without merging**
