### PR TITLE
LPS-172670 [Raylife AP/D2C] Create Roles for Underwriter Workflow

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-167986](https://issues.liferay.com/browse/LPS-167986)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:relevant

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
