### PR TITLE
LPS-185473 | Users with provisioning account role do not show up in the Team Members list

### PR DESCRIPTION
**Pull request by gabrielargomes**
LPS-177948[](https://issues.liferay.com/browse/LPS-177948)

### CODE REVIEW

**Comment by gabrielargomes** [comment]
ci:test:sf

**Comment by gabrielargomes** [comment]
ci:test:sf

**Comment by gabrielargomes** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Pull request closed without merging**
