### PR TITLE
LPS-163455 [Raylife AP] Incomplete application details page

### PR DESCRIPTION
**Pull request by silasbsi**
Subtask: [LPS-163455](https://issues.liferay.com/browse/LPS-163455)

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @silasbsi

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
