### PR TITLE
LPS-144387 [CP 2.0] addAccounts, addUserAccounts and resources

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by aildsonf** [comment]
Just starting reviewing :)

**Comment by luanakarla** [comment]
Just starting reviewing :)

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
