### PR TITLE
LPS-162605 [ASK] Moderation

### PR DESCRIPTION
**Pull request by torresvictor100**

### CODE REVIEW

**Comment by torresvictor100** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by velosofelipe64** [comment]
ci:test:sf

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Comment by torresvictor100** [comment]
ci:test:sf

**Comment by torresvictor100** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/2127

**Pull request closed without merging**
