### PR TITLE
LPS-188870 EVP Automated Test | Master

### PR DESCRIPTION
**Pull request by joelrocha68**
[LPS-188870](https://liferay.atlassian.net/browse/LPS-188870)

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-evp

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by styller1** [comment]
LGTM!

**Comment by styller1** [comment]
ci:forward

**Pull request closed without merging**
