### PR TITLE
LPS-145156 & LPS-145158 & LPS-140173 [CP 2.0] Developer Keys for DXP and DXP Cloud

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
It's look good

Good job, @Lucas2691, @jairmedeiros

**Comment by kevenleone** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
