### PR TITLE
LPS-169335 [Raylife AP] Search bar creation

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-169335](https://issues.liferay.com/browse/LPS-169335)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Approved! Thank you @eliasantosf :white_check_mark:

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
