### PR TITLE
LPS-184215 [PRM] MDF Request Draft bug

### PR DESCRIPTION
**Pull request by thaynam**
[LPS-184215](https://issues.liferay.com/browse/LPS-184215)
MDF Request Draft bug

[LPS-185369](https://issues.liferay.com/browse/LPS-185369)
Error when submitting MDF the status is in draft

[LPS-183144](https://issues.liferay.com/browse/LPS-183144)
Make the PRM create some data when created

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
