### PR TITLE
LPS-174564 TR2 Automated Test | master

### PR DESCRIPTION
**Pull request by joelrocha68**
Ticket:
https://issues.liferay.com/browse/LPS-174564

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray

**Comment by joelrocha68** [comment]
ci:test:relevant

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:site-initializer-testray

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
