### PR TITLE
LPS-173395

### PR DESCRIPTION
**Pull request by itstali**
https://issues.liferay.com/browse/LPS-177807
https://issues.liferay.com/browse/LPS-173395

### CODE REVIEW

**Comment by itstali** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:site-initializer-raylife-d2c

**Comment by nikki-pru** [comment]
ci:test:site-initializer-raylife-d2c:nocompile

**Comment by itstali** [comment]
ci:test:sf

**Comment by itstali** [comment]
ci:test:site-initializer-raylife-d2c:nocompile

**Comment by nikki-pru** [comment]
Failed tests are not related. Forwarding PR. 
Thank you! :1st_place_medal:

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
