### PR TITLE
LPS-192892 [PRM] Visual inconsistencies on Partner Portal Page

### PR DESCRIPTION
**Pull request by Manda-vit**

### CODE REVIEW

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by thaynam** [comment]
[resent](https://github.com/pt-liferay-solutions/liferay-portal/pull/4634)

**Pull request closed without merging**
