### PR TITLE
LPS-187410 [C.P 2.0] The activation key details must display DNE for a key with unlimited expiration date

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-187410](https://issues.liferay.com/browse/LPS-187410)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Good job @eduardo-diniz , @pedroliveirav 

😁

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Pull request closed without merging**
