### PR TITLE
LPS-161174 [ASK] Homepage Filter

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Muito bom

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Pull request closed without merging**
