### PR TITLE
LPS-164325 [EVP] Create MyEVP Table Employee View

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by juliocezarjc** [comment]
Just starting reviewing :)

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:relevant

**Review by silasbsi — APPROVED** [review]
LGTM 🔥

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
