### PR TITLE
LPS-185612 - [BUG] The kebab disappears when the user leaves the create page

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-185612](https://issues.liferay.com/browse/LPS-185612)

### CODE REVIEW

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
