### PR TITLE
MP2 Automated Test | LPS-187209 | master

### PR DESCRIPTION
**Pull request by LuanaKSilva**
Ticket:
[LPS-187197](https://liferay.atlassian.net/browse/LPS-187197)

Tests:
MP2PublisherDashboard#AssertTheDetailsOfTheEmail
MP2PublisherDashboard#CanViewTheUserRoleInTheMemberList

### CODE REVIEW

**Comment by LuanaKSilva** [comment]
ci:test:sf

**Comment by LuanaKSilva** [comment]
ci:test:site-initializer-liferay-marketplace

**Comment by renato-araujo-liferay** [comment]
Look great to me @LuanaKSilva. let's wait for our CI to run and move forward

**Comment by LuanaKSilva** [comment]
ci:test:sf

**Comment by LuanaKSilva** [comment]
ci:forward

**Pull request closed without merging**
