### PR TITLE
LPS-161065 Walkthrough in Site Initializer as site settings

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:stable

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
will send to Brian. Thanks @joseabelenda

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
