### PR TITLE
LPS-173154 [PRM] Make MDF Claim editable

### PR DESCRIPTION
**Pull request by thaynam**
[LPS-173154](https://issues.liferay.com/browse/LPS-173154)
Make MDF Claim editable

[LPS-179929](https://issues.liferay.com/browse/LPS-179929)
Refactor Salesforce Objects to use External Reference Code

[LPS-179958](https://issues.liferay.com/browse/LPS-179958)
Update assets in Site Initializer adding ERC to be updated

[LPS-179710](https://issues.liferay.com/browse/LPS-179710)
When Company, Country and Currency fields aren't filled and an MDF is saved as draft, it isn't possible to edit it

[LPS-179708](https://issues.liferay.com/browse/LPS-179708)
MDF remains in Draft status even when submitted

[LPS-165934](https://issues.liferay.com/browse/LPS-165934)
Dashboard - Partner Level Dashlet

[LPS-178928](https://issues.liferay.com/browse/LPS-178928)
Account Role 'Partner Manager' should be able to edit MDF Requests

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/3661

**Pull request closed without merging**
