### PR TITLE
LPS-171115 Fixed Error message does not appear when returning a subtask to open

### PR DESCRIPTION
**Pull request by samuelleolopes**

### CODE REVIEW

**Comment by samuelleolopes** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-171115 Error message does not appear when returning a subtask to open</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-171115">Error message does not appear when returning a subtask to open</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Impedibug</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Samuel Lopes</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Joel Rocha</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

1 file changed, 2 insertions(+), 2 deletions(-)

**Comment by samuelleolopes** [comment]
ci:test:sf

**Review by caiosouza15 — APPROVED** [review]
Great work :fire:

**Review by welitonpe — APPROVED** [review]
LGTM :fire:

**Review by kevenleone — COMMENTED** [review]
I'm not confident about this change 

The code will be executed the same way, you just changed the return to void.

Whatever the problem is, probably there's no relationship with this function, it should be something else.

Can you try other approach?

**Comment by samuelleolopes** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
