### PR TITLE
LPS-140164 Simplify and Format Code

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by aildsonf** [comment]
Just starting reviewing :)

**Comment by aildsonf** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Comment by aildsonf** [comment]
Just starting reviewing :)

**Pull request closed without merging**
