### PR TITLE
LPS-162674 [ASK] Add Featured Domains in Moderation

### PR DESCRIPTION
**Pull request by torresvictor100**

### CODE REVIEW

**Comment by torresvictor100** [comment]
ci:test:sf

**Comment by torresvictor100** [comment]
ci:test:relevant

**Comment by torresvictor100** [comment]
ci:test:sf

**Comment by torresvictor100** [comment]
ci:test:sf

**Comment by torresvictor100** [comment]
ci:test:relevant

**Comment by torresvictor100** [comment]
ci:test:sf

**Comment by torresvictor100** [comment]
ci:test:relevant

**Comment by torresvictor100** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by torresvictor100** [comment]
ci:test:relevant

**Comment by torresvictor100** [comment]
ci:test:sf

**Comment by torresvictor100** [comment]
ci:test:relevant

**Pull request closed without merging**
