### PR TITLE
CP 2.0 Automation Test: LPS-160277 | master

### PR DESCRIPTION
**Pull request by luanakarla**
Ticket:
[LPS-160277](https://issues.liferay.com/browse/LPS-160277)

Tests:
CP2HomePage#AssertThatTheLanguageLinksWork
CP2HomePage#AssertThatTheCookiePolicyPageOpens

### CODE REVIEW

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by luanakarla** [comment]
ci:test:sf

**Review by renato-araujo-liferay — APPROVED** [review]
@luanakarla Could you avoid using "**This macro** does¨ expression in the following PR? it's redundant given this content is already in a .macro file and was declared as a macro function

**Review by renato-araujo-liferay — APPROVED** [review]
Approved

**Comment by renato-araujo-liferay** [comment]
ci:forward

**Review by renato-araujo-liferay — APPROVED** [review]

**Comment by renato-araujo-liferay** [comment]
ci:forward

**Comment by luanakarla** [comment]
ci:forward

**Pull request closed without merging**
