### PR TITLE
LPS-163649 Fixed error message when adding user group without name

### PR DESCRIPTION
**Pull request by Elvinho**

### CODE REVIEW

**Comment by Elvinho** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-163649 Incorrect error message when adding user group without name</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-163649">Incorrect error message when adding user group without name</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Impedibug</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Joel Rocha</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

2 files changed, 2 insertions(+), 1 deletion(-)

**Comment by caiosouza15** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/2209

**Pull request closed without merging**
