### PR TITLE
LPS-172531 Add classNameIds and sort, new Comparator

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-172531](https://issues.liferay.com/browse/LPS-172531)

This PR fixes the RuntimeException: Unable to get class name from id 0 error, by adding the classNameIds to the AssetListEntrySegmentsEntryRel table's typeSettings, which are required to export contents successfully. I moved a comparator class to the asset-list-api module, to make it reusable elsewhere. This issue is blocking [this](https://issues.liferay.com/browse/LPS-176242) LPS, so this PR does not fix completely the staging on Masterclass site.

[staging PR](https://github.com/liferay-staging/liferay-portal/pull/247)

### CODE REVIEW

**Comment by kevenleone** [comment]
Hi @DaniSzimko thanks for sending the PR for us, can you fix the conflict first? 

`This branch has conflicts that must be resolved
 Use the command line  to resolve conflicts before continuing.
Conflicting files
modules/apps/asset/asset-list-web/src/main/java/com/liferay/asset/list/web/internal/util/comparator/ClassNameModelResourceComparator.java`

Also, can @joseabelenda and @nNilton take a look?

**Comment by DaniSzimko** [comment]
I resolved the conflicts and force pushed the branch.

**Comment by joseabelenda** [comment]
Hi @DaniSzimko 
Thank you for this PR.
LGTM

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/3811

**Comment by joseabelenda** [comment]
Hi @DaniSzimko
It was necessary a baseline commit.
Resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/3811
Thx

**Pull request closed without merging**
