### PR TITLE
LPS-175612 TR2 Automated Test | master

### PR DESCRIPTION
**Pull request by joelrocha68**
[LPS-175612](https://issues.liferay.com/browse/LPS-175612)

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by nikki-pru** [comment]
Testing here: https://github.com/pt-liferay-solutions/liferay-portal/pull/3651

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Pull request closed without merging**
