### PR TITLE
LPS-174368 [CP] Mismatching dates on koroneiki/provisioning to CP2.0

### PR DESCRIPTION
**Pull request by kiwm**
Related issue: https://issues.liferay.com/browse/LPS-174368

### CODE REVIEW

**Comment by kiwm** [comment]
ci:test:sf

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @kiwm

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
Just starting reviewing :)

**Comment by JoMaAlves** [comment]
Just starting reviewing :)

**Comment by JoMaAlves** [comment]
ci:forward

**Pull request closed without merging**
