### PR TITLE
LPS-157436 User Groups for Site Initializer

### PR DESCRIPTION
**Pull request by leomiyagi**
https://issues.liferay.com/browse/LPS-157436

### CODE REVIEW

**Comment by leomiyagi** [comment]
ci:test

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
@gleicelisbino , @nNilton could review this PR, please? 😄

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
i just added a sort @leomiyagi

**Pull request closed without merging**
