### PR TITLE
LPS-188983  [EVP] Liferay Region Filters

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-188983](https://issues.liferay.com/browse/LPS-188983)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Good job @eliasantosf :martial_arts_uniform:

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
