### PR TITLE
[Site Initializer] LPS-163227 Fix Page Template

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by TamyrisTorres** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:test:sf

**Comment by EuniceTravassos** [comment]
Just starting reviewing :)

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by EuniceTravassos** [comment]
Just starting reviewing :)

**Comment by EuniceTravassos** [comment]
Just starting reviewing :)

**Comment by nNilton** [comment]
ci:forward

**Comment by DiogoNo** [comment]
Just starting reviewing :)

**Pull request closed without merging**
