### PR TITLE
LPS-162795 Fix translate and space to right of product activation menu button

### PR DESCRIPTION
**Pull request by wandersonvicente**

### CODE REVIEW

**Comment by wandersonvicente** [comment]
ci:test:cf

**Comment by wandersonvicente** [comment]
ci:test:sf

**Review by claricebrasil — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:reevaluate:1347401_2861

**Comment by jairmedeiros** [comment]
ci:reevaluate:1347401_2861

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
