### PR TITLE
LPS-167118 [Site Initializer] _updateObjectDefinitionAccountEntryRestricted

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:forward

**Comment by TamyrisTorres** [comment]
ci:forward

**Comment by thaiscabrals** [comment]
The failures of the automation tests on Objects are not related.

**Comment by TamyrisTorres** [comment]
Manually resent:https://github.com/brianchandotcom/liferay-portal/pull/128550

**Pull request closed without merging**
