### PR TITLE
LPS-142937 Replace useGraphQL to useQuery from Apollo

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-142937 Add Apollo GraphQL to Customer Portal React</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-142937">Add Apollo GraphQL to Customer Portal React</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

17 files changed, 286 insertions(+), 247 deletions(-)

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
Just starting reviewing :)

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Pull request closed without merging**
