### PR TITLE
LPS-177816 [PRM] [BUG] Fix Isn't possible to edit an Activity on a created MDF Request 

### PR DESCRIPTION
**Pull request by thaynam**
[LPS-177816](https://issues.liferay.com/browse/LPS-177816)
Isn't possible to edit an Activity on a created MDF Request

[LPS-177869](https://issues.liferay.com/browse/LPS-177869)
Manager only can edit MDF in "draft" status

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:stable

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
