### PR TITLE
LPS-150035 [Raylife AP] Creation of Total Active Chart - Policies page

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :fire:

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:stop

**Comment by silasbsi** [comment]
ci:forward

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
