### PR TITLE
LPS-159928 SF

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-159928 Add Flags Feature Flag to be displayed</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-159928">Add Flags Feature Flag to be displayed</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-159927 Use Flags Modal inside Questions Web</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-159927">Use Flags Modal inside Questions Web</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-159926 Add Flags Properties to Questions Web Java</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-159926">Add Flags Properties to Questions Web Java</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-159925 Export Flags Module through Liferay Workspace</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-159925">Export Flags Module through Liferay Workspace</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

14 files changed, 188 insertions(+), 19 deletions(-)

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
@kevenleone very nice!
Please see my change.
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/1813

**Comment by kevenleone** [comment]
Thanks @joseabelenda

**Pull request closed without merging**
