### PR TITLE
LPS-151038 Creating variables with Raylife Paypal credentials

### PR DESCRIPTION
**Pull request by joelrocha68**

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-raylife

**Comment by joelrocha68** [comment]
ci:test:site-initializer-raylife

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
@joelrocha68 SF seems to be having trouble with this pull request in an unusual way that is somehow preventing CI from posting a message to the pull request. Specifically, SF is throwing this error:

```
[beanshell] /opt/dev/projects/github/liferay-portal/build-test-tck.xml:4: The following error occurred while executing this line:
[beanshell] /opt/dev/projects/github/liferay-portal/build-test.xml:11193: The content of elements must consist of well-formed character data or markup.
```

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-raylife

**Comment by joelrocha68** [comment]
ci:test:site-initializer-raylife

**Comment by joelrocha68** [comment]
ci:stop

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-raylife

**Comment by joelrocha68** [comment]
ci:forward

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-raylife

**Comment by joelrocha68** [comment]
ci:forward

**Comment by joelrocha68** [comment]
site.initializer.raylife.ap

**Comment by joelrocha68** [comment]
ci:test:site.initializer.raylife.ap

**Comment by joelrocha68** [comment]
ci:test:site-initializer-raylife-d2c

**Comment by joelrocha68** [comment]
ci:test:site-initializer-raylife-ap

**Pull request closed without merging**
