### PR TITLE
LPS-167118 [Site Initializer] _updateObjectDefinitionAccountEntryRestricted

### PR DESCRIPTION
**Pull request by TamyrisTorres**

### CODE REVIEW

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:forward

**Comment by TamyrisTorres** [comment]
ci:test:relevant

**Comment by thaiscabrals** [comment]
The errors are not related. The [failed tests ](https://testray.liferay.com/home/-/testray/subtasks/index?testrayTaskId=2189918739&cur=1&delta=20&tab=runs&mergedToTestraySubtaskId=0)are already failing in the master.

**Comment by TamyrisTorres** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/129994

**Pull request closed without merging**
