### PR TITLE
LPS-174180 [CP 2.0] The elements in the banner on Activation Status tab is overlapping

### PR DESCRIPTION
**Pull request by kiwm**
Related issue: https://issues.liferay.com/browse/LPS-174180

### CODE REVIEW

**Comment by kiwm** [comment]
ci:test:sf

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:sf

**Comment by kiwm** [comment]
ci:test:sf

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:sf

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @kiwm

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
