### PR TITLE
LPS-180358 [EVP] Enable requesting for more info on Organization's workflow

### PR DESCRIPTION
**Pull request by luisacmn**

### CODE REVIEW

**Comment by luisacmn** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:bundle

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @luisacmn

**Pull request closed without merging**
