### PR TITLE
LPS-187969 [CP 2.0] The activation key table must display DNE for a key with unlimited expiration date

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-187969](https://issues.liferay.com/browse/LPS-187969)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by eduardo-diniz** [comment]
ci:forward

**Comment by eduardo-diniz** [comment]
ci:test:relevant

**Comment by eduardo-diniz** [comment]
ci:forward

**Comment by eduardo-diniz** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by eduardo-diniz** [comment]
ci:forward

**Pull request closed without merging**
