### PR TITLE
LPS-140174 Create Custom Event Hook and validations

### PR DESCRIPTION
**Pull request by kevenleone**
@eliasantosf , @lucas2691, @igordmf

take a look

### CODE REVIEW

**Comment by kevenleone** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-140174 Quick Links Panel</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-140174">Quick Links Panel</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Story</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>0/4 Completed</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Development</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Lucas Soares</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Rafael Dantas</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-143476 Create Fragment Base Structure</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-143476">Create Fragment Base Structure</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Elias Santos</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Lucas Soares</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-143478 Build the Web Content Cards</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-143478">Build the Web Content Cards</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Lucas Soares</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Lucas Soares</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-140160 Navigation menu basic structure</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-140160">Navigation menu basic structure</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Story</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>3/3 Completed</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Ready for QA</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Support QA</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Rafael Dantas</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

39 files changed, 1129 insertions(+), 104 deletions(-)

This PR is too huge for one to review :broken_heart: 

Batman

**Comment by kevenleone** [comment]
ci:stop

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:stop

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by Lucas2691** [comment]
Just starting reviewing :)

**Pull request closed without merging**
