### PR TITLE
LPS-168096 [EVP] Remove Advanced CSS

### PR DESCRIPTION
**Pull request by Claudionilton**

### CODE REVIEW

**Comment by Claudionilton** [comment]
ci:test:sf

**Comment by EuniceTravassos** [comment]
Just starting reviewing :)

**Review by EuniceTravassos — APPROVED** [review]
=)

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
