### PR TITLE
LPS-144343 Add path, macro and test for RaylifeUploadDocuments archive

### PR DESCRIPTION
**Pull request by luanakarla**

### CODE REVIEW

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:site-inicializer-raylife

**Comment by luanakarla** [comment]
ci:test:site-inicializer-raylife

**Comment by luanakarla** [comment]
ci:test:site-initializer-raylife

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:close

**Pull request closed without merging**
