### PR TITLE
LPS-187837 [Marketplace] Fixed Client extension Yaml

### PR DESCRIPTION
**Pull request by welitonpe**

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:test:sf

**Review by juliocezar96 — APPROVED** [review]
Nice job! 🤙

**Comment by welitonpe** [comment]
ci:test:sf

**Review by ytuik — APPROVED** [review]

**Review by joanagrego — APPROVED** [review]

**Comment by joanagrego** [comment]
ci:forward:force

**Comment by welitonpe** [comment]
ci:forward:force

**Pull request closed without merging**
