### PR TITLE
LPS-145324 [CP 2.0] Update Liferay API approach to use facade implementation

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
@kevenleone, within this PR I change the .env to works with "half" hot-update and update some userAccounts to integrate with Okta Session

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: #713

**Pull request closed without merging**
