### PR TITLE
LPS-192753 [Marketplace] Create the Digital Place for Local Public Services Page

### PR DESCRIPTION
**Pull request by ytuik**
https://liferay.atlassian.net/browse/LPS-192753

### CODE REVIEW

**Comment by ytuik** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:forward

**Pull request closed without merging**
