### PR TITLE
Migration from GraphQl to Rest, WIP

### PR DESCRIPTION
**Pull request by welitonpe**

### CODE REVIEW

**Comment by rafaelfs98** [comment]
Just starting reviewing :)

**Comment by Aline160** [comment]
Just starting reviewing :)

**Comment by samuelleolopes** [comment]
Just starting reviewing :)

**Comment by samuelleolopes** [comment]
Just starting reviewing :)

**Comment by caiosouza15** [comment]
Just starting reviewing :)

**Pull request closed without merging**
