### PR TITLE
PRM Automated Test - LPS-173817 | master

### PR DESCRIPTION
**Pull request by marinaasant0s**
[LPS-173817](https://issues.liferay.com/browse/LPS-173817)

### CODE REVIEW

**Comment by marinaasant0s** [comment]
ci:test:sf

**Comment by marinaasant0s** [comment]
ci:test:sf

**Review by AfonsoHSantos — CHANGES_REQUESTED** [review]

**Comment by marinaasant0s** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:stop

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
giphy

**Comment by AfonsoHSantos** [comment]
Hi @marinaasant0s, thanks for working on it! The code looks good to me.
I'm forwarding it!

**Comment by AfonsoHSantos** [comment]
ci:forward

**Comment by AfonsoHSantos** [comment]
Resent here #3256

**Pull request closed without merging**
