### PR TITLE
LPS-171338 [EVP] Create Objects Fields

### PR DESCRIPTION
**Pull request by Claudionilton**

### CODE REVIEW

**Comment by Claudionilton** [comment]
ci:test:sf

**Review by eliasantosf — CHANGES_REQUESTED** [review]
Wrongly formatted commit name. Remove the [EVP] tag from the commit name.

**Comment by Claudionilton** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]

**Review by silasbsi — APPROVED** [review]
LGTM ✅

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
