### PR TITLE
LPS-186027 [EVP] Request notification template creation

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-186027](https://issues.liferay.com/browse/LPS-186027)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:stop

**Comment by kevenleone** [comment]
Pull Request forwarded: https://github.com/brianchandotcom/liferay-portal/pull/136056

**Pull request closed without merging**
