### PR TITLE
LPS-168009 [CP 2.0] [BUG] Error Inviting Two Users at The Same Time

### PR DESCRIPTION
**Pull request by claricebrasil**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
Faltou somente remover o promise.all e mandar o array inteiro para o batch

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:test:osb-site-initializer-customer-portal

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
