### PR TITLE
LPS-166719 [PRM] Fix 'Dismiss' and 'Watch Video' buttons on banner are not working

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @thaynam

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
