### PR TITLE
LPS-173380 [Fixing Ci Routine Raylife Ap]

### PR DESCRIPTION
**Pull request by styller1**
Ticket:
https://issues.liferay.com/browse/LPS-173380

### CODE REVIEW

**Comment by styller1** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:site-initializer-raylife-ap:nocompile

**Comment by styller1** [comment]
ci:test:site-initializer-raylife-ap:nocompile

**Comment by styller1** [comment]
ci:test:site-initializer-raylife-ap:nocompile

**Comment by nikki-pru** [comment]
The tests addressed here are still failing but the paths from this PR are needed for a Poshi release to move forward.
@styller1 please send in fixes for the tests after this PR. Thanks!

cc @CalumR23

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
