### PR TITLE
LPS-152752 Updated useheader and the components that use it, to change header icon according to section

### PR DESCRIPTION
**Pull request by welitonpe**

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by welitonpe** [comment]
ci:test:relevant
ci:test:stable

**Comment by kevenleone** [comment]
ci:stop

**Comment by welitonpe** [comment]
ci:stop

**Pull request closed without merging**
