### PR TITLE
LPS-LPS-174810 [EVP] Create the news structure and content

### PR DESCRIPTION
**Pull request by luisacmn**

### CODE REVIEW

**Comment by luisacmn** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @luisacmn

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
