### PR TITLE
LPS-157143 [Raylife D2C] Populating new policy through D2C flow

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @joanagrego

**Review by silasbsi — APPROVED** [review]
LGTM :fire: thanks @joanagrego

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by welitonpe** [comment]
ci:stop

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
