### PR TITLE
LPS-175694 [EVP] Adjustment in payment confirmation names and relationships

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-175610](https://issues.liferay.com/browse/LPS-175610)
Impedibug: [LPS-176011](https://issues.liferay.com/browse/LPS-176011)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Comment by juliocezar96** [comment]
ci:forward

**Pull request closed without merging**
