### PR TITLE
LPS-143303 Separate logic in two methods. The first one creates the empty layouts (just the entities), and the second populates them with data. This way we can reference the layouts in the data, such as link to pages and other logic

### PR DESCRIPTION
**Pull request by jkappler**
Hi @joseabelenda, the idea of the pull is to separate pages creation with adding content to them. That way we will be able to reference a page in the content of a display page, page template, master page and pages.

Let me know what you think please. 

Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
Sorry, triggered fwd by mistake @kevenleone

**Comment by jkappler** [comment]
ci:reopen

**Comment by joseabelenda** [comment]
Hi @jkappler, very nice!
Thanks.

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
