### PR TITLE
LPS-158459 [Ask] Questions display has a date inconsistency

### PR DESCRIPTION
**Pull request by Lucas2691**

### CODE REVIEW

**Review by jairmedeiros — APPROVED** [review]

**Comment by Lucas2691** [comment]
ci:test:sf

**Comment by Lucas2691** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:forward

**Review by Claudionilton — APPROVED** [review]

**Comment by Lucas2691** [comment]
ci:test:sf

**Comment by Lucas2691** [comment]
ci:close

**Pull request closed without merging**
