### PR TITLE
LPS-171437 Fix RaylifeHomePage#CanViewErrorMessageForWrongZipCode

### PR DESCRIPTION
**Pull request by itstali**

### CODE REVIEW

**Comment by itstali** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:bundle

**Comment by luanakarla** [comment]
ci:help

**Comment by luanakarla** [comment]
ci:test:site-initializer-raylife-d2c

**Comment by luanakarla** [comment]
Closing this pr because the routine errors are another. @itstali let's talk about it.

**Comment by luanakarla** [comment]
ci:close

**Pull request closed without merging**
