### PR TITLE
Lps 162414 [PRM] create dropzone

### PR DESCRIPTION
**Pull request by biellopes00**

### CODE REVIEW

**Comment by biellopes00** [comment]
https://github.com/pt-liferay-solutions/liferay-portal/pull/2401 resend

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:sf

**Pull request closed without merging**
