### PR TITLE
LPS-145363 [CP 2.0] Allow users to remove additional admin during DXP Cloud setup

### PR DESCRIPTION
**Pull request by iagochaves**
https://github.com/pt-liferay-solutions/liferay-portal/pull/941#issue-1149335641

### CODE REVIEW

**Comment by iagochaves** [comment]
ci:test:sf

**Review by igordmf — APPROVED** [review]
Good job!

**Review by claricebrasil — APPROVED** [review]
God job!

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
