### PR TITLE
[Testray] LPS-160219 Fix sort and filter used in autoanalyze

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by thaiscabrals** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:forward

**Pull request closed without merging**
