### PR TITLE
LPS-157337 [CP 2.0] Unit Test For Subscriptions Management

### PR DESCRIPTION
**Pull request by claricebrasil**

### CODE REVIEW

**Comment by claricebrasil** [comment]
ci:test:sf

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
ci:reevaluate:1317401_5312

**Comment by claricebrasil** [comment]
ci:forward

**Pull request closed without merging**
