### PR TITLE
LPS-161174 [ASK] add new filters for search thread

### PR DESCRIPTION
**Pull request by velosofelipe64**

### CODE REVIEW

**Comment by velosofelipe64** [comment]
ci:forward

**Comment by velosofelipe64** [comment]
ci:forward

**Comment by velosofelipe64** [comment]
ci:forward

**Comment by velosofelipe64** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by velosofelipe64** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/123943

**Pull request closed without merging**
