### PR TITLE
LPS-143308 Scope CSS to avoid inject CSS global

### PR DESCRIPTION
**Pull request by silasbsi**

### CODE REVIEW

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by JoMaAlves** [comment]
Just starting reviewing :)

**Comment by samuelleolopes** [comment]
Just starting reviewing :)

**Comment by eduardobbgf** [comment]
Just starting reviewing :)

**Comment by rosig** [comment]
Just starting reviewing :)

**Comment by ilzamcmed** [comment]
Just starting reviewing :)

**Comment by eduardobbgf** [comment]
Just starting reviewing :)

**Pull request closed without merging**
