### PR TITLE
LPS-163923 [Raylife D2C] Login screen creation

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-163923](https://issues.liferay.com/browse/LPS-163923)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Good job! :white_check_mark:

**Review by silasbsi — APPROVED** [review]
LGTM 😁

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
