### PR TITLE
LPS-133944 Restore

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Review by joseabelenda — APPROVED** [review]
LGTM.
Thx

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
@joseabelenda , I think this error is happening because of 

https://github.com/liferay/liferay-portal/blob/master/modules/apps/digital-signature/.lfrbuild-releng-ignore

The build for digital-signature is currently disabled, isn't?

**Comment by joseabelenda** [comment]
@kevenleone I got it.
You can send directly to Brian.
Thx

**Comment by kevenleone** [comment]
resent directly to bchan; https://github.com/brianchandotcom/liferay-portal/pull/103017

**Pull request closed without merging**
