### PR TITLE
LPS-148124 [CP 2.0] Create analytics cloud workspace objects

### PR DESCRIPTION
**Pull request by igordmf**

### CODE REVIEW

**Review by claricebrasil — APPROVED** [review]
Nice job!

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by iagochaves** [comment]
Hey @igordmf could you run format source to fix this?

**Comment by igordmf** [comment]
ci:forward

**Comment by iagochaves** [comment]
Just starting reviewing :)

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by igordmf** [comment]
Closing to reopen

**Pull request closed without merging**
