### PR TITLE
LPS-141697 SF

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
@welitonpe se estiver tudo certo, pode dar forward aqui!

pinga Abelenda se for dar forward

**Comment by jairmedeiros** [comment]
Just starting reviewing :)

**Comment by jairmedeiros** [comment]
Some refinements need to be done. I will create other PR!

**Pull request closed without merging**
