### PR TITLE
[TESTRAY] LPS-159150 Migrate GraphQL to REST

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-159150 [FE] Update CaseResultHeaderActions and useAssignCaseResult to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-159150">[FE] Update CaseResultHeaderActions and useAssignCaseResult to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Breno Silva</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Breno Silva</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-159149 [FE] Move Outlet and EditTest to use REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-159149">[FE] Move Outlet and EditTest to use REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Breno Silva</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Breno Silva</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-159136 [FE]Migrate Auto Complete from GraphQL to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-159136">[FE]Migrate Auto Complete from GraphQL to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Aline Pereira</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Aline Pereira</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158830 [FE] Changes to the TestrayCaseResult file</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158830">[FE] Changes to the TestrayCaseResult file</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Caio Souza</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Caio Souza</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158829 [FE] Changes to the subtask file</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158829">[FE] Changes to the subtask file</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Caio Souza</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Caio Souza</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158614 [FE]Changes in CaseTypeFormModal</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158614">[FE]Changes in CaseTypeFormModal</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Caio Souza</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Caio Souza</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158612 [FE] Create, Edit and Delete Functions for Rest</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158612">[FE] Create, Edit and Delete Functions for Rest</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Caio Souza</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Caio Souza</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158826 Allow viewing all screen information in REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158826">Allow viewing all screen information in REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Aline Pereira</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Aline Pereira</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158603 [FE]Create an Options Table from GraphQL to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158603">[FE]Create an Options Table from GraphQL to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Aline Pereira</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Aline Pereira</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158602  [FE]Delete an Options Table from GraphQL to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158602"> [FE]Delete an Options Table from GraphQL to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Aline Pereira</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Aline Pereira</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158600 [FE] Edit an Options Table from GraphQL to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158600">[FE] Edit an Options Table from GraphQL to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Aline Pereira</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Aline Pereira</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158693 [FE]Create an TestflowTasks Table for REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158693">[FE]Create an TestflowTasks Table for REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Aline Pereira</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Aline Pereira</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158936 [FE] Update UserOutlet from GraphQL to Rest</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158936">[FE] Update UserOutlet from GraphQL to Rest</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Rafael Ferreira</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Wellington Barbosa</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158935 [FE] Update UserForm from GraphQL to Rest</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158935">[FE] Update UserForm from GraphQL to Rest</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Rafael Ferreira</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Wellington Barbosa</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158404 [FE] Update Users Table to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158404">[FE] Update Users Table to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Rafael Ferreira</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158607 [FE] Update Requirements Modal to use REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158607">[FE] Update Requirements Modal to use REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Breno Silva</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Breno Silva</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158609 [FE]  Changing the typing getRequirementQuery fuction</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158609">[FE]  Changing the typing getRequirementQuery fuction</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Breno Silva</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Breno Silva</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158608 [FE] Update useRequirementsCaseActions to use Rest</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158608">[FE] Update useRequirementsCaseActions to use Rest</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Breno Silva</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Breno Silva</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158606 [FE] Update Requirements Outlet to use REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158606">[FE] Update Requirements Outlet to use REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Breno Silva</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Breno Silva</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158604 [FE]  Update Requirement Table to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158604">[FE]  Update Requirement Table to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Breno Silva</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Breno Silva</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158594 [FE] Update endpoint in useRequirementActions</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158594">[FE] Update endpoint in useRequirementActions</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>SE Support</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Breno Silva</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158343 Migrate Manage Users from GraphQL to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158343">Migrate Manage Users from GraphQL to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Story</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>0/3 Completed</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Development</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Rafael Ferreira</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158403 [FE] Move Requirement Form and Outlet to use REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158403">[FE] Move Requirement Form and Outlet to use REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158402 [FE] Update Requirement Table to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158402">[FE] Update Requirement Table to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158401 [FE] Move FactorCategory Form and Outlet to use REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158401">[FE] Move FactorCategory Form and Outlet to use REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158400 [FE] Update FactorCategory Table to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158400">[FE] Update FactorCategory Table to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158358 [FE] Move Case Form and Outlet to use REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158358">[FE] Move Case Form and Outlet to use REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158384 [FE] Move Suite Form and Outlet to use REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158384">[FE] Move Suite Form and Outlet to use REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158399 [FE] Move Build Form and Outlet to use REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158399">[FE] Move Build Form and Outlet to use REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158398 [FE] Update Build Table to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158398">[FE] Update Build Table to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158383 [FE] Update Suite Table to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158383">[FE] Update Suite Table to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158360 [FE] Extend useFormActions inside useFormModal </b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158360">[FE] Extend useFormActions inside useFormModal </a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158359 [FE] Update Case Table to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158359">[FE] Update Case Table to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158356 [FE] Move Routine Form and Outlet to use REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158356">[FE] Move Routine Form and Outlet to use REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158353 [FE] Update Routine Table to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158353">[FE] Update Routine Table to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158352 [FE] Move Project Form and Outlet to use REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158352">[FE] Move Project Form and Outlet to use REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158347 [FE] Update Project Table to REST</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158347">[FE] Update Project Table to REST</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158334 [FE] Add Fetch to SWR</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158334">[FE] Add Fetch to SWR</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-158332 [FE] Add SWR and Setup the cache system</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-158332">[FE] Add SWR and Setup the cache system</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

4551 files changed, 39112 insertions(+), 84878 deletions(-)

This PR is too huge for one to review :broken_heart: 

Batman

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by rafaelfs98** [comment]
Just starting reviewing :)

**Comment by samuelleolopes** [comment]
Just starting reviewing :)

**Comment by Aline160** [comment]
Just starting reviewing :)

**Comment by Aline160** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
