### PR TITLE
LPS-162362 [Raylife AP] Create logic for Applications with Underwriting status

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-158168](https://issues.liferay.com/browse/LPS-158168)

### CODE REVIEW

**Review by silasbsi — APPROVED** [review]
LGTM 🥋

**Comment by kevenleone** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @joanagrego

**Comment by pedro-michel** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
Just starting reviewing :)

**Pull request closed without merging**
