### PR TITLE
LPS-190520 [EVP] Fix reject option opens when Liferay manager click in Approve Service Request

### PR DESCRIPTION
**Pull request by Mylena-Rodrigues**
Ticket: [LPS-190520](https://liferay.atlassian.net/browse/LPS-190520)

### CODE REVIEW

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by Mylena-Rodrigues** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @Mylena-Rodrigues

**Comment by Mylena-Rodrigues** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
ci:test:relevant

**Review by silasbsi — APPROVED** [review]
Good job

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
