### PR TITLE
LPS-165365 [EVP] Create Organization Listing - Staff View

### PR DESCRIPTION
**Pull request by Dianacastrostw**

### CODE REVIEW

**Comment by juliocezarjc** [comment]
Just starting reviewing :)

**Comment by juliocezarjc** [comment]
@Dianacastrostw  When I create an organization and go to the listing, the status field is empty. Can you fix this?

**Comment by juliocezarjc** [comment]
@Dianacastrostw Missed running `gw formatSource`.

**Comment by silasbsi** [comment]
@Dianacastrostw you need to do an update with master.

**Comment by JoMaAlves** [comment]
ci:test:sf

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @Dianacastrostw

**Review by juliocezarjc — APPROVED** [review]
Nice job! 🤙

**Comment by juliocezarjc** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
