### PR TITLE
LPS-159243 [Raylife AP] Create applications table with pagination at the bottom

### PR DESCRIPTION
**Pull request by aecioprado**

### CODE REVIEW

**Comment by aecioprado** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Nice job! :up:

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @aecioprado

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
