### PR TITLE
LPS-171492 [Raylife AP] -  FIX Search bar and Fix Pagination

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-171492](https://issues.liferay.com/browse/LPS-171492) 
[LPS-171803](https://issues.liferay.com/browse/LPS-171803)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Approved! Thank you @eduardo-diniz :white_check_mark:

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
