### PR TITLE
PRM Automated Test - LPS-182116 | master

### PR DESCRIPTION
**Pull request by marinaasant0s**
[LPS-182116](https://liferay.atlassian.net/browse/LPS-182116) - PRMMDFRequestActivities#CanSubmitMDFWithEventInPersonActivity

### CODE REVIEW

**Comment by marinaasant0s** [comment]
ci:test:sf

**Comment by marinaasant0s** [comment]
ci:test:sf

**Comment by marinaasant0s** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
Hi @marinaasant0s, these two commits should be fixed up:

1. https://github.com/pt-liferay-solutions/liferay-portal/pull/4341/commits/2c1017aec37cd7ef20a6adcafd4266a44eabb813
2. https://github.com/pt-liferay-solutions/liferay-portal/pull/4341/commits/43fd9e6869b8cfdcebf59b6fc77da27c70218e2f

**Comment by AfonsoHSantos** [comment]
Hi @marinaasant0s, thanks for working on it.
The code looks good to me.

giphy

**Comment by AfonsoHSantos** [comment]
Could you please rebase your branch with master and run the `afcb` again?

**Review by AfonsoHSantos — APPROVED** [review]
Hi @marinaasant0s, thanks for working on it.
The code looks good to me!

giphy

**Comment by AfonsoHSantos** [comment]
ci:forward

**Comment by marinaasant0s** [comment]
Resent #4572

**Pull request closed without merging**
