### PR TITLE
LPS-133893 Remove display from multiple chat providers

### PR DESCRIPTION
**Pull request by MateusCastro**

### CODE REVIEW

**Review by kevenleone — APPROVED** [review]
LGTM

**Comment by MateusCastro** [comment]
ci:test:sf

**Comment by MateusCastro** [comment]
ci:test:relevant

**Review by joseabelenda — APPROVED** [review]
LGTM
Thanks, @MateusCastro

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
