### PR TITLE
LPS-160051 Questions Suspicious Activity

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:stable

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:stable

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:stable

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:stable

**Comment by joseabelenda** [comment]
ci:test:reevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
https://github.com/pt-liferay-solutions/liferay-portal/pull/1846

**Pull request closed without merging**
