### PR TITLE
LPS-153128 [Raylife AP] Liferay responsive layout to pages of the Raylife Agent Portal

### PR DESCRIPTION
**Pull request by silasbsi**

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Review by JoMaAlves — APPROVED** [review]
LGTM 🔥

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
LGTM :fire: Thanks @silasbsi

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @

**Review by joanagrego — APPROVED** [review]
Nice job!

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
