### PR TITLE
LPS-183750 Fixed undefinded userId on request information of user

### PR DESCRIPTION
**Pull request by welitonpe**

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:test:sf

**Review by Elvinho — COMMENTED** [review]
Nice job 👍🏾

**Review by EugenioAntunes — APPROVED** [review]
Nice job, Man 🐐

**Review by rafaelfs98 — APPROVED** [review]
LGTM :fire:

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
