### PR TITLE
LPS-186792 [EVP] Add default users to EVP

### PR DESCRIPTION
**Pull request by raquelpaiva**
[LPS-184335](https://issues.liferay.com/browse/LPS-184335)

### CODE REVIEW

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @raquelpaiva

**Comment by raquelpaiva** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/136057

**Pull request closed without merging**
