### PR TITLE
LPS-173669 [Raylife D2C/AP] Adjustments on Duplicate Data

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:relevant

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:reevaluate:1297401_6227

**Comment by nikki-pru** [comment]
test:relevant error is unrelated to this pull. 
A similar error occurred in a different PR. This can be forwarded.

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
