### PR TITLE
LPS-170953 CaseResult error fixed

### PR DESCRIPTION
**Pull request by samuelleolopes**

### CODE REVIEW

**Comment by samuelleolopes** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-170953 Create field in table and bring its value</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-170953">Create field in table and bring its value</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Closed</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Caio Souza</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Caio Souza</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

1 file changed, 2 deletions(-)

**Comment by samuelleolopes** [comment]
ci:test:sf

**Review by caiosouza15 — APPROVED** [review]
Thank you @samuelleolopes. Great :fire:

**Review by welitonpe — APPROVED** [review]
Nice work :fire:

**Review by rafaelfs98 — APPROVED** [review]
Very good, my friend :fire:

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by welitonpe** [comment]
Ci:forward

**Comment by samuelleolopes** [comment]
ci:forward

**Comment by samuelleolopes** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/2975

**Pull request closed without merging**
