### PR TITLE
Add Info Cards to Home page

### PR DESCRIPTION
**Pull request by Odrakir1**
This PR adds a grid of Info Cards (new fragment) to the Home page. Attached how it looks.

image

### CODE REVIEW

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by Odrakir1** [comment]
Just starting reviewing :)

**Comment by Odrakir1** [comment]
Just starting reviewing :)

**Pull request closed without merging**
