### PR TITLE
LPS-172701 [EVP] Implementation download CSV

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-172701](https://issues.liferay.com/browse/LPS-172701)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
