### PR TITLE
LPS-188441 [PRM]  Add dynamic fields for proof of performance on MDF Claim 

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:stable

**Comment by caiosouza15** [comment]
Just starting reviewing :)

**Comment by caiosouza15** [comment]
Just starting reviewing :)

**Comment by caiosouza15** [comment]
Just starting reviewing :)

**Comment by thaynam** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
resent https://github.com/pt-liferay-solutions/liferay-portal/pull/4492

**Pull request closed without merging**
