### PR TITLE
LPS-185760 [QUESTIONS] Content Improvements - Rename contents for Feature Request Page

### PR DESCRIPTION
**Pull request by Manda-vit**

### CODE REVIEW

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/4225

**Pull request closed without merging**
