### PR TITLE
LPS-160831 [Raylife AP] Second Vehicle can't change the year after the first one was removed

### PR DESCRIPTION
**Pull request by silasbsi**
Sub-task: [LPS-160831](https://issues.liferay.com/browse/LPS-160831)

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @silasbsi

**Review by joanagrego — APPROVED** [review]
Nice job! :white_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward

**Pull request closed without merging**
