### PR TITLE
LPS-156429 Add Tests for Testray Build Administrator

### PR DESCRIPTION
**Pull request by joelrocha68**
[LPS-156429](https://issues.liferay.com/browse/LPS-156429)

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by barrosdennys** [comment]
ci:forward

**Comment by barrosdennys** [comment]
ci:reopen

**Comment by joelrocha68** [comment]
ci:forward

**Comment by joelrocha68** [comment]
ci:reopen

**Comment by joelrocha68** [comment]
ci:forward

**Pull request closed without merging**
