### PR TITLE
LPS-166775 fixed close button positon in questions

### PR DESCRIPTION
**Pull request by JMachado98**
**Link for issue:** https://issues.liferay.com/browse/LPS-166775

The issue was, the X button from question toast was out of place. It was caused by the `variant="inline"` property.

Following @brenobcos advise i defined the position using CSS and used `!important` to overwrite the previous placement configurations.

### CODE REVIEW

**Comment by JMachado98** [comment]
@kevenleone can you review this PR please?

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by juliocezar96** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
