### PR TITLE
LPS-146129 Add RaylifeKnockoutMobile tests

### PR DESCRIPTION
**Pull request by thaiscabrals**
- LPS-146129 Add RaylifeKnockoutMobile tests
- LPS-146129 SF

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by Paulovcaselli** [comment]
ci:forward

**Pull request closed without merging**
