### PR TITLE
LPS-167980 [EVP] Creating remote app structure

### PR DESCRIPTION
**Pull request by silasbsi**
Subtask: [LPS-167980](https://issues.liferay.com/browse/LPS-167980)

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by Claudionilton** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:test:relevant

**Pull request closed without merging**
