### PR TITLE
LPS-176752 [CP 2.0] Cannot submit LXC SM activation form

### PR DESCRIPTION
**Pull request by kiwm**
Related issue: https://issues.liferay.com/browse/LPS-176752

### CODE REVIEW

**Comment by kiwm** [comment]
ci:test:sf

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:forward

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:forward

**Pull request closed without merging**
