### PR TITLE
LPS-178461 [Raylife D2C/AP]  Insert Other Products Applications through Site Initializer

### PR DESCRIPTION
**Pull request by EugenioAntunes**
Task Related [LPS-178461](https://issues.liferay.com/browse/LPS-178461)

### CODE REVIEW

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
Just starting reviewing :)

**Comment by joanagrego** [comment]
Resent --> [PR](https://github.com/pt-liferay-solutions/liferay-portal/pull/3618)

**Pull request closed without merging**
