### PR TITLE
LPS-162411  LPS-162413 [PRM] Create Claim form

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Comment by DiogoNo** [comment]
Just starting reviewing :)

**Comment by ytuik** [comment]
Just starting reviewing :)

**Pull request closed without merging**
