### PR TITLE
LPS-170277 [Questions] Elasticsearch7 map lastPostDate

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:forward

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Pull request closed without merging**
