### PR TITLE
LPS-159018 Fix on Quote Comparison page

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-159018](https://issues.liferay.com/browse/LPS-159018)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :1st_place_medal: Thanks @joanagrego

**Comment by silasbsi** [comment]
ci:relevant

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
