### PR TITLE
LPS-151106 [Raylife AP] Create Status Chart

### PR DESCRIPTION
**Pull request by Mylena-Rodrigues**

### CODE REVIEW

**Comment by Mylena-Rodrigues** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :fire:

**Comment by silasbsi** [comment]
ci:forward

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Comment by Mylena-Rodrigues** [comment]
ci:forward

**Pull request closed without merging**
