### PR TITLE
LPS-191682 [Marketplace] Add Product Attachment Custom Fields

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by welitonpe — APPROVED** [review]
Good Job :fire: :fire: :fire:

**Comment by joanagrego** [comment]
ci:test:sf

**Review by claricebrasil — APPROVED** [review]
Great job, Joana!

**Comment by claricebrasil** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:reevaluate:1257401_2246

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
