### PR TITLE
LPS-182749 The scroll not working in the table to export case

### PR DESCRIPTION
**Pull request by kildarep**
Hello Reviewer!
Related Issue: https://issues.liferay.com/browse/LPS-182749

To solve the problem the overflow property was changed to 'auto'.

### CODE REVIEW

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Comment by kildarep** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
Hi @kildarep , thanks for your PR!

LGTM 🔥

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
