### PR TITLE
LPS-177993 [Raylife AP] Add External Reference Code Pattern to Raylife Applications

### PR DESCRIPTION
**Pull request by joanagrego**
Related to --> [LPS-177993](https://issues.liferay.com/browse/LPS-177993)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:reevaluate:1297401_7009

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
