### PR TITLE
LPS-146886 Update Selected Quote - Upload Documents to Mobile and Tablet View

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
Hi @kevenleone, I don't know if @silasbsi finished reviewing this PR. He was working with the Agent Portal Setup.

**Comment by kevenleone** [comment]
ci:test:relevant

**Review by silasbsi — COMMENTED** [review]
LGTM :+1:

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
