### PR TITLE
LPS-144322 Fix approach to communicate React with fragment

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:test:stable

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
Just starting reviewing :)

**Comment by jairmedeiros** [comment]
Just starting reviewing :)

**Pull request closed without merging**
