### PR TITLE
LPS-176556 Create Apply Filter button action

### PR DESCRIPTION
**Pull request by rafaelfs98**
[LPS-173527](https://issues.liferay.com/browse/LPS-173527)

### CODE REVIEW

**Comment by rafaelfs98** [comment]
ci:test:sf

**Comment by rafaelfs98** [comment]
ci:test:sf

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Review by welitonpe — APPROVED** [review]
LGTM :Fire:

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
