### PR TITLE
LPS-192206 [CP 2.0] Reverting the form requirements to the previous state and changing the texts

### PR DESCRIPTION
**Pull request by EugenioAntunes**
[LPS-192206](https://liferay.atlassian.net/browse/LPS-192206)

### CODE REVIEW

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Review by pedroliveirav — APPROVED** [review]
Nice! 🚀

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by EugenioAntunes** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Pull request closed without merging**
