### PR TITLE
LPS-169415 [CP 2.0] Fix the message no translate 'no team members'

### PR DESCRIPTION
**Pull request by caiosouza15**

### CODE REVIEW

**Review by JoMaAlves — COMMENTED** [review]
LGTM ​🦖​🌋​ 
Thank you @caiosouza15

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by caiosouza15** [comment]
ci:test:sf

**Comment by caiosouza15** [comment]
ci:test:relevant

**Comment by caiosouza15** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:sf

**Pull request closed without merging**
