### PR TITLE
LPS-171853 [Raylife Ap] Fix Tooltip Adjustments

### PR DESCRIPTION
**Pull request by eduardo-diniz**

### CODE REVIEW

**Review by joanagrego — APPROVED** [review]
Approved! Thank you @eduardo-diniz

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:relevant

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
