### PR TITLE
LPS-161728 [Raylife D2C] Commerce Catalog API tweaks

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-161728](https://issues.liferay.com/browse/LPS-161728)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]

**Review by silasbsi — APPROVED** [review]
LGTM :martial_arts_uniform: Thanks @eliasantosf

**Comment by silasbsi** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
