### PR TITLE
LPS-173414 [PRM] Modified Deal button behavior

### PR DESCRIPTION
**Pull request by Manda-vit**

### CODE REVIEW

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:relevant

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @Manda-vit

**Review by thaynam — APPROVED** [review]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
