### PR TITLE
LPS-191875 [CP 2.0] [Bug] Fixed User can generate a key even without having selected a subscription option

### PR DESCRIPTION
**Pull request by samuelleolopes**
[LPS-191875](https://liferay.atlassian.net/browse/LPS-191875)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:sf

**Review by kylembischof — APPROVED** [review]
Looks good!

**Review by EugenioAntunes — APPROVED** [review]
Nice job, @samuelleolopes  ⚡

**Comment by samuelleolopes** [comment]
ci:forward

**Pull request closed without merging**
