### PR TITLE
LPS-182049 [EVP] Implementation of the custom field for listing the organization when creating the Request

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-182049](https://issues.liferay.com/browse/LPS-182049)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:bundle

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:bundle

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by juliocezar96** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @juliocezar96

**Comment by eliasantosf** [comment]
ci:forward

**Comment by juliocezar96** [comment]
ci:forward

**Comment by juliocezar96** [comment]
ci:forward

**Pull request closed without merging**
