### PR TITLE
LPS-159878 BugFix When I edit the Suites the third time, the edit field does not show the name of the previous updated edit

### PR DESCRIPTION
**Pull request by rafaelfs98**

### CODE REVIEW

**Comment by rafaelfs98** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
