### PR TITLE
LPS-168879 fix AC and DXP Cloud links

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
@claricebrasil , @luisacmn 

Would be possible to take a look? thanks

**Review by claricebrasil — APPROVED** [review]
Looks good to me

**Review by luisacmn — APPROVED** [review]
Ok!!

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
