### PR TITLE
LPS-167527 Fix Integration Tests of MessageBoardMessageResourceTest

### PR DESCRIPTION
**Pull request by gleicelisbino**

### CODE REVIEW

**Comment by gleicelisbino** [comment]
ci:test:sf

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
