### PR TITLE
LPS-186800 [Marketplace] Site navigation buttons do not work as expected

### PR DESCRIPTION
**Pull request by silasbsi**
BUG: [LPS-186800](https://liferay.atlassian.net/browse/LPS-186800)

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by joanagrego** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Pull request closed without merging**
