### PR TITLE
LPS-195262 [Marketplace] Fixing the filter and the search results for the solutions and app page

### PR DESCRIPTION
**Pull request by ytuik**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:forward

**Comment by claricebrasil** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:forward

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by ytuik** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:forward

**Pull request closed without merging**
