### PR TITLE
LPS-159347 [Raylife AP] Set up pagination

### PR DESCRIPTION
**Pull request by pedroliveirav**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Nice job! :white_check_mark:

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @pedroliveirav

**Review by silasbsi — APPROVED** [review]
LGTM 🥋

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
