### PR TITLE
[Questions] Elasticsearch7 map lastPostDate

### PR DESCRIPTION
**Pull request by gleicelisbino**

### CODE REVIEW

**Comment by gleicelisbino** [comment]
ci:test:sf

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:clo

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/2852

**Pull request closed without merging**
