### PR TITLE
LPS-160961 [Site Initializer] Implement Segments Experience

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:forward

**Comment by juliocezarjc** [comment]
Just starting reviewing :)

**Comment by juliocezarjc** [comment]
Just starting reviewing :)

**Comment by nNilton** [comment]
ci:reevaluate:1317401_5241

**Comment by joseabelenda** [comment]
ci:test:relevant

**Pull request closed without merging**
