### PR TITLE
PRM Automated Test - LPS-195724

### PR DESCRIPTION
**Pull request by KevinQueiroz**
[LPS-195724](https://liferay.atlassian.net/browse/LPS-195724) - PRMMDFRequest#CanDeleteInDraftStatus

### CODE REVIEW

**Comment by KevinQueiroz** [comment]
ci:test:sf

**Comment by KevinQueiroz** [comment]
@kenduenwald

**Comment by KevinQueiroz** [comment]
[LPS-195724](https://liferay.atlassian.net/browse/LPS-195724) - PRMMDFRequest#CanDeleteInDraftStatus

**Comment by guivilarim** [comment]
ci:test:osb-site-initializer-partner-portal

**Comment by KevinQueiroz** [comment]
ci:test:sf

**Comment by guivilarim** [comment]
ci:forward

**Pull request closed without merging**
