### PR TITLE
LPS-183144 [PRM] Make the PRM create some data when created

### PR DESCRIPTION
**Pull request by luisacmn**

### CODE REVIEW

**Comment by luisacmn** [comment]
ci:test:sf

**Comment by luisacmn** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:stop

**Comment by thaynam** [comment]
ci:forward

**Comment by luisacmn** [comment]
ci:test:sf

**Pull request closed without merging**
