### PR TITLE
LPS-165870 Run job scheduler script via API

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:sf

**Review by joseabelenda — APPROVED** [review]

**Comment by joseabelenda** [comment]
ci:forward

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/2446

**Pull request closed without merging**
