### PR TITLE
LPS-134540 Add Image Processor and PDF checking to create better Preview experience

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Review by joseabelenda — APPROVED** [review]
LGTM.
Thanks @kevenleone

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
