### PR TITLE
LPS-160716 TR2 Automated Test | master

### PR DESCRIPTION
**Pull request by joelrocha68**
[LPS-160717](https://issues.liferay.com/browse/LPS-160717)
[LPS-169435](https://issues.liferay.com/browse/LPS-169435)
[LPS-169436](https://issues.liferay.com/browse/LPS-169436)
[LPS-161402](https://issues.liferay.com/browse/LPS-161402)
[LPS-160723](https://issues.liferay.com/browse/LPS-160723)
[LPS-169401](https://issues.liferay.com/browse/LPS-169401)
[LPS-169430](https://issues.liferay.com/browse/LPS-169430)
[LPS-160716](https://issues.liferay.com/browse/LPS-160716)

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by nikki-pru** [comment]
[Passing](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2232851841&testrayRunId=2232852243)
LPS-161402 - TestraySubtaskAdministrator#AdminCanMergeInAnalysisSubtaskWithCompletedSubtask
LPS-160723 - TestraySubtaskAdministrator#AdminCanReturnToOpenSubtask
LPS-169430 - TestraySubtaskAdministrator#AdminCanMergeCompleteSubtaskWithOpenSubtask
LPS-160716 - TestraySubtaskAdministrator#AdminCanCompleteSubtaskAsFailing
LPS-160717 - TestraySubtaskAdministrator#AdminCanCompleteSubtaskAsPassing
LPS-169435 - TestraySubtaskAdministrator#AdminCanCompleteSubtaskAsTestFix

[Failing](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2232851841&testrayRunId=2232852243)
LPS-169436 - TestraySubtaskAdministrator#AdminCanCompleteSubtaskAsBlocked
LPS-169401 - TestraySubtaskAdministrator#AdminCanCancelMergeSubtask

@joelrocha68 , I will push this forward since most of the tests are passing. Can you please send in a separate fix for the two that are failing?

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
