### PR TITLE
LPS-160469 [Raylife AP] fix Product chart request api

### PR DESCRIPTION
**Pull request by silasbsi**
Sub-task: [LPS-160469](https://issues.liferay.com/browse/LPS-160469)

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Nice job! :arrow_up:

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @silasbsi

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
