### PR TITLE
LPS-162401 Refactor Testray Factors

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by nNilton** [comment]
ci:reevaluate:1287401_4259

**Comment by kevenleone** [comment]
ci:forward

**Comment by nNilton** [comment]
ci:reevaluate:1287401_4259

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
