### PR TITLE
LPS-185369 [PRM] [BUG] Error when submitting MDF the status is in draft

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by thaynam** [comment]
[resent](https://github.com/pt-liferay-solutions/liferay-portal/pull/4155)

**Pull request closed without merging**
