### PR TITLE
LPS-180659, LPS-178110, LPS-180652 [CP 2.0] Add a new listing for Liferay Versions , Cannot submit Email, Add Search by Project Code

### PR DESCRIPTION
**Pull request by JoMaAlves**
Tickets solved here:
- [LPS-180652](https://issues.liferay.com/browse/LPS-180652)
- [LPS-178110](https://issues.liferay.com/browse/LPS-178110)
- [LPS-180659](https://issues.liferay.com/browse/LPS-180659)

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
