### PR TITLE
LPS-176588 [EVP]  Improved Footer and Details Button

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-176588](https://issues.liferay.com/browse/LPS-176588)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:stop

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @juliocezar96

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:forward

**Pull request closed without merging**
