### PR TITLE
LPS-172704 [PRM] Image add to Annoucements is off padding in home page

### PR DESCRIPTION
**Pull request by ericthmoritsuka**
Related Issue: https://issues.liferay.com/browse/LPS-172704

### CODE REVIEW

**Comment by ericthmoritsuka** [comment]
ci:test:sf

**Comment by ericthmoritsuka** [comment]
ci:test:relevant

**Comment by ericthmoritsuka** [comment]
I tested it and it looks like the images are not showing in the announcement anymore. They are still showing in the modal, though, as requested.

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by ericthmoritsuka** [comment]
ci:test:relevant

**Comment by ericthmoritsuka** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:forward

**Comment by ericthmoritsuka** [comment]
@thaynam I will resend the PR in an updated branch.

**Pull request closed without merging**
