### PR TITLE
LPS-157891 [Raylife AP] Consume API to Persona and Business categories

### PR DESCRIPTION
**Pull request by silasbsi**
Subtask: [LPS-157891](https://issues.liferay.com/browse/LPS-157891)

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @silasbsi

**Review by JoMaAlves — COMMENTED** [review]
LGTM

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
