### PR TITLE
LPS-184211 Provide Information Templates in Site Initializer Extender

### PR DESCRIPTION
**Pull request by joseabelenda**
.

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:reevaluate:1317401_8016

**Comment by nNilton** [comment]
ci:forward

**Pull request closed without merging**
