### PR TITLE
LPS-154804 and LPS-159019 and LPS-159021 [PRM] Create form goals and components

### PR DESCRIPTION
**Pull request by joaosvassis**

### CODE REVIEW

**Comment by ytuik** [comment]
Just starting reviewing :)

**Comment by DiogoNo** [comment]
Just starting reviewing :)

**Comment by DiogoNo** [comment]
Just starting reviewing :)

**Comment by EuniceTravassos** [comment]
Just starting reviewing :)

**Comment by ytuik** [comment]
Just starting reviewing :)

**Comment by jackelyneaquino** [comment]
jackelyneaquino

**Pull request closed without merging**
