### PR TITLE
LPS-175978 [EVP] Make it possible to read an entire content of a News in the modal

### PR DESCRIPTION
**Pull request by luisacmn**

### CODE REVIEW

**Comment by luisacmn** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @luisacmn

**Comment by eliasantosf** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
