### PR TITLE
LPS-185919 The case parameters are accepting duplicate teams and components

### PR DESCRIPTION
**Pull request by EugenioAntunes**
[LPS-185919](https://issues.liferay.com/browse/LPS-185919)

### CODE REVIEW

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Review by welitonpe — APPROVED** [review]
LGTM :fire:

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by EugenioAntunes** [comment]
ci:forward

**Comment by kevenleone** [comment]
Pull Request forwarded: https://github.com/brianchandotcom/liferay-portal/pull/135621

**Pull request closed without merging**
