### PR TITLE
LPS-193674 [MARKETPLACE] App Dashboard Menu Responsiveness and Products Pagination Adjustments 

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Review by claricebrasil — APPROVED** [review]
Good job!

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:reevaluate:1397401_7034

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by itstali** [comment]
The errors on ci are not related to this PR :))

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
ci:reopen

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
Resent --> [PR](https://github.com/pt-liferay-solutions/liferay-portal/pull/4722)

**Pull request closed without merging**
