### PR TITLE
LPS-146207 [CP 2.0] Improve pattern file names

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Comment by igordmf** [comment]
Just starting reviewing :)

**Comment by igordmf** [comment]
Just starting reviewing :)

**Comment by igordmf** [comment]
Just starting reviewing :)

**Comment by igordmf** [comment]
Just starting reviewing :)

**Comment by igordmf** [comment]
Just starting reviewing :)

**Comment by igordmf** [comment]
Just starting reviewing :)

**Comment by igordmf** [comment]
Just starting reviewing :)

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Good job on that, CP!

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
