### PR TITLE
LPS-185655 [PRM] Add standalone action for MDF Claim

### PR DESCRIPTION
**Pull request by luisacmn**

### CODE REVIEW

**Comment by luisacmn** [comment]
ci:test:sf

**Comment by luisacmn** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:solutions-acceptance

**Review by AfonsoHSantos — APPROVED** [review]
The test failures on `solutions-acceptance` aren't related with this PR.

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by thaynam** [comment]
[resent](https://github.com/pt-liferay-solutions/liferay-portal/pull/4324)

**Pull request closed without merging**
