### PR TITLE
LPS-192762 [Marketplace] Page Open Square CRM

### PR DESCRIPTION
**Pull request by juliocezar96**
subtask : [LPS-192762](https://liferay.atlassian.net/browse/LPS-192762)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
