### PR TITLE
LPS-188236 Fix Zip Code and Phone field to accept more characters

### PR DESCRIPTION
**Pull request by caiosouza15**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by AfonsoHSantos** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Review by AfonsoHSantos — APPROVED** [review]
Relevant failures aren't related with this PR changes

**Comment by caiosouza15** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/137335 resent

**Pull request closed without merging**
