### PR TITLE
Refactor Click to chat LRQA-82291 | Master

### PR DESCRIPTION
**Pull request by marinaasant0s**
Ticket Refactor - [LRQA-82291](https://liferay.atlassian.net/browse/LRQA-82291)

### CODE REVIEW

**Comment by marinaasant0s** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:click-to-chat

**Comment by nikki-pru** [comment]
Failures are not related

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
