### PR TITLE
LPS-159819 BugFix Do not appears the task details informations

### PR DESCRIPTION
**Pull request by rafaelfs98**

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by rafaelfs98** [comment]
ci:forward

**Comment by rafaelfs98** [comment]
ci:stop

**Pull request closed without merging**
