### PR TITLE
[LPS-145165 & LPS-145656 & LPS-145657] Activation Form Card - DXP Cloud

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by igordmf** [comment]
Just starting reviewing :)

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
