### PR TITLE
LPS-186337 Created Object definition to jiraOAuth

### PR DESCRIPTION
**Pull request by welitonpe**

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:reopen

**Comment by Elvinho** [comment]
Just starting reviewing :)

**Comment by Elvinho** [comment]
Just starting reviewing :)

**Review by Elvinho — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/4320

**Pull request closed without merging**
