### PR TITLE
LPS-150939 [CP 2.0] Add CP2NewKeyGenerationDxpPart2A tests

### PR DESCRIPTION
**Pull request by MathausC**
https://issues.liferay.com/browse/LPS-150939

### CODE REVIEW

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:relevant

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:stable

**Comment by MathausC** [comment]
ci:test:relevant

**Comment by MathausC** [comment]
ci:stop

**Comment by MathausC** [comment]
ci:test:stable

**Comment by MathausC** [comment]
ci:test:relevant

**Comment by MathausC** [comment]
ci:test:relevant

**Comment by barrosdennys** [comment]
ci:forward

**Comment by MathausC** [comment]
PR continued on #2375

**Pull request closed without merging**
