### PR TITLE
[Site Initializer] LPS-159613 Update addStructuredContentFolders

### PR DESCRIPTION
**Pull request by Andrefes565**

### CODE REVIEW

**Comment by Andrefes565** [comment]
ci:teste:sf

**Comment by nNilton** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
ci:test:sf

**Review by nNilton — CHANGES_REQUESTED** [review]

**Comment by Andrefes565** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
ci:test:sf

**Comment by nNilton** [comment]
waiting for https://github.com/pt-liferay-solutions/liferay-portal/pull/1829 be merged first

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/1981

**Pull request closed without merging**
