### PR TITLE
LPS-160961 [INFRA] Implement Segments Experience

### PR DESCRIPTION
**Pull request by TamyrisTorres**

### CODE REVIEW

**Comment by juliocezar96** [comment]
Just starting reviewing :)

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/2516

**Pull request closed without merging**
