### PR TITLE
LPS-158614 Changes in CaseTypeFormModal

### PR DESCRIPTION
**Pull request by welitonpe**

### CODE REVIEW

**Comment by brenobcos** [comment]
Just starting reviewing :)

**Comment by Aline160** [comment]
Just starting reviewing :)

**Comment by caiosouza15** [comment]
Just starting reviewing :)

**Comment by Aline160** [comment]
Just starting reviewing :)

**Comment by Aline160** [comment]
Just starting reviewing :)

**Comment by Aline160** [comment]
Just starting reviewing :)

**Pull request closed without merging**
