### PR TITLE
LPS-144865 [CP 2.0] Project Card & Font Styles Refinement

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:test:stable

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
