### PR TITLE
LPS-183558 Loading Added in Testflow

### PR DESCRIPTION
**Pull request by Elvinho**

### CODE REVIEW

**Comment by Elvinho** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-183558 [FE] Add Loading in Testflow</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-183558">[FE] Add Loading in Testflow</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>SE Support</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Elvison Victor</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

10 files changed, 21 insertions(+), 20 deletions(-)

**Review by EugenioAntunes — APPROVED** [review]
Nice job, Man 🐐

**Review by rafaelfs98 — APPROVED** [review]
LGTM :fire:

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Review by kevenleone — APPROVED** [review]
Very good!


Thanks @Elvinho

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
