### PR TITLE
LPS-171186 Setting useCache to false

### PR DESCRIPTION
**Pull request by lucasmiranda0**
[LPS-171186](https://issues.liferay.com/browse/LPS-171186) Setting useCache to false, this way the edit button will make a new requisition, instead of searching data on cache.

### CODE REVIEW

**Comment by lucasmiranda0** [comment]
ci:test:sf

**Comment by lucasmiranda0** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Thanks @lucasmiranda0

**Comment by lucasmiranda0** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
