### PR TITLE
LPS-160750 [Raylife AP] Creating PRODUCT PERFORMANCE Product Filter Requests

### PR DESCRIPTION
**Pull request by JoMaAlves**
Task: [LPS-160750](https://issues.liferay.com/browse/LPS-160750)

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Great job! :white_check_mark:

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @JoMaAlves

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
