### PR TITLE
LPS-181912 [Raylife Ap] Add vehicle images 

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-181912](https://issues.liferay.com/browse/LPS-181912)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
Hi @eduardo-diniz, please resend this PR in another branch.

**Pull request closed without merging**
