### PR TITLE
LPS-145599 [Raylife] Fix Raylife setUp and add paths

### PR DESCRIPTION
**Pull request by thaiscabrals**
- LPS-145599 Fix Raylife setUp and add paths
- LPS-145599 SF

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by Paulovcaselli** [comment]
Just starting reviewing :)

**Comment by Paulovcaselli** [comment]
Just starting reviewing :)

**Pull request closed without merging**
