### PR TITLE
LPS-181906[EVP] Organization status didn't change after Finance approval

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-181906](https://issues.liferay.com/browse/LPS-181906)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:bundle

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
