### PR TITLE
LPS-154312 - Update ci, test properties and tests from site-initializer-raylife to site-initializer-raylife-d2c

### PR DESCRIPTION
**Pull request by alexcandidos**
https://issues.liferay.com/browse/LPS-154312

### CODE REVIEW

**Comment by alexcandidos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
ci:test:site-initializer-raylife-d2c

**Comment by joelrocha68** [comment]
ci:forward

**Comment by joelrocha68** [comment]
ci:forward

**Pull request closed without merging**
