### PR TITLE
LPS-166208 [Raylife AP] Create Policy Auto Details page

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-156883](https://issues.liferay.com/browse/LPS-156883)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
