### PR TITLE
LPS-183630 [Marketplace] Add Commerce Channel, Product Options, Users and Accounts.

### PR DESCRIPTION
**Pull request by joanagrego**
Related to --> [LPS-183566](https://issues.liferay.com/browse/LPS-183566)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:stop

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/3951

**Pull request closed without merging**
