### PR TITLE
LPS-192890 [PRM] Contents on Activities detail page are duplicate when filling a MDF request

### PR DESCRIPTION
**Pull request by Manda-vit**

### CODE REVIEW

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by thaynam** [comment]
[resent](https://github.com/pt-liferay-solutions/liferay-portal/pull/4634)

**Pull request closed without merging**
