### PR TITLE
LPS-175720 Filter layout created

### PR DESCRIPTION
**Pull request by welitonpe**

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Review by samuelleolopes — APPROVED** [review]

**Comment by welitonpe** [comment]
ci:forward

**Comment by kevenleone** [comment]
Pull Request forwarded: https://github.com/brianchandotcom/liferay-portal/pull/130424

**Pull request closed without merging**
