### PR TITLE
LPS-182811 [EVP] Create Finance review and flow

### PR DESCRIPTION
**Pull request by raquelpaiva**
[LPS-182811 Finance Review on Funds Request] (https://issues.liferay.com/browse/LPS-181773)

### CODE REVIEW

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by raquelpaiva** [comment]
ci:test:sf

**Comment by raquelpaiva** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @raquelpaiva

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
