### PR TITLE
LPS-155671 [PRM] Search Page

### PR DESCRIPTION
**Pull request by EuniceTravassos**

### CODE REVIEW

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:stop

**Comment by ytuik** [comment]
Just starting reviewing :)

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
