### PR TITLE
MP2 Automation Test: LPS-185600, LPS-185601 and LPS-185602 | master

### PR DESCRIPTION
**Pull request by luanakarla**
Ticket:
[LPS-184212](https://issues.liferay.com/browse/LPS-184212)

Tests:
Marketplace#ProductsOptionsAreCreatedForMP20
Marketplace#SpecificationGroupAreCreatedForMP20
Marketplace#SpecificationLabelAreCreatedForMP20

### CODE REVIEW

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:site-initializer-liferay-marketplace

**Comment by joelrocha68** [comment]
LGTM!

**Comment by luanakarla** [comment]
ci:forward

**Comment by luanakarla** [comment]
ci:stop

**Comment by luanakarla** [comment]
ci:close

**Comment by luanakarla** [comment]
ci:reopen

**Comment by luanakarla** [comment]
ci:forward

**Comment by luanakarla** [comment]
ci:forward

**Comment by luanakarla** [comment]
ci:stop

**Comment by luanakarla** [comment]
ci:close

**Comment by luanakarla** [comment]
ci:reopen

**Comment by luanakarla** [comment]
ci:forward

**Comment by luanakarla** [comment]
ci:reopen

**Comment by luanakarla** [comment]
ci:forward

**Pull request closed without merging**
