### PR TITLE
LPS-156555 [Raylife AP] Update Dashboard Layout

### PR DESCRIPTION
**Pull request by JoMaAlves**
Task: [LPS-156555](https://issues.liferay.com/browse/LPS-156555)

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Resend: https://github.com/pt-liferay-solutions/liferay-portal/pull/1576

**Pull request closed without merging**
