### PR TITLE
LPS-183144 [PRM] Make the PRM create some data when created

### PR DESCRIPTION
**Pull request by luisacmn**

### CODE REVIEW

**Comment by luisacmn** [comment]
ci:test:sf

**Comment by luisacmn** [comment]
ci:test:sf

**Comment by thaynam** [comment]
[resent](https://github.com/pt-liferay-solutions/liferay-portal/pull/4146)

**Comment by luisacmn** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
I just sent SF fix: https://github.com/ling-alan-huang/liferay-portal/pull/1882

**Comment by luisacmn** [comment]
> I just sent SF fix: [ling-alan-huang#1882](https://github.com/ling-alan-huang/liferay-portal/pull/1882)

Thank you!

**Pull request closed without merging**
