### PR TITLE
LPS-164596 [EVP] Irregular button padding

### PR DESCRIPTION
**Pull request by JoMaAlves**
Bug: [LPS-164596](https://issues.liferay.com/browse/LPS-164596)

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Review by juliocezarjc — APPROVED** [review]
Nice job! 🤙

**Comment by JoMaAlves** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :+1: :martial_arts_uniform: Thanks @JoMaAlves

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
