### PR TITLE
LPS-192159 [CP 2.0] Applied Filter Visibility Validation

### PR DESCRIPTION
**Pull request by samuelleolopes**
[LPS-148378](https://liferay.atlassian.net/browse/LPS-148378)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by samuelleolopes** [comment]
ci:forward

**Review by Aline160 — APPROVED** [review]
Great!!

**Pull request closed without merging**
