### PR TITLE
LPS-140660 Raylife D2C Mobile Design for Property Info Page

### PR DESCRIPTION
**Pull request by alvarolealdl**

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Review by silasbsi — COMMENTED** [review]
LGTM :fire:

**Comment by silasbsi** [comment]
@kevenleone could you make a new review?

**Comment by alvarolealdl** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
