### PR TITLE
LPS-190132 [EVP] Update Request Status When Organization Is Review

### PR DESCRIPTION
**Pull request by Elvinho**

### CODE REVIEW

**Comment by Elvinho** [comment]
ci:test:sf

**Comment by Elvinho** [comment]
ci:test:stable

**Comment by Elvinho** [comment]
ci:test:relevant

**Comment by Elvinho** [comment]
ci:test:stable

**Comment by Elvinho** [comment]
ci:test:relevant

**Comment by Elvinho** [comment]
ci:test:relevant

**Comment by Elvinho** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by MGabriellaS** [comment]
These failures are not related to this PR

**Comment by Elvinho** [comment]
ci:test:relevant

**Pull request closed without merging**
