### PR TITLE
LPS-182633 [CP 2.0] Enterprise search activation key terms list doesn't include all terms

### PR DESCRIPTION
**Pull request by pedroliveirav**
[LPS-182633](https://issues.liferay.com/browse/LPS-182633)

### CODE REVIEW

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
