### PR TITLE
LPS-194816 [CP 2.0] Change critical incident contacts on the team members card in real time

### PR DESCRIPTION
**Pull request by pedroliveirav**
[LPS-194816](https://liferay.atlassian.net/browse/LPS-194816)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Comment by pedroliveirav** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/140186

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/140189

**Pull request closed without merging**
