### PR TITLE
LPS-183685 The case parameters do not remain selected when editing

### PR DESCRIPTION
**Pull request by EugenioAntunes**
[LPS-183685](https://issues.liferay.com/browse/LPS-183685) Developed by @rafaelfs98 
[LPS-184733](https://issues.liferay.com/browse/LPS-184733)

### CODE REVIEW

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Review by rafaelfs98 — APPROVED** [review]
LGTM :fire:

**Review by welitonpe — APPROVED** [review]
LGTM :fire: :fire:

**Comment by welitonpe** [comment]
ci:forward

**Pull request closed without merging**
