### PR TITLE
LPS-144190 Gather CP 2.0 PRs

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/111440
https://github.com/brianchandotcom/liferay-portal/pull/111452
https://github.com/brianchandotcom/liferay-portal/pull/111467
https://github.com/brianchandotcom/liferay-portal/pull/111494
https://github.com/brianchandotcom/liferay-portal/pull/111538
https://github.com/brianchandotcom/liferay-portal/pull/111560

**Comment by jairmedeiros** [comment]
Just starting reviewing :)

**Comment by luanakarla** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by joaosvassis** [comment]
Just starting reviewing :)

**Comment by claricebrasil** [comment]
Just starting reviewing :)

**Comment by Abigailmelo** [comment]
Just starting reviewing :)

**Comment by Abigailmelo** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by aildsonf** [comment]
Just starting reviewing :)

**Comment by iagochaves** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
All PRs merged by Brian

**Pull request closed without merging**
