### PR TITLE
LPS-189899 [C.P 2.0] Fix Filters don't working with translation

### PR DESCRIPTION
**Pull request by eduardo-diniz**

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by eduardo-diniz** [comment]
ci:test:stable

**Comment by samuelleolopes** [comment]
ci:forward

**Pull request closed without merging**
