### PR TITLE
LPS-178702 [Site Initializer] Add defaultValue field in addExpandoColumns

### PR DESCRIPTION
**Pull request by eliasantosf**

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by nNilton — APPROVED** [review]

**Comment by nNilton** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:close

**Pull request closed without merging**
