### PR TITLE
LPS-152854 [CP 2.0] - Deactivate key - Before selecting any keys - DXP

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LPS-152624

Skipped [LPS-152853](https://issues.liferay.com/browse/LPS-152853) because it is covered.

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by epark18** [comment]
@barrosdennys I will resend this with https://github.com/brianchandotcom/liferay-portal/pull/122911#issuecomment-1242582131because of rebase errors

**Comment by epark18** [comment]
See https://github.com/pt-liferay-solutions/liferay-portal/pull/2134.

**Pull request closed without merging**
