### PR TITLE
LPS-184089 Add options to testflows rightclick

### PR DESCRIPTION
**Pull request by Elvinho**

### CODE REVIEW

**Comment by Elvinho** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

2 files changed, 27 insertions(+), 5 deletions(-)

**Review by welitonpe — APPROVED** [review]
LGTM :fire:

**Review by EugenioAntunes — APPROVED** [review]
Nice job, Man 🐐

**Review by kevenleone — APPROVED** [review]
VERY GOOD!

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
