### PR TITLE
LPS-161266 Adding info to original posts

### PR DESCRIPTION
**Pull request by Claudionilton**

### CODE REVIEW

**Comment by Claudionilton** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
@Claudionilton it looks good, but the buildLang is missing here:

Always, after adding translation, you must:

1. go to modules/apps/portal-language/portal-language-lang
2. gw buildLang
3. git add . (liferay-portal)
4. git commit -m 'LPS-YYYYYY buildLang' 

After create this commit, push it here, thanks 🗡️

**Review by kevenleone — CHANGES_REQUESTED** [review]
Code looks good, but buildLang is missing

**Comment by Claudionilton** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/1999

**Pull request closed without merging**
