### PR TITLE
LPS-191518 [Marketplace] Fixing the pointer for the dialect components

### PR DESCRIPTION
**Pull request by ytuik**
https://liferay.atlassian.net/browse/LPS-191518

### CODE REVIEW

**Comment by ytuik** [comment]
ci:test:sf

**Comment by ytuik** [comment]
ci:test:site-initializer-liferay-marketplace:nocompile

**Review by silasbsi — APPROVED** [review]
Good job

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:reevaluate:1297401_7734

**Comment by ytuik** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:forceForward

**Comment by ytuik** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:forward

**Pull request closed without merging**
