### PR TITLE
Add Setup Automation MP project: LPS-184212 | master

### PR DESCRIPTION
**Pull request by luanakarla**
Ticket:
[LPS-184212](https://issues.liferay.com/browse/LPS-184212)

### CODE REVIEW

**Comment by luanakarla** [comment]
ci:test:sf

**Review by renato-araujo-liferay — APPROVED** [review]
WD @luanakarla

**Comment by luanakarla** [comment]
ci:forward

**Comment by luanakarla** [comment]
ci:forward

**Comment by luanakarla** [comment]
ci:close

**Pull request closed without merging**
