### PR TITLE
LPS-167649 [Site Initializer] Add Aggregation Fields to Site Initializer Object Definition

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:stop

**Comment by nNilton** [comment]
ci:close

**Comment by nNilton** [comment]
I'll resend

**Comment by nNilton** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/2705

**Pull request closed without merging**
