### PR TITLE
LPS-159616 Update Layout

### PR DESCRIPTION
**Pull request by gleicelisbino**

### CODE REVIEW

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1387401_3432

**Comment by michaelhashimoto** [comment]
@gleicelisbino  - I kind of suspect this might be a real issue because in upstream these tests are passing pretty consistently:
https://testray.liferay.com/home/-/testray/case_results/1965377036/history?tab=result&hideFilterPin=true

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Pull request closed without merging**
