### PR TITLE
LPS-172294 [PRM] Add Fragment with States in MDF Claim and Request Detail

### PR DESCRIPTION
**Pull request by thaynam**
[LPS-172212](https://issues.liferay.com/browse/LPS-172212)
Is not possible to submit a Deal Registration

[LPS-172292](https://issues.liferay.com/browse/LPS-172292)
[FE] Add Fragment with Missing States in MDF Request Detail

[PS-172294](https://issues.liferay.com/browse/LPS-172294)
[FE] Add Fragment with Missing States in MDF Claim Detail

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Review by ytuik — COMMENTED** [review]
LGTM!

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by thaynam** [comment]
rebase error, resent [3081](https://github.com/pt-liferay-solutions/liferay-portal/pull/3081)

**Pull request closed without merging**
