### PR TITLE
LPS-149416 [CP 2.0] Create new fields for koroneikiAccount and accountSubscriptionGroups

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Review by igordmf — APPROVED** [review]
You woke up and discover yourself an unbelievable guy

**Review by Lucas2691 — APPROVED** [review]
Same report that @igordmf ! Awesome!

**Review by joanagrego — APPROVED** [review]
Beautiful.

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
