### PR TITLE
LPS-166823 [Raylife AP] Create logic to consume data for Policy Expiring Chart

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-146255](https://issues.liferay.com/browse/LPS-146255)

### CODE REVIEW

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Review by eliasantosf — APPROVED** [review]

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
