### PR TITLE
LPS-185316 [Marketplace] Make the new invited member grey on the Members List

### PR DESCRIPTION
**Pull request by ytuik**
[https://issues.liferay.com/browse/LPS-185316](https://github.com/pt-liferay-solutions/liferay-portal/pull/4205)

### CODE REVIEW

**Comment by ytuik** [comment]
ci:test:sf

**Comment by ytuik** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by ytuik** [comment]
ci:test:stable

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by ytuik** [comment]
ci:forward

**Pull request closed without merging**
