### PR TITLE
LPS-149102 [CP 2.0] Create analytics cloud data center location objects

### PR DESCRIPTION
**Pull request by igordmf**

### CODE REVIEW

**Review by jairmedeiros — APPROVED** [review]

**Review by claricebrasil — APPROVED** [review]
Amazing, job!

**Review by iagochaves — APPROVED** [review]

**Comment by iagochaves** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by iagochaves** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by iagochaves** [comment]
ci:forward

**Comment by igordmf** [comment]
ci:forward

**Comment by igordmf** [comment]
ci:forward

**Pull request closed without merging**
