### PR TITLE
LPS-159791 [Raylife AP] Creating PRODUCT PERFORMANCE Product Filters Layout

### PR DESCRIPTION
**Pull request by JoMaAlves**
Task: [LPS-159791](https://issues.liferay.com/browse/LPS-159791)

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Great job! :arrow_up:

**Comment by JoMaAlves** [comment]
ci:relevant

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @JoMaAlves

**Comment by JoMaAlves** [comment]
ci:relevant:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
