### PR TITLE
LPS-186904 [PRM] - Move object fields from object definitions

### PR DESCRIPTION
**Pull request by luisacmn**

### CODE REVIEW

**Comment by luisacmn** [comment]
ci:test:sf

**Comment by luisacmn** [comment]
ci:test:solutions-acceptance

**Review by AfonsoHSantos — APPROVED** [review]
The test failures (solutions-acceptance) aren't related with this PR

**Comment by luisacmn** [comment]
> The test failures (solutions-acceptance) aren't related with this PR

Thanks, @AfonsoHSantos

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
