### PR TITLE
LPS 146306 - Take into account replaceable values in site initializer for fragments and fragment compositions

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
@jkappler first of all thank you so much for your PR https://github.com/pt-liferay-solutions/liferay-portal/pull/819.
I made some changes and sent this PR.
If my changes make sense we can forward.
What do you think?

Thanks!

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Looks amazing @joseabelenda! Thanks again as always!

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
