### PR TITLE
LPS-171428 & LPS-171259 [PRM] Stop Sending MDF Claim Draft to Salesforce and Taking Rejected and Expired Claims out of count

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:test:stable

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
Re-sent over https://github.com/pt-liferay-solutions/liferay-portal/pull/2989

**Pull request closed without merging**
