### PR TITLE
[PRM] Bugs and Improvements requested by Channel Team

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @thaynam

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by Elvinho** [comment]
resent https://github.com/pt-liferay-solutions/liferay-portal/pull/4675

**Pull request closed without merging**
