### PR TITLE
EVP Automated Test LPS-166351,LPS-166354 , LPS-166355 | master

### PR DESCRIPTION
**Pull request by Italo-gabriel**
JIRA Ticket 
[LPS-166351](https://issues.liferay.com/browse/LPS-166351) 
[LPS-166354](https://issues.liferay.com/browse/LPS-166354)
[LPS-166355](https://issues.liferay.com/browse/LPS-166355)

### CODE REVIEW

**Comment by Italo-gabriel** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Comment by Italo-gabriel** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:osb-site-initializer-evp

**Pull request closed without merging**
