### PR TITLE
LPS-188986 [CP 2.0] Activation key form refresh interactions

### PR DESCRIPTION
**Pull request by samuelleolopes**
[LPS-187936](https://liferay.atlassian.net/browse/LPS-187936)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
