### PR TITLE
LPS-172795  [PRM] - The Proceed button is activated even with mandatory space not filled 

### PR DESCRIPTION
**Pull request by Manda-vit**
Related issue: https://issues.liferay.com/browse/LPS-172795

### CODE REVIEW

**Comment by Manda-vit** [comment]
ci:test:sf
 ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:relevant

**Review by thaynam — CHANGES_REQUESTED** [review]
hey @Manda-vit, thanks you, it works! Can you please just remove this [line](https://github.com/liferay/liferay-portal/blob/7b11a1fa4186195fe52164a783d3f87bca7fa98b/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/DealRegistrationForm/steps/General/schema/yup.ts#L30)? It wasn't working correctly because of it.

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
