### PR TITLE
LPS-172691 [PRM] Button "View All Announcements" borders are overlapping

### PR DESCRIPTION
**Pull request by ericthmoritsuka**
Related issues:
https://issues.liferay.com/browse/LPS-172691
https://issues.liferay.com/browse/LPS-172684

### CODE REVIEW

**Comment by ericthmoritsuka** [comment]
ci:test:sf

**Comment by ericthmoritsuka** [comment]
ci:test:relevant

**Comment by ericthmoritsuka** [comment]
ci:test:relevant

**Comment by ericthmoritsuka** [comment]
ci:test:relevant

**Comment by ericthmoritsuka** [comment]
ci:test:sf

**Review by thaynam — APPROVED** [review]

**Pull request closed without merging**
