### PR TITLE
Test fix EVP LRQA-82215

### PR DESCRIPTION
**Pull request by MGabriellaS**
[LRQA-82215](https://liferay.atlassian.net/browse/LRQA-82215)

### CODE REVIEW

**Comment by MGabriellaS** [comment]
ci:test:sf

**Review by renato-araujo-liferay — APPROVED** [review]
Thank you for the this fix @MGabriellaS . LGFM

**Comment by renato-araujo-liferay** [comment]
ci:test:osb-site-initializer-evp

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by MGabriellaS** [comment]
ci:test:osb-site-initializer-evp

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by MGabriellaS** [comment]
ci:test:osb-site-initializer-evp

**Comment by renato-araujo-liferay** [comment]
CI failure happens only because of the collection display bug and is currently being analyzed.

**Comment by renato-araujo-liferay** [comment]
ci:forward

**Pull request closed without merging**
