### PR TITLE
LPS-163806 [ASK] add filter for subscribed tags

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:reevaluate:1307401_4991

**Comment by nNilton** [comment]
ci:reevaluate:1307401_4991

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by velosofelipe64** [comment]
ci:forward

**Pull request closed without merging**
