### PR TITLE
LPS-134900 Add Background and OriginalDocumentTag in UnavailablePreview Component

### PR DESCRIPTION
**Pull request by MateusCastro**

### CODE REVIEW

**Comment by MateusCastro** [comment]
ci:test:sf

**Comment by MateusCastro** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Review by joseabelenda — APPROVED** [review]

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
