### PR TITLE
Raylife AP Automated Tests - LPS-160728 | master 

### PR DESCRIPTION
**Pull request by itstali**
https://issues.liferay.com/browse/LPS-160728

### CODE REVIEW

**Comment by itstali** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
LGTM!

**Review by luanakarla — APPROVED** [review]
Hey @itstali, thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by luanakarla** [comment]
ci:forward

**Comment by itstali** [comment]
ci:foward

**Comment by itstali** [comment]
ci:forward

**Pull request closed without merging**
