### PR TITLE
LPS-189899 [CP 2.0] Fix Filters don't working with translation.

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-189899](https://liferay.atlassian.net/browse/LPS-189899)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Review by pedroliveirav — APPROVED** [review]

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Pull request closed without merging**
