### PR TITLE
LPS-179074 [EVP] Implementing the message and redirect after editing the organization

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-179074](https://issues.liferay.com/browse/LPS-179074)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:bundle

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:bundle

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @juliocezar96

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:forward

**Pull request closed without merging**
