### PR TITLE
LPS-192765 [Marketplace]  Page Electronic Procurement System

### PR DESCRIPTION
**Pull request by juliocezar96**
Subtask : [LPS-192765](https://liferay.atlassian.net/browse/LPS-192765)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
