### PR TITLE
LPS-149313 [Sitei Initializer] Create _addOrganizations in site initializer

### PR DESCRIPTION
**Pull request by joseabelenda**
.

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by nicolas-sss** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
