### PR TITLE
LPS-163132 [EVP] applying-diagram-changes

### PR DESCRIPTION
**Pull request by Andrefes565**
[LPS-162992](https://issues.liferay.com/browse/LPS-162992#view-subtasks)

### CODE REVIEW

**Review by silasbsi — APPROVED** [review]
LGTM :martial_arts_uniform: :+1: Thanks @Andrefes565

**Comment by silasbsi** [comment]
ci:forward

**Comment by Andrefes565** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
