### PR TITLE
LPS-191638 [CP 2.0] Inserting clear terminology on generate key final screen

### PR DESCRIPTION
**Pull request by EugenioAntunes**
[LPS-191647](https://liferay.atlassian.net/browse/LPS-191647)

[LPS-191638](https://liferay.atlassian.net/browse/LPS-191638)

### CODE REVIEW

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Review by pedroliveirav — APPROVED** [review]
Nice! 🚀

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
