### PR TITLE
LPS-191430  There is no pattern on error messages in MDF Claim form

### PR DESCRIPTION
**Pull request by caiosouza15**

### CODE REVIEW

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @caiosouza15

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
