### PR TITLE
LPS-146900 Subscribe to Question when add a reply

### PR DESCRIPTION
**Pull request by kevenleone**
# How it was developed?
   - I used Clay Tooltip markups for better accessibility. 

# What has been affected by the development?
   - A tooltip was added to subscribe button, because it's hard to understand if the gray button is subscribe or unsubscribe.
   - After adding a reply or comment the user is automatically subscribed to the Question.
   - Added a totalCount = 0, because when comments was being loaded we're displaying `undefined Answers` and now `0 Answers`

# Evidences

image

image

https://user-images.githubusercontent.com/22279592/166680346-e536854f-b1ad-4cca-be93-86ca816a4fee.mov

https://user-images.githubusercontent.com/22279592/166680358-d02fba07-02a9-47fc-8b6c-cee0754652ba.mov

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
Just starting reviewing :)

**Comment by samuelleolopes** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
Change 0 answers to `loading answers` for example

**Comment by samuelleolopes** [comment]
Just starting reviewing :)

**Comment by samuelleolopes** [comment]
Just starting reviewing :)

**Comment by samuelleolopes** [comment]
Just starting reviewing :)

**Pull request closed without merging**
