### PR TITLE
LPS-194142 [Marketplace] Implement the category and tag and Implement the list of APP solutions

### PR DESCRIPTION
**Pull request by juliocezar96**
Subtasks: [LPS-194141](https://liferay.atlassian.net/browse/LPS-194141) [LPS-194142](https://liferay.atlassian.net/browse/LPS-194142)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Review by claricebrasil — APPROVED** [review]
Good job!

**Review by joanagrego — APPROVED** [review]
Approved! Thanks @juliocezar96 :white_check_mark:

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:forward

**Comment by juliocezar96** [comment]
ci:forward:force

**Pull request closed without merging**
