### PR TITLE
LPS-160460 TR2 Automated Test | master

### PR DESCRIPTION
**Pull request by joelrocha68**
[LPS-175597](https://issues.liferay.com/browse/LPS-175597)

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by nikki-pru** [comment]
LGTM! great job!

**Comment by joelrocha68** [comment]
ci:forward

**Pull request closed without merging**
