### PR TITLE
LPS-196772 [MARKETPLACE] App Details Page Layout Adjustments

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
Good job @joanagrego Thanks. :martial_arts_uniform:

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by joanagrego** [comment]
ci:forward:force

**Comment by itstali** [comment]
hey @joanagrego the errors showed here has nothing to do with your PR, be free to push forward :100:

**Comment by joanagrego** [comment]
Resent --> [PR](https://github.com/brianchandotcom/liferay-portal/pull/141186)

**Pull request closed without merging**
