### PR TITLE
LPS-144568 Add RaylifeSummarySection path and test

### PR DESCRIPTION
**Pull request by thaiscabrals**
- LPS-144568 Add RaylifeSummarySection path and test
- LPS-144568 SF

### CODE REVIEW

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by thaiscabrals** [comment]
ci:forward

**Pull request closed without merging**
