### PR TITLE
LPS-164525, LPS-164529 [ASK] Add Comment Button UI enhancement

### PR DESCRIPTION
**Pull request by velosofelipe64**

### CODE REVIEW

**Review by joseabelenda — APPROVED** [review]
LGTM!

**Comment by joseabelenda** [comment]
ci:forward

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Comment by velosofelipe64** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by brenobcos** [comment]
Just starting reviewing :)

**Pull request closed without merging**
