### PR TITLE
[Site Initializer] LPS-160961 Implement Segments Experience

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:reevaluate:1327401_5985

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:reevaluate:1327401_5993

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/2299

**Pull request closed without merging**
