### PR TITLE
LPS-162897 Activity Improvements - Latest Activity Page

### PR DESCRIPTION
**Pull request by gleicelisbino**

### CODE REVIEW

**Comment by gleicelisbino** [comment]
ci:test:sf

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/3133

**Pull request closed without merging**
