### PR TITLE
MP2 Automation Test: LPS-184714, LPS-184715 and LPS-185107 | master

### PR DESCRIPTION
**Pull request by luanakarla**
Ticket:
[LPS-184212](https://issues.liferay.com/browse/LPS-184212)

Tests:
Marketplace#ChannelsAreCreatedForMP20
Marketplace#CatalogsAreCreatedForMP20
Marketplace#AccountUsersAreCreatedForMP20

### CODE REVIEW

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:site-initializer-liferay-marketplace

**Comment by joelrocha68** [comment]
LGTM!

**Comment by luanakarla** [comment]
ci:forward

**Comment by luanakarla** [comment]
ci:stop

**Comment by luanakarla** [comment]
ci:close

**Comment by luanakarla** [comment]
ci:reopen

**Comment by luanakarla** [comment]
ci:forward

**Comment by luanakarla** [comment]
ci:stop

**Pull request closed without merging**
