### PR TITLE
LPS-159346 [Raylife AP] get data from api to fill out applications number

### PR DESCRIPTION
**Pull request by aecioprado**
related with -> [LPS-159346](https://github.com/pt-liferay-solutions/liferay-portal/pull/1788)

### CODE REVIEW

**Comment by aecioprado** [comment]
ci:test:sf

**Comment by aecioprado** [comment]
ci:test:sf

**Comment by aecioprado** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :1st_place_medal: Thanks @aecioprado

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @aecioprado

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
