### PR TITLE
LPS-160726 TR2 Automated Test | master

### PR DESCRIPTION
**Pull request by joelrocha68**
[LPS-160576](https://issues.liferay.com/browse/LPS-160576)
[LPS-174555](https://issues.liferay.com/browse/LPS-174555)

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray

**Comment by nikki-pru** [comment]
Reviewing!

**Comment by nikki-pru** [comment]
ci:test:site-initializer-testray

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by nikki-pru** [comment]
ci:test:site-initializer-testray:compile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
