### PR TITLE
LPS-190272 [Marketplace] Field cannot be added after object is created

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-190272](https://liferay.atlassian.net/browse/LPS-190272)

### CODE REVIEW

**Comment by juliocezar96** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-190272 [Impedibug] Custom field cannot be added after object is created</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-190272">[Impedibug] Custom field cannot be added after object is created</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Impedibug</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Medium</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Support QA</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Luana Silva</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

2 files changed, 20 insertions(+), 13 deletions(-)

**Comment by juliocezar96** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
Good job @juliocezar96 :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Comment by welitonpe** [comment]
ci:forward:force

**Pull request closed without merging**
