### PR TITLE
LPS-145160 [CP 2.0] Change menu approach to redirect page

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
