### PR TITLE
LPS-148345 [CP 2.0] Customer can edit notification for activation key expiration

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-148345](https://issues.liferay.com/browse/LPS-148345)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/4066

**Pull request closed without merging**
