### PR TITLE
Raylife AP Automation Test: LPS-161514| master

### PR DESCRIPTION
**Pull request by luanakarla**
Tickets:
[LPS-160728](https://issues.liferay.com/browse/LPS-160728)
[LPS-161514](https://issues.liferay.com/browse/LPS-161514)
[LPS-167067](https://issues.liferay.com/browse/LPS-167067)

Tests:
RaylifeAPContactInfo#IfDatePickerWorks
RaylifeAPContactInfo#NextButtonWorksWhenFieldsAreFilled
RaylifeAPCoverages#IfNextButtonIsEnableWhenFieldsFilled
RaylifeAPApplicationFilterSearch#CanViewTheSearchResults
RaylifeAPApplicationFilterSearch#CanViewTheFilterEnableAndDisable

### CODE REVIEW

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:site-initializer-raylife-ap:nocompile

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
