### PR TITLE
LPS-166582 [Raylife D2C/AP] Add Raylife Users through Site Initializer

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-162770](https://issues.liferay.com/browse/LPS-162770)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @joanagrego

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
