### PR TITLE
LPS-144060 Fix Commerce Notification Center

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
@joseabelenda, this is the fix for commerce notification

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
