### PR TITLE
LPS-162115 [EVP] Create DATA ON EVP Section for Homepage

### PR DESCRIPTION
**Pull request by juliocezarjc**
[LPS-162115](https://issues.liferay.com/browse/LPS-162115)

### CODE REVIEW

**Comment by juliocezarjc** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :martial_arts_uniform:

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @juliocezarjc

**Comment by JoMaAlves** [comment]
Just starting reviewing :)

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Comment by juliocezarjc** [comment]
ci:test:sf

**Comment by juliocezarjc** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
Just starting reviewing :)

**Comment by juliocezarjc** [comment]
ci:test:relevant

**Comment by juliocezarjc** [comment]
ci:test:relevant

**Comment by juliocezarjc** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
