### PR TITLE
Testray 2 Automated Test - LPS-156977 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/LPS-156982
https://issues.liferay.com/browse/LPS-156988
https://issues.liferay.com/browse/LPS-156994
https://issues.liferay.com/browse/LPS-156997
https://issues.liferay.com/browse/LPS-156998
https://issues.liferay.com/browse/LPS-162504
https://issues.liferay.com/browse/LPS-162505

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by barrosdennys** [comment]
ci:forward

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:forward

**Comment by AfonsoHSantos** [comment]
ci:forward

**Pull request closed without merging**
