### PR TITLE
LPS-180700 Inserting Correct Icon to Testray Site-Initializer

### PR DESCRIPTION
**Pull request by EugenioAntunes**
[LPS-180700](https://issues.liferay.com/browse/LPS-180700)

### CODE REVIEW

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Review by rafaelfs98 — APPROVED** [review]
LGTM :fire:

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Review by welitonpe — APPROVED** [review]
Nice.

**Review by Elvinho — APPROVED** [review]
LGTM 🔥

**Review by kevenleone — APPROVED** [review]
Greaaaattt

🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by EugenioAntunes** [comment]
ci:test:relevant

**Comment by EugenioAntunes** [comment]
ci:forward

**Pull request closed without merging**
