### PR TITLE
LPS-142859 and LPS-142941 Added side-menu handler to change page

### PR DESCRIPTION
**Pull request by iagochaves**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:forward

**Comment by iagochaves** [comment]
ci:forward

**Comment by iagochaves** [comment]
Just starting reviewing :)

**Comment by Lucas2691** [comment]
Just starting reviewing :)

**Comment by joaosvassis** [comment]
Just starting reviewing :)

**Comment by aildsonf** [comment]
Just starting reviewing :)

**Comment by aildsonf** [comment]
Just starting reviewing :)

**Pull request closed without merging**
