### PR TITLE
LPS-188456 [PRM] Change the file URL for download

### PR DESCRIPTION
**Pull request by ytuik**
https://liferay.atlassian.net/browse/LPS-188456

### CODE REVIEW

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @ytuik

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:forward

**Pull request closed without merging**
