### PR TITLE
LPS-152664 SF

### PR DESCRIPTION
**Pull request by kevenleone**
PR Including:

https://github.com/pt-liferay-solutions/liferay-portal/pull/1331

https://github.com/pt-liferay-solutions/liferay-portal/pull/1309

----------

### Jira Issues

https://issues.liferay.com/browse/LPS-152659
https://issues.liferay.com/browse/LPS-152658
https://issues.liferay.com/browse/LPS-152657
https://issues.liferay.com/browse/LPS-152656
https://issues.liferay.com/browse/LPS-152655
https://issues.liferay.com/browse/LPS-152664

----------

# Features / Improvements

* The user can edit the comment
* The user can understand the structure of threads and questions
* And helping the user with shortcuts

# How it was developed?
   - I used Clay Tooltip markups for better accessibility. 

# What has been affected by the development?
   - A tooltip was added to subscribe button, because it's hard to understand if the gray button is subscribe or unsubscribe.
   - After adding a reply or comment the user is automatically subscribed to the Question.
   - Added a totalCount = 0, because when comments was being loaded we're displaying `undefined Answers` and now `0 Answers`

# Evidences

image

image

https://user-images.githubusercontent.com/22279592/166680346-e536854f-b1ad-4cca-be93-86ca816a4fee.mov

https://user-images.githubusercontent.com/22279592/166680358-d02fba07-02a9-47fc-8b6c-cee0754652ba.mov

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:questions

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:questions

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by Lucas2691** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:stop

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:reevaluate:1307401_3324

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
