### PR TITLE
LPS-172083 Create Payment Confirmation and kebab fragment button

### PR DESCRIPTION
**Pull request by EuniceTravassos**

### CODE REVIEW

**Comment by EuniceTravassos** [comment]
ci:test:sf

**Comment by EuniceTravassos** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @EuniceTravassos

**Comment by eliasantosf** [comment]
ci:forward

**Comment by juliocezar96** [comment]
Just starting reviewing :)

**Pull request closed without merging**
