### PR TITLE
LPS-168339 bug fix answers on thread does not load

### PR DESCRIPTION
**Pull request by caiosouza15**

### CODE REVIEW

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by Lucas2691** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:reevaluate:1397401_1643

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
