### PR TITLE
LPS-163806 [ASK] add filter for subscribed tags

### PR DESCRIPTION
**Pull request by velosofelipe64**

### CODE REVIEW

**Comment by velosofelipe64** [comment]
ci:test:sf

**Comment by velosofelipe64** [comment]
ci:test:sf

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Comment by brenobcos** [comment]
Just starting reviewing :)

**Comment by velosofelipe64** [comment]
ci:test:sf

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Comment by velosofelipe64** [comment]
ci:forward

**Pull request closed without merging**
