### PR TITLE
LPS-191557 [Marketplace] Add Dashboard Permissions section

### PR DESCRIPTION
**Pull request by ytuik**
https://liferay.atlassian.net/browse/LPS-191557

### CODE REVIEW

**Comment by ytuik** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]

**Review by claricebrasil — APPROVED** [review]
Great job, Bruno!

**Comment by claricebrasil** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:stop

**Comment by claricebrasil** [comment]
resent: #4549

**Pull request closed without merging**
