### PR TITLE
Lps 157950

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by wandersonvicente** [comment]
Just starting reviewing :)

**Comment by claricebrasil** [comment]
resent https://github.com/pt-liferay-solutions/liferay-portal/pull/1790

**Comment by claricebrasil** [comment]
Associated with https://github.com/pt-liferay-solutions/liferay-portal/pull/1802

**Pull request closed without merging**
