### PR TITLE
LPS-195392 [Marketplace] Add Missing Custom Fields 

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by LuanaKSilva** [comment]
Hey @joanagrego, I analyzed the relevant flaws. None of them are because of your PR. Putting it forward.

**Comment by LuanaKSilva** [comment]
ci:forward:force

**Pull request closed without merging**
