### PR TITLE
LPS-159028 [PRM] Add form and listing for Activities

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Comment by DiogoNo** [comment]
Just starting reviewing :)

**Comment by joaosvassis** [comment]
Just starting reviewing :)

**Comment by joaosvassis** [comment]
Just starting reviewing :)

**Comment by DiogoNo** [comment]
Just starting reviewing :)

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
