### PR TITLE
[Raylife] LPS-149622 Continue Quote Button Fixed

### PR DESCRIPTION
**Pull request by Mylena-Rodrigues**

### CODE REVIEW

**Comment by Mylena-Rodrigues** [comment]
ci:test:sf

**Review by silasbsi — COMMENTED** [review]
LGTM :fire: :+1:

**Comment by silasbsi** [comment]
@kevenleone could you make another review?

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
