### PR TITLE
LPS-167546 [EVP] Create Organization Button Fix

### PR DESCRIPTION
**Pull request by Claudionilton**

### CODE REVIEW

**Comment by Claudionilton** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @Claudionilton

**Comment by silasbsi** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
Just starting reviewing :)

**Comment by EuniceTravassos** [comment]
Just starting reviewing :)

**Comment by EuniceTravassos** [comment]
Just starting reviewing :)

**Review by EuniceTravassos — APPROVED** [review]

**Comment by silasbsi** [comment]
ci:forward

**Comment by Lucas2691** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:forward

**Pull request closed without merging**
