### PR TITLE
LPS-186326 - The success message does not appear when delete a category

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-186326](https://issues.liferay.com/browse/LPS-186326)

### CODE REVIEW

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward:force

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
