### PR TITLE
LPS-163805 / LPS-163838 [ASK] Sort by viewCount and totalScore

### PR DESCRIPTION
**Pull request by velosofelipe64**

### CODE REVIEW

**Comment by velosofelipe64** [comment]
ci:test:sf

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

@nNilton , @gleicelisbino could you guys dbCheck?

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Comment by velosofelipe64** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Pull request closed without merging**
