### PR TITLE
LPS-178400 Create component name and translate

### PR DESCRIPTION
**Pull request by alvarolealdl**

### CODE REVIEW

**Comment by alvarolealdl** [comment]
ci:test:sf

**Review by rafaelfs98 — APPROVED** [review]
LGTM :fire:

**Review by rafaelfs98 — APPROVED** [review]
LGTM :fire:

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Review by Elvinho — APPROVED** [review]

**Review by kevenleone — APPROVED** [review]
Thanks guys, LGTM 🔥

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/131735

**Pull request closed without merging**
