### PR TITLE
LPS-183092 [EVP] Employee Can't view all organization

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-183092](https://issues.liferay.com/browse/LPS-183092)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:bundle

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
