### PR TITLE
LPS-194371 [Marketplace] Create Footer for Marketplace Masterpage

### PR DESCRIPTION
**Pull request by claricebrasil**

### CODE REVIEW

**Review by joanagrego — APPROVED** [review]
Good job! :white_check_mark:

**Comment by claricebrasil** [comment]
ci:test:sf

**Review by juliocezar96 — APPROVED** [review]
Nice job! 🤙

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:forward

**Pull request closed without merging**
