### PR TITLE
LPS-165830 - [Raylife AP] Creating additional fields when is auto quote

### PR DESCRIPTION
**Pull request by pedroliveirav**
[Task: LPS-165830](https://issues.liferay.com/browse/LPS-165830)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:forward

**Comment by pedroliveirav** [comment]
ci:forward

**Pull request closed without merging**
