### PR TITLE
LPS-161612 Update add or update Commerce Channel

### PR DESCRIPTION
**Pull request by gleicelisbino**

### CODE REVIEW

**Comment by gleicelisbino** [comment]
ci:test:sf

**Comment by gleicelisbino** [comment]
Resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/2034

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
