### PR TITLE
LPS-144915 [CP 2.0] Add Properties for Poshi Tests

### PR DESCRIPTION
**Pull request by Paulovcaselli**

### CODE REVIEW

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
Just starting reviewing :)

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
Just starting reviewing :)

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
Just starting reviewing :)

**Comment by luanakarla** [comment]
Just starting reviewing :)

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Comment by luanakarla** [comment]
Just starting reviewing :)

**Comment by thaiscabrals** [comment]
Just starting reviewing :)

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
Just starting reviewing :)

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Comment by luanakarla** [comment]
Just starting reviewing :)

**Comment by thaiscabrals** [comment]
Just starting reviewing :)

**Comment by Paulovcaselli** [comment]
Just starting reviewing :)

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by Paulovcaselli** [comment]
ci:forward

**Comment by Paulovcaselli** [comment]
ci:test:relevant

**Comment by Paulovcaselli** [comment]
ci:close

**Pull request closed without merging**
