### PR TITLE
LPS-158246 [CP 2.0] Display LXC form on first admin onboarding

### PR DESCRIPTION
**Pull request by luisacmn**

### CODE REVIEW

**Comment by luisacmn** [comment]
ci:test:sf

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
congrats for you first PR @luisacmn !

**Comment by jairmedeiros** [comment]
ci:forward

**Review by wandersonvicente — APPROVED** [review]

**Comment by wandersonvicente** [comment]
ci:test:sf

**Comment by luisacmn** [comment]
ci:test:sf

**Review by claricebrasil — APPROVED** [review]

**Comment by claricebrasil** [comment]
ci:forward

**Pull request closed without merging**
