### PR TITLE
LPS-144576 Add RaylifePaymentMethod macro, paths and tests

### PR DESCRIPTION
**Pull request by thaiscabrals**
- LPS-144576 Add RaylifePaymentMethod macro, paths and tests
- LPS-144576 SF

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by Paulovcaselli** [comment]
ci:forward

**Pull request closed without merging**
