### PR TITLE
LPS-173392 [CP 2.0] Partner Manager showing as Support Seat role

### PR DESCRIPTION
**Pull request by kiwm**
Related issue: https://issues.liferay.com/browse/LPS-173392

### CODE REVIEW

**Comment by kiwm** [comment]
ci:test:sf

**Comment by kiwm** [comment]
ci:test:relevant

**Review by jairmedeiros — APPROVED** [review]
LGTM!

Pay attention that your commit is without LPS!

**Comment by kiwm** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by kiwm** [comment]
ci:test:relevant

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @kiwm

**Comment by JoMaAlves** [comment]
ci:forward

**Pull request closed without merging**
