### PR TITLE
Scope CSS to avoid inject CSS global

### PR DESCRIPTION
**Pull request by kevenleone**
@silasbsi , @welitonpe , e time do Raylife

### CODE REVIEW

**Comment by kevenleone** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

691 files changed, 45028 insertions(+), 12558 deletions(-)

This PR is too huge for one to review :broken_heart: 

Batman

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by eduardobbgf** [comment]
Just starting reviewing :)

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Pull request closed without merging**
