### PR TITLE
LPS-144867 [CP 2.0] Refinement React fragment implementation

### PR DESCRIPTION
**Pull request by iagochaves**

### CODE REVIEW

**Comment by igordmf** [comment]
Just starting reviewing :)

**Comment by igordmf** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by jairmedeiros** [comment]
Just starting reviewing :)

**Pull request closed without merging**
