### PR TITLE
LPS-177321 [EVP] Refactoring throughout the EVP project to standardize folders and files

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-177321](https://issues.liferay.com/browse/LPS-177321)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by juliocezar96** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Pull request closed without merging**
