### PR TITLE
LPS-144589 Add RaylifePolicyDeclaration paths and tests

### PR DESCRIPTION
**Pull request by thaiscabrals**
- LPS-144589 Add RaylifePolicyDeclaration paths and tests
- LPS-144589 SF

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by pyoo47** [comment]
ci:stop

Stopping and restarting due to ci-infrastructure bug

**Comment by pyoo47** [comment]
ci:test:site-intializer-raylife

**Comment by pyoo47** [comment]
ci:test:site-initializer-raylife

**Comment by Paulovcaselli** [comment]
ci:stop

**Comment by Paulovcaselli** [comment]
ci:forward

**Pull request closed without merging**
