### PR TITLE
LPS-188497 Allow replace in ddm-templates.json

### PR DESCRIPTION
**Pull request by joseabelenda**
.

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:reevaluate:1407401_3709

**Comment by nNilton** [comment]
Hey @joseabelenda , could you please resent this directly? Mu'men really need this, and I forget to do it

**Pull request closed without merging**
