### PR TITLE
LPS-186238 | Disaster Recovery data center region drop-down is not displayed when DR subscription is active

### PR DESCRIPTION
**Pull request by gabrielargomes**
[LPS-183514](https://issues.liferay.com/browse/LPS-183514)

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:forward

**Comment by eduardo-diniz** [comment]
ci:forward

**Comment by gabrielargomes** [comment]
ci:forward

**Comment by samuelleolopes** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
