### PR TITLE
LPS-183277 [TR2] Automation Test | master

### PR DESCRIPTION
**Pull request by joelrocha68**
Suite Permissions
https://issues.liferay.com/browse/LPS-183168

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Review by luanakarla — CHANGES_REQUESTED** [review]
Hey @joelrocha68 , thanks for working on it!

Could you make the same changes requested [here](https://github.com/pt-liferay-solutions/liferay-portal/pull/3956)? Thanks in advance.

**Review by luanakarla — APPROVED** [review]

**Comment by luanakarla** [comment]
LGTM!

**Comment by joelrocha68** [comment]
ci:forward

**Comment by joelrocha68** [comment]
ci:forward

**Comment by joelrocha68** [comment]
ci:forward

**Pull request closed without merging**
