### PR TITLE
[Site Initializer]  LPS-159608 Update addKnowledgeBaseFolder

### PR DESCRIPTION
**Pull request by Andrefes565**

### CODE REVIEW

**Comment by Andrefes565** [comment]
ci:teste:sf

**Comment by Andrefes565** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
ci:test:sf

**Review by nNilton — CHANGES_REQUESTED** [review]

**Comment by nNilton** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
ci:test:sf

**Comment by nNilton** [comment]
@joseabelenda

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/1976

**Pull request closed without merging**
