### PR TITLE
LPS-189094 [EVP] Fix possibility of staff user ask for more info or reject a request

### PR DESCRIPTION
**Pull request by Mylena-Rodrigues**
Ticket: [LPS-189094](https://liferay.atlassian.net/browse/LPS-189094)

### CODE REVIEW

**Comment by Mylena-Rodrigues** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @Mylena-Rodrigues

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by Mylena-Rodrigues** [comment]
ci:test:relevant

**Comment by Mylena-Rodrigues** [comment]
Link: [brianchandotcom#137212](https://github.com/brianchandotcom/liferay-portal/pull/137212)

**Pull request closed without merging**
