### PR TITLE
LPS-182046 Giving Proper Roles Permissions For Case Types

### PR DESCRIPTION
**Pull request by EugenioAntunes**
[LPS-182046](https://issues.liferay.com/browse/LPS-178264)

### CODE REVIEW

**Review by Elvinho — APPROVED** [review]
LGTM 🔥

**Review by rafaelfs98 — APPROVED** [review]
Good job @EugenioAntunes

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
