### PR TITLE
LPS-150639 [CP 2.0] Search team members by name and email 

### PR DESCRIPTION
**Pull request by claricebrasil**
Fix if number of available seats is below 0 than should show 0 of max requestors available.

### CODE REVIEW

**Review by igordmf — APPROVED** [review]

**Review by joaosvassis — APPROVED** [review]
Nice

**Review by Lucas2691 — APPROVED** [review]

**Review by joanagrego — APPROVED** [review]
Perfect

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
