### PR TITLE
CP 2.0 - Test Fix - LRQA-77266 | master

### PR DESCRIPTION
**Pull request by MathausC**
https://issues.liferay.com/browse/LRQA-77266

### CODE REVIEW

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:stable

**Comment by MathausC** [comment]
ci:test:relevant

**Comment by MathausC** [comment]
@barrosdennys Needs review.

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:relevant

**Comment by barrosdennys** [comment]
ci:forward

**Pull request closed without merging**
