### PR TITLE
LPS-144192 Remove Save & Exit in Product Quote

### PR DESCRIPTION
**Pull request by silasbsi**

### CODE REVIEW

**Comment by rosig** [comment]
Just starting reviewing :)

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Comment by ilzamcmed** [comment]
Just starting reviewing :)

**Comment by thaiscabrals** [comment]
Just starting reviewing :)

**Comment by samuelleolopes** [comment]
Just starting reviewing :)

**Comment by luanakarla** [comment]
Just starting reviewing :)

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Comment by eduardobbgf** [comment]
Just starting reviewing :)

**Comment by JoMaAlves** [comment]
Just starting reviewing :)

**Pull request closed without merging**
