### PR TITLE
LPS-161284 [COMPONENTS] Implement replace in LayoutContent

### PR DESCRIPTION
**Pull request by TamyrisTorres**

### CODE REVIEW

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
