### PR TITLE
LPS-166126 [Testray] DispatchTrigger to create tasks and subtasks

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:forward

**Comment by nNilton** [comment]
ci:reevaluate:1387401_4973

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
