### PR TITLE
LPS-143120 [Site Initializer] setExternalReferenceCode and use just one RemoteAppEntry

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:stable

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
Just starting reviewing :)

**Comment by samuelleolopes** [comment]
Just starting reviewing :)

**Comment by luanakarla** [comment]
Just starting reviewing :)

**Comment by iagochaves** [comment]
Just starting reviewing :)

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:reevaluate:1327401_1797

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Pull request closed without merging**
