### PR TITLE
LPS-145280 [Click to Chat] add show in control panel configuration

### PR DESCRIPTION
**Pull request by gleicelisbino**

### CODE REVIEW

**Comment by gleicelisbino** [comment]
ci:test:sf

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Review by joseabelenda — APPROVED** [review]

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Pull request closed without merging**
