### PR TITLE
LPS-160292 [PRM] Creation of Deal, MDF, Revenue, Level and Renewal Dashboards

### PR DESCRIPTION
**Pull request by thaynam**
https://issues.liferay.com/browse/LPS-156226
https://issues.liferay.com/browse/LPS-156229
https://issues.liferay.com/browse/LPS-156238
https://issues.liferay.com/browse/LPS-156225
https://issues.liferay.com/browse/LPS-156547

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
