### PR TITLE
LPS-186204 Add possibility to associate Accounts with Organizations

### PR DESCRIPTION
**Pull request by joaodamasceno2001**

### CODE REVIEW

**Comment by joaodamasceno2001** [comment]
ci:test:sf

**Comment by joaodamasceno2001** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci is a bit bugged
please, resent @joaodamasceno2001

**Comment by joaodamasceno2001** [comment]
@nNilton I created this PR 45 minutes ago

**Pull request closed without merging**
