### PR TITLE
TR2 Test Fix | LPS-174569 | master

### PR DESCRIPTION
**Pull request by luanakarla**
Ticket:
https://issues.liferay.com/browse/LPS-174569

### CODE REVIEW

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:site-initializer-testray

**Comment by nikki-pru** [comment]
[Tests are passing here](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2242410985&testrayRunId=2242412882) and there are no new failures caused by these changes.

Só AdminCanViewRequiredField esta falhando.

@luanakarla I will forward, but please check on the test above. Thank you

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
