### PR TITLE
COMMERCE-9372 Use DynamicImport-Package instead of optional Import-Package. It prevents startup order issues when the site initializer extender bundle resolves before the commerce ones that provide the optional imports. See https://docs.osgi.org/specification/osgi.core/7.0.0/framework.module.html#i2548181

### PR DESCRIPTION
**Pull request by rafaprax**
Issue: https://issues.liferay.com/browse/COMMERCE-9372

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:site-initializer-raylife-d2c

**Comment by rafaprax** [comment]
ci:test:site-initializer-raylife-d2c

**Comment by kyle-miho** [comment]
failures seem unrelated @rafaprax if we are waiting for results for the site initializer tests, i can check those tomorrow

**Comment by rafaprax** [comment]
Thx @kyle-miho. Let's wait for the site initializer results.

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by kyle-miho** [comment]
@rafaprax the Site Initializer Test suite seems to be broken as of now, I wouldn't worry about its results for now

**Comment by rafaprax** [comment]
Ok then. Thx @kyle-miho

**Comment by kyle-miho** [comment]
The startup suite seems to pass on other ci results, ill run it again to be safe

**Comment by kyle-miho** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @kyle-miho if everything is ok with the startup suite, feel free to forward this pr. Thx

**Comment by rafaprax** [comment]
Conflicts solved.

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
I will manually forward this

**Comment by kyle-miho** [comment]
ci:close

**Comment by rafaprax** [comment]
Thx @kyle-miho

**Pull request closed without merging**
