### PR TITLE
LPS-176554 Create Apply Filter button action

### PR DESCRIPTION
**Pull request by rafaelfs98**
[LPS-173528 - Components filter 1st level](https://issues.liferay.com/browse/LPS-173528)

### CODE REVIEW

**Review by Elvinho — APPROVED** [review]
LGTM 🥇

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Review by welitonpe — APPROVED** [review]
LGTM:fire:

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
