### PR TITLE
LPS-163132 [EVP] Create EVP Process Section

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :+1: Thanks @JoMaAlves

**Comment by silasbsi** [comment]
ci:forward

**Comment by juliocezarjc** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:forward

**Pull request closed without merging**
