### PR TITLE
LPS-161284 [COMPONENTS] Implement replace in LayoutContent

### PR DESCRIPTION
**Pull request by TamyrisTorres**

### CODE REVIEW

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:forward

**Comment by TamyrisTorres** [comment]
ci:stop

**Comment by TamyrisTorres** [comment]
ci:stop

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/1989

**Pull request closed without merging**
