### PR TITLE
LPS-161349 Fixed behavior of checkbox check all / uncheck all,  to correctly behavior

### PR DESCRIPTION
**Pull request by welitonpe**

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by welitonpe** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
Pull Request forwarded: https://github.com/brianchandotcom/liferay-portal/pull/122169

**Comment by kevenleone** [comment]
ci:close

**Pull request closed without merging**
