### PR TITLE
LPS-193992 [CP 2.0] Added Mumbai to the AC form region list

### PR DESCRIPTION
**Pull request by samuelleolopes**
[LPS-193874](https://liferay.atlassian.net/browse/LPS-193874)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Review by EugenioAntunes — APPROVED** [review]
Nice job, @samuelleolopes  ⚡

**Review by pedroliveirav — APPROVED** [review]

**Review by Aline160 — APPROVED** [review]
Great!!

**Review by kylembischof — APPROVED** [review]
Looks good!

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Pull request closed without merging**
