### PR TITLE
LPS-140158 Project Breadcrumb

### PR DESCRIPTION
**Pull request by claricebrasil**

### CODE REVIEW

**Comment by claricebrasil** [comment]
@kevenleone @jairmedeiros

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
We sent a PR to Peter Shin, to get some help with Gradle, to back again with this conversation

**Comment by jairmedeiros** [comment]
ci:close

**Comment by jairmedeiros** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/612

**Pull request closed without merging**
