### PR TITLE
LPS-172235 [Raylife D2C/AP] Create Raylife Data Objects - Quotes 

### PR DESCRIPTION
**Pull request by EugenioAntunes**
[LPS-172253](https://issues.liferay.com/browse/LPS-172235)

### CODE REVIEW

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Approved! Thank you @EugenioAntunes :white_check_mark:

**Comment by joanagrego** [comment]
ci:test:bundle

**Review by claricebrasil — APPROVED** [review]

**Comment by claricebrasil** [comment]
ci:forward

**Pull request closed without merging**
