### PR TITLE
LPS-167118 [Site Initializer] _updateObjectDefinitionAccountEntryRestricted

### PR DESCRIPTION
**Pull request by TamyrisTorres**

### CODE REVIEW

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:forward

**Comment by nNilton** [comment]
ci:forward

**Comment by nNilton** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:forward

**Comment by nNilton** [comment]
@thaiscabrals can you see this failures please?

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:reevaluate:1387401_6681

**Comment by nNilton** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/3410

**Pull request closed without merging**
