### PR TITLE
LPS-196347 [CP 2.0] Display quantities on the card does not work for some types of products

### PR DESCRIPTION
**Pull request by eduardo-diniz**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Comment by eduardo-diniz** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/141007

**Pull request closed without merging**
