### PR TITLE
LPS-143481 Add tests, macros and paths for RaylifeRetrieveQuote archive

### PR DESCRIPTION
**Pull request by luanakarla**

### CODE REVIEW

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by Paulovcaselli** [comment]
ci:stop

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by Paulovcaselli** [comment]
ci:stop

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:stop

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:close

**Pull request closed without merging**
