### PR TITLE
LPS-189097 [EVP] Fix service request creation

### PR DESCRIPTION
**Pull request by Mylena-Rodrigues**
Ticket: [LPS-189097](https://liferay.atlassian.net/browse/LPS-189097)

### CODE REVIEW

**Comment by Mylena-Rodrigues** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @Mylena-Rodrigues

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by Mylena-Rodrigues** [comment]
ci:test:relevant

**Comment by Mylena-Rodrigues** [comment]
ci:test:relevant

**Comment by Mylena-Rodrigues** [comment]
Link: [brianchandotcom#137210](https://github.com/brianchandotcom/liferay-portal/pull/137210)

**Pull request closed without merging**
