### PR TITLE
LPS-167887 [CP 2.0] fix the translation key 

### PR DESCRIPTION
**Pull request by caiosouza15**

### CODE REVIEW

**Comment by caiosouza15** [comment]
ci:test:sf

**Review by jairmedeiros — APPROVED** [review]

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @caiosouza15

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by caiosouza15** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by caiosouza15** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:forward

**Pull request closed without merging**
