### PR TITLE
LPS-148193 Add RaylifePropertyInfoMobile tests

### PR DESCRIPTION
**Pull request by thaiscabrals**
- LPS-148193 Add RaylifePropertyInfoMobile tests
- LPS-148193 SF

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by Paulovcaselli** [comment]
ci:forward

**Pull request closed without merging**
