### PR TITLE
LPS-160588 [PRM] Field Validations

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by DiogoNo** [comment]
Just starting reviewing :)

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by joaosvassis** [comment]
Just starting reviewing :)

**Comment by ytuik** [comment]
Just starting reviewing :)

**Comment by jackelyneaquino** [comment]
jackelyneaquino

**Comment by EuniceTravassos** [comment]
Just starting reviewing :)

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
