### PR TITLE
LPS-174788 - [Raylife Ap] Fix below the Active Claim and Date Order

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-174788 ](https://issues.liferay.com/browse/LPS-174788)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Good job! Thank you @eduardo-diniz :white_check_mark:

**Review by claricebrasil — APPROVED** [review]

**Comment by claricebrasil** [comment]
ci:forward

**Pull request closed without merging**
