### PR TITLE
LPS-178934 [Questions] Fix questions not showing as pending with new homepage

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@joseabelenda I'm merging this manually.

**Comment by brianchandotcom** [comment]
@joseabelenda I made a lot of tiny changes in my origin. Please review. Thx!

**Pull request closed without merging**
