### PR TITLE
LPS-175567 Status filters not working

### PR DESCRIPTION
**Pull request by rafaelfs98**
[LPS-175567](https://issues.liferay.com/browse/LPS-175567)

### CODE REVIEW

**Review by welitonpe — APPROVED** [review]
Good Job :fire:  :fire:

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
