### PR TITLE
Testray 2 Automated Test  - LPS-160544 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/LPS-160543
https://issues.liferay.com/browse/LPS-160545
https://issues.liferay.com/browse/LPS-160546

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by barrosdennys** [comment]
ci:forward

**Pull request closed without merging**
