### PR TITLE
LPS-186904 [PRM] Move object fields from object definitions in Site

### PR DESCRIPTION
**Pull request by luisacmn**

### CODE REVIEW

**Comment by luisacmn** [comment]
ci:test:solutions-acceptance

**Comment by thaynam** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:solutions-acceptance

**Comment by luisacmn** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:stop:solutions-acceptance

**Comment by AfonsoHSantos** [comment]
ci:test:solutions-acceptance

**Pull request closed without merging**
