### PR TITLE
LPS-173370 Fixing Ci Routine Raylife D2C

### PR DESCRIPTION
**Pull request by styller1**
Ticket:
[LPS-173370](https://issues.liferay.com/browse/LPS-173370)

Is related to:
[LPS-174829](https://issues.liferay.com/browse/LPS-174829)

Sub-tasks:
[LPS-173400](https://issues.liferay.com/browse/LPS-173400)
[LPS-173401](https://issues.liferay.com/browse/LPS-173401)
[LPS-173402](https://issues.liferay.com/browse/LPS-173402)
[LPS-173381](https://issues.liferay.com/browse/LPS-173381)
[LPS-173388](https://issues.liferay.com/browse/LPS-173388)
[LPS-173391](https://issues.liferay.com/browse/LPS-173391)

### CODE REVIEW

**Comment by styller1** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:site-initializer-raylife-d2c

**Comment by nikki-pru** [comment]
Reviewing

**Comment by nikki-pru** [comment]
ci:forward

**Comment by styller1** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
