### PR TITLE
LPS-157305 [Ask] Adjust method to make MB able to filter and sort

### PR DESCRIPTION
**Pull request by franciscoabsl**
During the development of the MB filter, different approaches were tested.

1) Firstly, our team researched how filtering works at Liferay back-end.
We found out that to use Liferay filters we had to make sure our entity was indexed using the indexing framework. 
Once the field we needed was not being persisted on the DB and it was being dynamically calculated during the conversion through the DTO, we got struggled and the attempts we made to index it were unsuccessful.

https://help.liferay.com/hc/en-us/articles/360039425691-Managing-Collections-in-REST-Builder

2) Then we tried to use DynamicQuery API for filtering. But, after some research and attempts, we find out that this approach would not be appropriate because this API is recommended for simple queries and when it is not necessary the use of multiple JOINS. Since we could need multiple JOINS (depending on what filters were selected) of tables (MBThread, MBMessage, RatingStats, ViewCountEntry, AssetTag, AssetEntries_AssetTags) we decided to use the approach below to solve our task.

https://help.liferay.com/hc/en-us/articles/360017882032-Dynamic-Query

3) Our final approach was to use Custom SQL and write our own custom SQL queries. This method gave us the flexibility we needed to achieve our goal and to succeed in the development of a solution that supports sorting by created date, modified date, total score, view count, and filters by threads with/without accepted answers, threads without anwers and threads with specifics tags.

https://help.liferay.com/hc/en-us/articles/360030959031-Custom-SQL

### CODE REVIEW

**Comment by franciscoabsl** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
How to test it:

GraphQL Query (/o/api) > GraphQL

```
query messageBoardSectionFilteredMessageBoardThreads(
	$messageBoardSectionId: Long!
	$page: Int!
	$pageSize: Int!
  	$filter: String!
  	$sort: String!
  	$tag: String!
	) {
		messageBoardSectionFilteredMessageBoardThreads(
			messageBoardSectionId: $messageBoardSectionId
			page: $page
			pageSize: $pageSize
            filter: $filter
            sort: $sort
            tag: $tag
		) {
			items {
				aggregateRating {
					ratingAverage
					ratingCount
					ratingValue
				}
				articleBody
				creator {
					id
					image
					name
				}
				dateModified
				friendlyUrlPath
				hasValidAnswer
				headline
				id
				keywords
				locked
				messageBoardSection {
					numberOfMessageBoardSections
					parentMessageBoardSectionId
					title
				}
				numberOfMessageBoardMessages
				seen
				status
				viewCount
			}
            lastPage
			page
			pageSize
			totalCount
		}
	}
```

Query Variable

```
 {
    "messageBoardSectionId": 42606,
    "page": 1,
    "pageSize": 5,
    "filter": "hasValidAnswer eq 'true'",
    "sort": "totalScore:asc",
    "tag": "java,python"
  }
```

The Query Variables should be different to tou.

**Comment by kevenleone** [comment]
Thank you so much for the PR @franciscoabsl , we are going to continue your legacy from here :D 

@joseabelenda , @velosofelipe64 , I found a bug with `tag` 

If you put 

```
 {
    "messageBoardSectionId": 42606,
    "page": 1,
    "pageSize": 5,
    "filter": "hasValidAnswer eq 'true'",
    "sort": "totalScore:asc",
    "tag": ""
  }
```

With tag empty string, the backend throws an error, pretty bad (because it exposes a SQL Query)

image

Can someone fix that?

**Comment by kevenleone** [comment]
I also have a concern about this Custom SQL, this is sanitized ? I'm asking it to avoid possible SQL Injection

**Comment by franciscoabsl** [comment]
> I also have a concern about this Custom SQL, this is sanitized ? I'm asking it to avoid possible SQL Injection

The Custom SQL tool works by replacing parts of a custom query according to the GraphQL parameters. I think there is no way for a query to be injected directly.

**Pull request closed without merging**
