### PR TITLE
LPS-195262 [Marketplace] Fixing the filter and the search results for the solutions and app page

### PR DESCRIPTION
**Pull request by ytuik**

### CODE REVIEW

**Comment by ytuik** [comment]
ci:forward

**Comment by ytuik** [comment]
ci:test:sf

**Comment by ytuik** [comment]
ci:stop

**Comment by ytuik** [comment]
ci:forward

**Comment by ocesar9** [comment]
y

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by ytuik** [comment]
ci:forward

**Comment by itstali** [comment]
Hey @ytuik the errors showed here has nothing to do with your PR, you can push forward :100:

**Comment by silasbsi** [comment]
ci:test:site-initializer-liferay-marketplace

**Pull request closed without merging**
