### PR TITLE
LPS-178555 [Raylife AP] Add Action Component in Claim Details Page

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-160817](https://issues.liferay.com/browse/LPS-160817)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
Good job. @joanagrego :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:stop

**Pull request closed without merging**
