### PR TITLE
LPS-184863 [Marketplace] Create the Additional Info User object and the connection on the form

### PR DESCRIPTION
**Pull request by ytuik**
https://issues.liferay.com/browse/LPS-184863 

Wait for https://github.com/pt-liferay-solutions/liferay-portal/pull/4080 to be merged

### CODE REVIEW

**Comment by juliocezar96** [comment]
Just starting reviewing :)

**Review by joanagrego — CHANGES_REQUESTED** [review]

**Comment by juliocezar96** [comment]
Just starting reviewing :)

**Review by joanagrego — APPROVED** [review]
Approved! :white_check_mark:

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
Just starting reviewing :)

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by ytuik** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:forward

**Review by juliocezar96 — APPROVED** [review]
Nice job! 🤙

**Comment by juliocezar96** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
Resent --> [PR](https://github.com/brianchandotcom/liferay-portal/pull/135662)

**Pull request closed without merging**
