### PR TITLE
LPS-175739 [EVP] Checkbox are not being displayed on the page

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-175739](https://issues.liferay.com/browse/LPS-175739)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Review by eliasantosf — APPROVED** [review]
LHTM, Tks! @juliocezar96

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
