### PR TITLE
LPS-145592 [RAYLIFE] Adjusted Trailing zeros in pricing, on Raylife Payment Method & Processing

### PR DESCRIPTION
**Pull request by welitonpe**

### CODE REVIEW

**Review by silasbsi — COMMENTED** [review]
LGTM :fire:

**Comment by silasbsi** [comment]
ci:test:sf

**Review by silasbsi — COMMENTED** [review]
LGTM :fire:

**Comment by welitonpe** [comment]
ci:test:sf

**Review by kevenleone — CHANGES_REQUESTED** [review]
Waiting for changes requested in person

**Comment by welitonpe** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGMT 🔥

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
