### PR TITLE
[Digital Signature] Test Fix LPS-195837 | Master

### PR DESCRIPTION
**Pull request by MGabriellaS**
[LPS-195837](https://liferay.atlassian.net/browse/LPS-195837)

### CODE REVIEW

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
LGTM!
Good to go

**Comment by joelrocha68** [comment]
ci:forward

**Comment by MGabriellaS** [comment]
ci:forward

**Pull request closed without merging**
