### PR TITLE
LPS-144319 Add tests and paths for RaylifeQuoteComparison archive

### PR DESCRIPTION
**Pull request by luanakarla**

### CODE REVIEW

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:site-initializer-raylife

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by Paulovcaselli** [comment]
ci:test:site-initializer-raylife

**Comment by Paulovcaselli** [comment]
ci:forward

**Pull request closed without merging**
