### PR TITLE
LPS-176683 [Raylife AP] Create Reviewed and Rejected Applications Details Pages

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-176683](https://issues.liferay.com/browse/LPS-176683)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:solutions-acceptance

**Review by claricebrasil — APPROVED** [review]
Great job!

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
