### PR TITLE
LPS-180231 [Raylife AP] Remove Raylife AP Feature Flag

### PR DESCRIPTION
**Pull request by joanagrego**
Related to --> [LPS-180231](https://issues.liferay.com/browse/LPS-180231)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:reevaluate:1277401_7725

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by styller1** [comment]
By build analysis, this pr does not appear to be breaking any test related to the product

**Comment by joanagrego** [comment]
Resent --> [PR](https://github.com/brianchandotcom/liferay-portal/pull/133459)

**Pull request closed without merging**
