### PR TITLE
LPS-171058 [Raylife AP] Product filter fix

### PR DESCRIPTION
**Pull request by eliasantosf**

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:relevant

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Review by joanagrego — APPROVED** [review]
Approved! Thank you @eliasantosf :white_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
