### PR TITLE
LPS-150666 [CP2.0] Add CP2KeyDetailsPortal tests

### PR DESCRIPTION
**Pull request by luanakarla**

### CODE REVIEW

**Comment by luanakarla** [comment]
It depends on https://github.com/pt-liferay-solutions/liferay-portal/pull/1969

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by barrosdennys** [comment]
ci:forward

**Pull request closed without merging**
