### PR TITLE
LPS-160908 [Raylife AP]  Hide label "CHOOSE AN OPTION"

### PR DESCRIPTION
**Pull request by EugenioAntunes**
Sub task: [LPS-160908](https://issues.liferay.com/browse/LPS-160908)

### CODE REVIEW

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Review by joanagrego — COMMENTED** [review]
Nice job!

**Review by joanagrego — APPROVED** [review]

**Review by silasbsi — APPROVED** [review]
LGTM :martial_arts_uniform: Thanks @EugenioAntunes

**Pull request closed without merging**
