### PR TITLE
LPS-150588 [CP2.0] Add CP2ProjectBreadCrumb tests

### PR DESCRIPTION
**Pull request by styller1**
https://issues.liferay.com/browse/LPS-150588

### CODE REVIEW

**Comment by styller1** [comment]
ci:test:sf

**Review by AfonsoHSantos — CHANGES_REQUESTED** [review]

**Comment by styller1** [comment]
ci:test:sf

**Review by AfonsoHSantos — APPROVED** [review]

**Comment by luanakarla** [comment]
ci:forward

**Comment by styller1** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:forward

**Pull request closed without merging**
