### PR TITLE
LPS-187543 [EVP] Creation of the flow for approval of requests of the type "sponsorship"

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-187543](https://issues.liferay.com/browse/LPS-187543)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
Good job

**Comment by eliasantosf** [comment]
ci:forward:force

**Comment by eliasantosf** [comment]
ci:forward:force

**Pull request closed without merging**
