### PR TITLE
LPS-175877 [Raylife D2C/AP] Setup Commerce Product visibility through Site Initializer

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-175877](https://issues.liferay.com/browse/LPS-175877)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:reevaluate:1377401_9053

**Comment by joanagrego** [comment]
ci:relevant

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
Just starting reviewing :)

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
Resent --> [PR](https://github.com/pt-liferay-solutions/liferay-portal/pull/3326)

**Pull request closed without merging**
