### PR TITLE
LPS-145895 Previous button does not appear on the Ipad

### PR DESCRIPTION
**Pull request by silasbsi**

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGMT 🔥

**Review by welitonpe — COMMENTED** [review]
LGTM :fire:

**Review by welitonpe — COMMENTED** [review]
LGTM :fire:

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
