### PR TITLE
LPS-176606 [CP 2.0] Add allowSelfProvisioning field to fix validation

### PR DESCRIPTION
**Pull request by caiosouza15**

### CODE REVIEW

**Review by jairmedeiros — APPROVED** [review]
LGTM

**Comment by jairmedeiros** [comment]
Waiting @JoMaAlves review to run ci:forward

**Comment by jairmedeiros** [comment]
Hey @caiosouza15, as a suggestion, it best to create commit messages with more context about what you are coding.
For instance, instead "Creates the new logic, refactors the coding and resolutions of the bug", it can be "Add allowSelfProvisioning field to fix validation"

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @caiosouza15

**Comment by JoMaAlves** [comment]
ci:forward

**Pull request closed without merging**
