### PR TITLE
LPS-173378 [Raylife AP] - Fix Creating exception for No data.

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-173378](https://issues.liferay.com/browse/LPS-173378)

### CODE REVIEW

**Review by joanagrego — APPROVED** [review]
Approved! Thank you @eduardo-diniz :white_check_mark:

**Review by claricebrasil — APPROVED** [review]

**Comment by claricebrasil** [comment]
ci:forward

**Comment by claricebrasil** [comment]
ci:forward

**Comment by claricebrasil** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
