### PR TITLE
LPS-144749 Update Hang tight fragment to Mobile and Tablet View

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Good job

**Comment by kevenleone** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:stop

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
