### PR TITLE
LPS-195386 [Marketplace] Adjust the price facet and search results

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-195386](https://issues.liferay.com/browse/LPS-195386)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by claricebrasil — COMMENTED** [review]
Formatting issue

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by claricebrasil — APPROVED** [review]

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by LuanaKSilva** [comment]
cc @jairmedeiros

**Comment by jairmedeiros** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/4759

**Pull request closed without merging**
