### PR TITLE
LPS-180067 Fixed missing column information

### PR DESCRIPTION
**Pull request by welitonpe**

### CODE REVIEW

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Good job!

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/3639

**Pull request closed without merging**
