### PR TITLE
LPS-193022 AddExpandoValue and refactor replaces in BundleSiteInitializer

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:forward

**Comment by nNilton** [comment]
ci:reevaluate:1407401_5779

**Comment by nNilton** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/140305

**Pull request closed without merging**
