### PR TITLE
LPS-146902 Fix wrap buttons on Case Results page

### PR DESCRIPTION
**Pull request by welitonpe**

### CODE REVIEW

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by welitonpe** [comment]
ci:test:stable

**Comment by welitonpe** [comment]
ci:teste:relevant

**Comment by welitonpe** [comment]
ci:foward

**Comment by thaiscabrals** [comment]
ci:stop

**Comment by welitonpe** [comment]
ci:forward

**Pull request closed without merging**
