### PR TITLE
LPS-195360 Added a data propertie on template email

### PR DESCRIPTION
**Pull request by welitonpe**
https://liferay.atlassian.net/browse/LPS-195357

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by welitonpe** [comment]
ci:test:sf

**Review by caiosouza15 — APPROVED** [review]
Good Job @welitonpe 
Pretty code

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by welitonpe** [comment]
ci:forward

**Pull request closed without merging**
