### PR TITLE
LPS-162897 [QUESTIONS] Activity Improvements - Latest Activity Page

### PR DESCRIPTION
**Pull request by joseabelenda**
.

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by guivilarim** [comment]
ci:test:stable

**Comment by joseabelenda** [comment]
ci:forward:force

**Comment by joseabelenda** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/139278

**Pull request closed without merging**
