### PR TITLE
LPS-185759 [QUESTIONS] Thread Improvements - Add userGroup labels

### PR DESCRIPTION
**Pull request by claricebrasil**

### CODE REVIEW

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:test:relevant

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:test:sf:stop

**Review by jairmedeiros — APPROVED** [review]

**Pull request closed without merging**
