### PR TITLE
LPS-159347 [Raylife AP] Set up pagination

### PR DESCRIPTION
**Pull request by pedroliveirav**
Sub-task: [LPS-159347](https://issues.liferay.com/browse/LPS-159347)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
You uploaded wrong files in your commits. Please resend. @pedroliveirav

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
Resent --> https://github.com/pt-liferay-solutions/liferay-portal/pull/2083

**Pull request closed without merging**
