### PR TITLE
LPS-195284 [CP 2.0] Remove sidebar fragment

### PR DESCRIPTION
**Pull request by pedroliveirav**
[LPS-195284](https://liferay.atlassian.net/browse/LPS-195284)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Review by Aline160 — APPROVED** [review]

**Comment by kevenleone** [comment]
ci:forward

**Comment by pedroliveirav** [comment]
ci:stop

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Comment by Aline160** [comment]
Just starting reviewing :)

**Comment by pedroliveirav** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/4764

**Pull request closed without merging**
