### PR TITLE
LPS-178658 [Raylife AP] Update Raylife's List Types Definitions

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-178658](https://issues.liferay.com/browse/LPS-178658)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:relevant

**Review by silasbsi — APPROVED** [review]
Good job. @joanagrego :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
