### PR TITLE
LPS-177040 [Site initializer] Replace Portal URL and group friendly URL on site initializer for notification templates

### PR DESCRIPTION
**Pull request by TamyrisTorres**

### CODE REVIEW

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:forward

**Comment by TamyrisTorres** [comment]
ci:forward

**Pull request closed without merging**
