### PR TITLE
CP 2.0 Automation Test: LPS-150114 | master

### PR DESCRIPTION
**Pull request by luanakarla**
Ticket: 
[LPS-150114](https://issues.liferay.com/browse/LPS-150114)
Tests: 
CP2ActivationCardLXCSM#AssertChangeOfCardStatusToActive
CP2ActivationCardLXCSM#AssertThatTheConfirmationIDHasBeenUpdated
CP2ActivationCardLXCSM#AssertThatTheStatusIsTheSameWhenCancelingAnAction

### CODE REVIEW

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Review by renato-araujo-liferay — APPROVED** [review]
WD @luanakarla

**Comment by luanakarla** [comment]
ci:forward

**Pull request closed without merging**
