### PR TITLE
LPS-183458  [EVP]  Breadcrumb adjustment on submit page Organization

### PR DESCRIPTION
**Pull request by raquelpaiva**
[LPS-183458](https://issues.liferay.com/browse/LPS-184316)

### CODE REVIEW

**Comment by raquelpaiva** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @raquelpaiva

**Comment by eliasantosf** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:stop

**Pull request closed without merging**
