### PR TITLE
Refactor Questions LRQA-82834 | Master

### PR DESCRIPTION
**Pull request by MGabriellaS**
[LRQA-82834](https://liferay.atlassian.net/browse/LRQA-82834)

### CODE REVIEW

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by MGabriellaS** [comment]
ci:sf:test

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:questions

**Comment by nikki-pru** [comment]
Failures are not related.
Thanks!

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
