### PR TITLE
LPS-159605 [Raylife AP] Set the email field of the Application table as a link that redirects to send an email.

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-159605](https://issues.liferay.com/browse/LPS-159605)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @joanagrego

**Review by silasbsi — APPROVED** [review]
LGTM 🥇 Thanks @joanagrego

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
