### PR TITLE
LPS-180483, LPS-180770 [CP 2.0] Portal and DXP activation not loading for NVI project, Fixed Digital Enterprise keys are not listed under DXP activation keys

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Review by jairmedeiros — APPROVED** [review]

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Pull request closed without merging**
