### PR TITLE
SF

### PR DESCRIPTION
**Pull request by rafaelfs98**

### CODE REVIEW

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/133169

**Comment by alvarolealdl** [comment]
Just starting reviewing :)

**Comment by alvarolealdl** [comment]
Just starting reviewing :)

**Comment by alvarolealdl** [comment]
Just starting reviewing :)

**Pull request closed without merging**
