### PR TITLE
LPS-170269 Fixed status in case results and disabled "Edit" and "Unassign Myself" buttons when assigning

### PR DESCRIPTION
**Pull request by samuelleolopes**

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:sf

**Review by welitonpe — APPROVED** [review]
LGTM :fire:

**Review by rafaelfs98 — APPROVED** [review]
Very good :fire:

**Review by kevenleone — COMMENTED** [review]
@samuelleolopes can you take a look?

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
