### PR TITLE
LPS-143160 Word Commercial not showing under Raylife

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Review by kevenleone — CHANGES_REQUESTED** [review]
@JoMaAlves can you take a look for indentation?

Try to run:

`gw formatSource`
`yarn format`

inside site-initializer-raylife

Some lines are real strange

**Comment by JoMaAlves** [comment]
For some reason, one line continue to be strangely indented

**Comment by JoMaAlves** [comment]
Oh I forgot the yarn format, 1 sec

**Comment by JoMaAlves** [comment]
@kevenleone Done! But for some reason, in the 2 css files, tab spaces are displayed differently, one smaller than the other.

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
