### PR TITLE
LPS-152315 Recent activities return results that didn't recently changed

### PR DESCRIPTION
**Pull request by gleicelisbino**

### CODE REVIEW

**Comment by gleicelisbino** [comment]
ci:test:sf

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
@gleicelisbino , testes do message board estao falhando com essa PR, talvez precise corrigir algum teste

**Comment by gleicelisbino** [comment]
@kevenleone Bem lembrado, sao os testes que eu fiz o fix em outra pr.

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
Resent#https://github.com/pt-liferay-solutions/liferay-portal/pull/2732

**Pull request closed without merging**
