### PR TITLE
LPS-181973 [EVP] Organization Status update by Workflow

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-181973](https://issues.liferay.com/browse/LPS-181973)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
ci:stop

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/3771

**Comment by joseabelenda** [comment]
@eliasantosf please see my changes on https://github.com/pt-liferay-solutions/liferay-portal/pull/3771.
Thx.

**Pull request closed without merging**
