### PR TITLE
LPS-181371 [EVP] Add Title on the page with the Name of the reporter

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-181371](https://issues.liferay.com/browse/LPS-181371)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
