### PR TITLE
LPS-189340 [MARKETPLACE] Adjusted custom fields already created

### PR DESCRIPTION
**Pull request by welitonpe**
[LPS-188692](https://liferay.atlassian.net/browse/LPS-188692)

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by brenobcos** [comment]
Just starting reviewing :)

**Review by brenobcos — APPROVED** [review]
Looks great to me!✅

**Comment by welitonpe** [comment]
ci:test:stable
ci:test:relevant

**Review by joanagrego — APPROVED** [review]
Approved! Thanks @welitonpe :white_check_mark:

**Comment by welitonpe** [comment]
ci:forward

**Review by juliocezar96 — APPROVED** [review]
Nice job! 🤙

**Comment by welitonpe** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:forward:force

**Pull request closed without merging**
