### PR TITLE
LPS-169358 [PRM] Empty state tooltip on activities page just appear when 'Continue' button is clicked

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
https://issues.liferay.com/browse/LPS-169358

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward

**Comment by eltonccdantas** [comment]
It looks good to me. :sunglasses:, As it's already been forwarded, thanks!

**Pull request closed without merging**
