### PR TITLE
LPS-163132 [EVP] Create EVP Process Title

### PR DESCRIPTION
**Pull request by juliocezarjc**
[LPS-163132](https://issues.liferay.com/browse/LPS-163132)

### CODE REVIEW

**Comment by juliocezarjc** [comment]
ci:test:sf

**Comment by juliocezarjc** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :martial_arts_uniform:

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @juliocezarjc

**Comment by juliocezarjc** [comment]
ci:test:relevant

**Pull request closed without merging**
