### PR TITLE
LPS-143770 and LPS-143771 Team members invitation page

### PR DESCRIPTION
**Pull request by iagochaves**

### CODE REVIEW

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

The code is really cool @iagochaves 👍🏻

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by iagochaves** [comment]
ci:test:relevant

**Comment by iagochaves** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
