### PR TITLE
[LPS-144952] [CP 2.0] Adjustments to Quick Links Panel

### PR DESCRIPTION
**Pull request by iagochaves**

### CODE REVIEW

**Review by igordmf — APPROVED** [review]
Good job!

**Review by Lucas2691 — APPROVED** [review]
Nice job.

**Review by claricebrasil — APPROVED** [review]

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
@jairmedeiros you can forward this pr anytime

**Comment by jairmedeiros** [comment]
sorry guys @iagochaves @kevenleone. As this PR as not notified to me, It was escaped from my radar.

**Comment by jairmedeiros** [comment]
Let's just keep the discussion  https://github.com/pt-liferay-solutions/liferay-portal/pull/1074#discussion_r828003111, that I guess was ignored, but it's very important for the next PRs :)

I will forward it.

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
