### PR TITLE
LPS-162897 Activity Improvements - Latest Activity Page

### PR DESCRIPTION
**Pull request by TamyrisTorres**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/4433

**Pull request closed without merging**
