### PR TITLE
LPS-183520 The Incorrect Flow in Case Result

### PR DESCRIPTION
**Pull request by rafaelfs98**

### CODE REVIEW

**Review by welitonpe — COMMENTED** [review]
LGTM :fire:

**Review by Elvinho — APPROVED** [review]
Nice 👋🏾

**Review by EugenioAntunes — APPROVED** [review]
Nice job, Man! 🐐

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by rafaelfs98** [comment]
ci:forward

**Pull request closed without merging**
