### PR TITLE
LPS-168930 [PRM] Create 2 separate tabs to the Deal registration listing view

### PR DESCRIPTION
**Pull request by thaynam**
[LPS-168930](https://issues.liferay.com/browse/LPS-168930)
Create 2 separate tabs to the Deal registration listing view

[LPS-156584](https://issues.liferay.com/browse/LPS-156584)
Renewals Listing - Partner View

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:stable

**Comment by thaynam** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @thaynam

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
