### PR TITLE
LPS-140162 SF

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-140162 Liferay contact</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-140162">Liferay contact</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Story</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Development</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Jair Medeiros</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Rafael Dantas</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-140150 Get started page</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-140150">Get started page</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Story</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>4/5 Completed</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Development</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Elias Santos</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Rafael Dantas</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-140155 Projects Listing - With less than 5 projects</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-140155">Projects Listing - With less than 5 projects</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Story</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Development</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Aguinus Santana</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Rafael Dantas</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-140156 Projects Listing - With more than 5 projects</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-140156">Projects Listing - With more than 5 projects</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Story</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Development</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Aguinus Santana</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Rafael Dantas</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-140160 Navigation menu basic structure</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-140160">Navigation menu basic structure</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Story</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Development</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Jair Medeiros</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Rafael Dantas</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

76 files changed, 1402 insertions(+), 761 deletions(-)

This PR is too huge for one to review :broken_heart:

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:forward

**Comment by brunnocastro** [comment]
Just starting reviewing :)

**Pull request closed without merging**
