### PR TITLE
LPS-184595 Fixing Setup For Customer Portal 2.0

### PR DESCRIPTION
**Pull request by styller1**
Ticket:
[LPS-184595](https://issues.liferay.com/browse/LPS-184595)

### CODE REVIEW

**Comment by styller1** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by styller1** [comment]
ci:test:site-initializer-customer-portal:nocompile

**Comment by styller1** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by luanakarla** [comment]
Hey @styller1, thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by luanakarla** [comment]
Hey @styller1, thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by luanakarla** [comment]
ci:forward

**Pull request closed without merging**
