### PR TITLE
LPS-134452 Create OriginalDocumentTag Component

### PR DESCRIPTION
**Pull request by MateusCastro**

### CODE REVIEW

**Comment by MateusCastro** [comment]
ci:test:sf

**Comment by MateusCastro** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:sf

**Review by joseabelenda — APPROVED** [review]
LGTM.

Thanks, @MateusCastro

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
