### PR TITLE
LPS-168246 [Raylife AP] Year of Vehicle in Automobile Policy does not appear

### PR DESCRIPTION
**Pull request by eliasantosf**

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]

**Review by silasbsi — APPROVED** [review]
LGMT :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
