### PR TITLE
[TS] [Questions] LPS-154165 Add Comment buttons formatted the same as other buttons

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team, 

**Notes from @jakesliwka:**
> https://issues.liferay.com/browse/LPS-154165
> Due to recent changes, in a Questions widget, the button "Reply" was changed to "Add Comment", and also had a formatting update, giving it a different style than the other options. The LPS requested that all buttons have the same format like they did before the changes. This update changes the format back to the original format for both "Add Comment" buttons (the button initially seen, as well as the button that appears after a comment has been posted).
> 
> Example:
> Before all changes:
> image
> 
> After the recent updates:
> image
> 
> After my formatting changes :
> image
> (second button)
> image

**Additional Notes**
The commit that introduced the format difference: https://github.com/liferay/liferay-portal/commit/8f9c3a29eb59cdc0b90d97a0bbafc3053b831dc0

QA created this LPS ticket when they discovered the inconsistent format. If this was actually intentional, it would be great if you can provide an update on the LPS ticket.

Please let us know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
@ericyanLr Thank you for submitting this PR.

At first, this was done intentionally, I'll take a look for additional information and give you a properly answer about that.

I'll be responding you soon

**Comment by Lucas2691** [comment]
Thank you, @ericyanLr . We'll talk about this design decision again.

**Comment by kevenleone** [comment]
@ericyanLr, @Lucas2691 sent a PR https://github.com/pt-liferay-solutions/liferay-portal/pull/1589

Replacing all buttons for better consistence, thanks.

**Pull request closed without merging**
