### PR TITLE
LPS-189274 Add vocabularyIds to Category Facets

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
si:test:sf

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Review by silasbsi — APPROVED** [review]
Good job :martial_arts_uniform:

**Comment by silasbsi** [comment]
ci:test:site-initializer-liferay-marketplace:nocompile

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
