### PR TITLE
LPS-143144 Fix Dialect Styles

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by Lucas2691** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/437

**Pull request closed without merging**
