### PR TITLE
LPS-172704 [PRM] CSS code added to avoid displaying images in announcements

### PR DESCRIPTION
**Pull request by ericthmoritsuka**
Related issue: https://issues.liferay.com/browse/LPS-172704

### CODE REVIEW

**Comment by ericthmoritsuka** [comment]
ci:test:sf

**Comment by ericthmoritsuka** [comment]
ci:test:relevant

**Review by thaynam — APPROVED** [review]
ci:forward

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
