### PR TITLE
LPS-184612 This is a B2C Site, so the accounts need to be personal

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-184612](https://issues.liferay.com/browse/LPS-184612)

### CODE REVIEW

**Comment by jpince** [comment]
@kevenleone please review!

**Comment by kevenleone** [comment]
LGTM 🔥 

Thanks @jpince , @mbowerman

**Comment by kevenleone** [comment]
ci:forward

**Comment by jpince** [comment]
ci:close see Zendesk ticket. This solution is under discussion, so closing this PR until the correct solution is confirmed. Tests can continue to run.

**Pull request closed without merging**
