### PR TITLE
LPS-158851 [Raylife AP] Getting data from coverage

### PR DESCRIPTION
**Pull request by EugenioAntunes**

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:stop

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :1st_place_medal:

**Comment by silasbsi** [comment]
ci:forward

**Review by joanagrego — APPROVED** [review]
Nice job! :arrow_up:

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
