### PR TITLE
LPS-189274 [Marketplace] Fix App Marketplace Dashboard Style Adjustments

### PR DESCRIPTION
**Pull request by claricebrasil**

### CODE REVIEW

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:forward:force

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by joanagrego** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Pull request closed without merging**
