### PR TITLE
LPS-178766 [Raylife AP/D2C] Raylife Coockie Refactoring

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Review by silasbsi — APPROVED** [review]
Good job dr. @kevenleone Thanks for your help.

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
