### PR TITLE
LPS-161174, LPS-163805, LPS-163838 [ASK] add new Filters and Sorts for search thread

### PR DESCRIPTION
**Pull request by velosofelipe64**

### CODE REVIEW

**Comment by velosofelipe64** [comment]
ci:test:sf

**Comment by velosofelipe64** [comment]
ci:test:sf

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Comment by velosofelipe64** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/123943

**Comment by velosofelipe64** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/123943

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Pull request closed without merging**
