### PR TITLE
LPS-166126 Testray TestFlow DispatchTrigger and Testray AutoFill Dispatch Trigger

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Comment by samuelleolopes** [comment]
Just starting reviewing :)

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Pull request closed without merging**
