### PR TITLE
[Testray] LPS-166126 DispatchTrigger to create tasks and subtasks

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:stop

**Comment by nNilton** [comment]
ci:close

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/2680

**Pull request closed without merging**
