### PR TITLE
LPS-163611 Bug fixes of Requirements form, Components form, Team forms and Breadcrumb search

### PR DESCRIPTION
**Pull request by welitonpe**

### CODE REVIEW

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Comment by welitonpe** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:stop

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/123480

**Pull request closed without merging**
