### PR TITLE
LPS-145043 Improve Liferay API in Remote App

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-145043 Improve Liferay API in Remote App</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-145043">Improve Liferay API in Remote App</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

14 files changed, 92 insertions(+), 174 deletions(-)

**Comment by Abigailmelo** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
@Abigailmelo hello

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
