### PR TITLE
LPS-165493 Putting Raylife AP Under Feature Flag

### PR DESCRIPTION
**Pull request by joanagrego**
As per recommendation of Sales Enablement, we should hide Raylife AP under feature flag as to not create confusion for both Sales and potential customers as to whether the product is working properly or not.

Related with --> [LPS-165493](https://issues.liferay.com/browse/LPS-165493)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
