### PR TITLE
LPS-176908 [EVP]  It is not possible filter reports by company name

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-176908](https://issues.liferay.com/browse/LPS-176908)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @juliocezar96

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
