### PR TITLE
LPS-178797 [EVP] Implementing Edit Organization for EVP Manager

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-178797](https://issues.liferay.com/browse/LPS-178797)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:bundle

**Review by luisacmn — APPROVED** [review]
Great job!

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:bundle

**Review by eliasantosf — APPROVED** [review]

**Comment by eliasantosf** [comment]
ci:forward

**Comment by juliocezar96** [comment]
ci:forward

**Comment by juliocezar96** [comment]
ci:forward

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:forward

**Pull request closed without merging**
