### PR TITLE
LPS-195063[Marketplace] Remove footer from react

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-195063](https://liferay.atlassian.net/browse/LPS-195063)

### CODE REVIEW

**Comment by juliocezar96** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-195063 Remove footer from react</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-195063">Remove footer from react</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Low</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Open</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Julio Cezar</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Julio Cezar</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

7 files changed, 40 insertions(+), 39 deletions(-)

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:stable

**Review by joanagrego — APPROVED** [review]
Approved! Thanks @juliocezar96 :white_check_mark:

**Review by eliasantosf — APPROVED** [review]

**Review by claricebrasil — APPROVED** [review]

**Comment by juliocezar96** [comment]
ci:forward:force

**Comment by juliocezar96** [comment]
ci:forward:force

**Comment by juliocezar96** [comment]
ci:forward:force

**Pull request closed without merging**
