### PR TITLE
LPS-172796 [PRM] View button is being shown on the next screen

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
https://issues.liferay.com/browse/LPS-172796

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
thanks you for this @pedro-oliveira446, can you please also add it to the MDF Claim List, we have the same problem over there. I beleave the files is the  [MDFClaimList.tsx](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/src/routes/MDFClaimList/MDFClaimList.tsx#L58)

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
Done ! @thaynam .

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
