### PR TITLE
LPS-163996 [Raylife AP] Previous button still working and Next button doesn't appear

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-163996](https://issues.liferay.com/browse/LPS-163996)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Good job! :white_check_mark:

**Review by silasbsi — APPROVED** [review]
LGTM 😁

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
