### PR TITLE
LPS-182070 [Raylife Ap] Underline should appear on Auto Claims

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-182070](https://issues.liferay.com/browse/LPS-182070)
[LPS-182071](https://issues.liferay.com/browse/LPS-182071)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
:white_check_mark:

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
