### PR TITLE
LPS-146875 The previous button and continue without functionality on the Ipad

### PR DESCRIPTION
**Pull request by luisxx123**

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Review by silasbsi — COMMENTED** [review]
LGMT :fire:

**Comment by silasbsi** [comment]
@kevenleone could you make another review?

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Good catch!

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
