### PR TITLE
LPS-140158 [CP 2.0] Remove unnecessary lines from .gitignore

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:stable

**Comment by joseabelenda** [comment]
ci:forward

**Comment by iagochaves** [comment]
Just starting reviewing :)

**Pull request closed without merging**
