### PR TITLE
LPS-183570 [Marketplace] Add Design Templates

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-183570](https://issues.liferay.com/browse/LPS-183570)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:bundle

**Comment by juliocezar96** [comment]
ci:test:bundle

**Comment by juliocezar96** [comment]
ci:test:relevant

**Review by silasbsi — APPROVED** [review]

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
