### PR TITLE
LPS-170834 [Raylife AP] Create Total Claims Chart

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-170834](https://issues.liferay.com/browse/LPS-170834)
[FE] Create Total Claims Chart

### CODE REVIEW

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
Resent --> https://github.com/pt-liferay-solutions/liferay-portal/pull/2941

**Pull request closed without merging**
