### PR TITLE
LPS-160661 [Raylife AP] Fix to save product name in object

### PR DESCRIPTION
**Pull request by juliocezarjc**
Impedibug: [LPS-160661](https://issues.liferay.com/browse/LPS-160661)

### CODE REVIEW

**Comment by juliocezarjc** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :martial_arts_uniform: :fist_oncoming:  Thanks @juliocezarjc

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ @juliocezarjc

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @juliocezarjc

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
