### PR TITLE
LPS-193694 [MARKETPLACE] Add DDM Templates to App Details Display Page Template

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by claricebrasil** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:forward

**Comment by LuanaKSilva** [comment]
Hey @joanagrego, I've analyzed the errors and none of them have anything to do with your PR. Forwarding to Brian. Thanks!

**Comment by LuanaKSilva** [comment]
ci:forward:force

**Pull request closed without merging**
