### PR TITLE
LPS-192793 [Marketplace] Adjusts on Clarity Trial to send all data to SSA API

### PR DESCRIPTION
**Pull request by welitonpe**
LPS-188732

### CODE REVIEW

**Review by juliocezar96 — APPROVED** [review]
Nice job! 🤙

**Comment by juliocezar96** [comment]
ci:test:sf

**Review by ytuik — COMMENTED** [review]
LGTM! :fire:

**Review by ytuik — APPROVED** [review]

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by welitonpe** [comment]
ci:stable

**Comment by welitonpe** [comment]
ci:test:sf

**Comment by welitonpe** [comment]
ci:forward

**Comment by LuanaKSilva** [comment]
ci:test:stable

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
Pull Request forwarded: https://github.com/brianchandotcom/liferay-portal/pull/139023

**Comment by kevenleone** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/139023

**Pull request closed without merging**
