### PR TITLE
PRM Automated Test - LPS-182116 | LPS-188868 | LPS-188238 | LPS-192014| master

### PR DESCRIPTION
**Pull request by marinaasant0s**
[LPS-182116](https://liferay.atlassian.net/browse/LPS-182116) - PRMMDFRequestActivities#CanSubmitMDFWithEventInPersonActivity
[LPS-188868](https://liferay.atlassian.net/browse/LPS-188868) - Automate PRMMDFRequestActivities#CanSubmitMDFWithDigitalMarketingAdvertisingActivity
[LPS-188238](https://liferay.atlassian.net/browse/LPS-188238) - Automate PRMMDFRequestActivities#CanSubmitMDFWithEventWebinarActivity
[LPS-192014](https://liferay.atlassian.net/browse/LPS-192014) - Automate PRMMDFRequestActivities#CanSubmitMDFWithContentMarketingActivity

### CODE REVIEW

**Comment by marinaasant0s** [comment]
ci:test:sf

**Comment by marinaasant0s** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
Hi @marinaasant0s, thanks for working on it.
The code looks good to me!

**Comment by AfonsoHSantos** [comment]
ci:forward

**Pull request closed without merging**
