### PR TITLE
LPS-159638 [Raylife AP] Create mocked data for policies and sales goal entities

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-159638](https://issues.liferay.com/browse/LPS-159638)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
