### PR TITLE
LPS-192097 [PRM] The tactic type fields in the details do not match what was requested in the activity

### PR DESCRIPTION
**Pull request by Manda-vit**

### CODE REVIEW

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by Manda-vit** [comment]
ci:foward

**Comment by Manda-vit** [comment]
ci:forward

**Comment by Manda-vit** [comment]
ci:forward

**Comment by Manda-vit** [comment]
ci:forward

**Pull request closed without merging**
