### PR TITLE
LPS-173180 [EVP] Implementation of roles

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-173180](https://issues.liferay.com/browse/LPS-173180)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
