### PR TITLE
LPS-189548 [CP 2.0] Fix Start date by default should be the current date and success message

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-189548](https://liferay.atlassian.net/browse/LPS-189548)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Good job @eduardo-diniz !

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by eduardo-diniz** [comment]
ci:forward

**Pull request closed without merging**
