### PR TITLE
LPS-146711 [CP 2.0] Update Style Book following Component Library

### PR DESCRIPTION
**Pull request by Lucas2691**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:forward

**Review by jairmedeiros — APPROVED** [review]

**Comment by kevenleone** [comment]
LGTM 🔥 

@jairmedeiros , @Lucas2691 format is missing here

**Review by kevenleone — APPROVED** [review]

**Comment by Lucas2691** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
