### PR TITLE
LPS-164146 [Raylife AP] Adjust the message on the page of Knockout

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-164146](https://issues.liferay.com/browse/LPS-164146)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Nice job! :white_check_mark:

**Review by silasbsi — APPROVED** [review]
LGTM :fire:

**Comment by silasbsi** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Comment by pedro-michel** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
