### PR TITLE
LPS-189249 [CP 2.0] Show quantity column and adjust instance size column display logic

### PR DESCRIPTION
**Pull request by pedroliveirav**
[LPS-189249](https://liferay.atlassian.net/browse/LPS-189249)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Good job @pedroliveirav

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
