### PR TITLE
LPS-191418 [CP 2.0] Generalize user deletion component

### PR DESCRIPTION
**Pull request by pedroliveirav**
[LPS-191418](https://liferay.atlassian.net/browse/LPS-191418)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by pedroliveirav** [comment]
ci:test:sf

**Review by EugenioAntunes — APPROVED** [review]
Nice job, Man ⚡

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by samuelleolopes** [comment]
ci:forward

**Pull request closed without merging**
