### PR TITLE
LPS-140383 [CP 2.0] Activation keys management for Portal

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Review by thaynam — APPROVED** [review]

**Review by claricebrasil — APPROVED** [review]
Great job!

**Comment by igordmf** [comment]
Hey Jair! I think you have inverted the LPS and CP2.0 tags order on PR title 😊 😇

**Review by igordmf — APPROVED** [review]
Nice work!

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
