### PR TITLE
[TS] LPS-167597 Update ClientExtensionEntry portletId

### PR DESCRIPTION
**Pull request by tototrinh**
Hi guys,
Please help review this PR and leave your comments. Thanks.
Ticket: https://issues.liferay.com/browse/LPS-167597
cc: @binhtran92

### CODE REVIEW

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by tototrinh** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
Thank you for send this PR for us, @tototrinh 

@joseabelenda can you take a look? 

I think the team responsible for `client-extension-web` is @liferay-frontend, what you think?

**Review by joseabelenda — APPROVED** [review]
Hi @tototrinh 
Thank you for this PR.
Everything looks good to me.
Feel free to go ahead.

**Comment by tototrinh** [comment]
Hi @joseabelenda @kevenleone, thank you for taking the time on this. Should I resend it to liferay-frontend team?

**Comment by joseabelenda** [comment]
Hi @tototrinh 
I think would be nice.
They maintain this component.
Thank you!

**Comment by tototrinh** [comment]
Thanks @joseabelenda, I sent it here https://github.com/liferay-frontend/liferay-portal/pull/2840. Close this PR.

**Pull request closed without merging**
