### PR TITLE
LPS-160750 Creating PRODUCT PERFORMANCE Product Filter Requests

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Nice job! :white_check_mark:

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:stop

**Comment by JoMaAlves** [comment]
ci:test:stop

**Pull request closed without merging**
