### PR TITLE
LPS-186231 [EVP] Some information in the email sent to employee is incorrect

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-186231](https://issues.liferay.com/browse/LPS-186231)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:forward
ci:forward

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
