### PR TITLE
LPS-192770 [Marketplace] Create Solutions Page for Retail Accelerator

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-192770](https://issues.liferay.com/browse/LPS-192770)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
ci:stop

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
