### PR TITLE
LPS-153397 [Ask] Create the Tags Subscribed section on Subscriptions page

### PR DESCRIPTION
**Pull request by Lucas2691**
### **How it was developed?**
This PR make a section on My Subscriptions page with tags what the user subscribing.
To do this was need make a hook (_useTags_) to organized the logic to tags session can be use to more than one page.
And was created one function to use the date only with Subscribed Tags (tagsItemsSelected()).

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by Lucas2691** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
