### PR TITLE
Pablo-Ci-test

### PR DESCRIPTION
**Pull request by styller1**

### CODE REVIEW

**Comment by styller1** [comment]
ci:test:osb-site-initializer-customer-portal:norebase

**Comment by styller1** [comment]
ci:test:osb-site-initializer-customer-portal:norebase

**Comment by renato-araujo-liferay** [comment]
ci:test:relevant

**Comment by renato-araujo-liferay** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:sf

**Pull request closed without merging**
