### PR TITLE
LPS-166667 [EVP] Blocking guest user access to EVP forms

### PR DESCRIPTION
**Pull request by JoMaAlves**
[LPS-166667](https://issues.liferay.com/browse/LPS-166667)

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Review by Claudionilton — APPROVED** [review]

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Review by juliocezar96 — APPROVED** [review]
Nice job! 🤙

**Pull request closed without merging**
