### PR TITLE
LPS-173192 [Raylife D2C]  Fixing External Reference Code pattern

### PR DESCRIPTION
**Pull request by EugenioAntunes**
[LPS-173192](https://issues.liferay.com/browse/LPS-173192)

### CODE REVIEW

**Review by joanagrego — CHANGES_REQUESTED** [review]
Good job! I added some adjustments, including changing the commit to our LPS pattern.

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Approved! Thank you @EugenioAntunes :white_check_mark:

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
