### PR TITLE
LPS-183153 - [BUG] When delete the project it does not return to the start page

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-183151](https://issues.liferay.com/browse/LPS-183153)

### CODE REVIEW

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
