### PR TITLE
LPS-191803 [Marketplace] Fix Filter Categories in App Dashboard

### PR DESCRIPTION
**Pull request by claricebrasil**

### CODE REVIEW

**Comment by claricebrasil** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
Good job @claricebrasil

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
