### PR TITLE
LPS-165055 [Raylife D2C] Fix the create an account to solve order creation

### PR DESCRIPTION
**Pull request by silasbsi**
Subtask: [LPS-165055](https://issues.liferay.com/browse/LPS-165055)

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @silasbsi

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
