### PR TITLE
LPS-183753 [C.P 2.0]  userInvitedAlreadyExists always null

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-183753](https://issues.liferay.com/browse/LPS-183753)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Comment by eduardo-diniz** [comment]
ci:test:relevant

**Comment by eduardo-diniz** [comment]
ci:forward

**Pull request closed without merging**
