### PR TITLE
LPS-170820 Create comment field in table and show its data

### PR DESCRIPTION
**Pull request by caiosouza15**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by caiosouza15** [comment]
ci:test:sf

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Good job!

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
