### PR TITLE
LPS-179568 [EVP] Resize images to fit the modal width

### PR DESCRIPTION
**Pull request by luisacmn**

### CODE REVIEW

**Comment by juliocezar96** [comment]
Just starting reviewing :)

**Review by juliocezar96 — APPROVED** [review]
Nice job! 🤙

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
LGTM :fire: Thanks @luisacmn

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
