### PR TITLE
LPS-150967 [CP 2.0] Add CP2NewKeyGenerationPortalPart1 tests

### PR DESCRIPTION
**Pull request by MathausC**
https://issues.liferay.com/browse/LPS-150967

### CODE REVIEW

**Comment by MathausC** [comment]
@barrosdennys Needs the aproval of #2348 so I can rebase from master.

**Comment by MathausC** [comment]
@barrosdennys Needs review

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:stable

**Comment by MathausC** [comment]
ci:test:relevant

**Comment by MathausC** [comment]
@barrosdennys needs review

**Comment by barrosdennys** [comment]
ci:forward

**Pull request closed without merging**
