### PR TITLE
LPS-194147 [CP 2.0] Create selected keys export

### PR DESCRIPTION
**Pull request by samuelleolopes**
[LPS-178859](https://liferay.atlassian.net/browse/LPS-178859)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Review by kylembischof — APPROVED** [review]
Looks good!

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Review by EugenioAntunes — APPROVED** [review]
Nice job, @samuelleolopes  ⚡

**Comment by styller1** [comment]
I've seen the relevant faults, everything seems to be fine with me

**Comment by samuelleolopes** [comment]
ci:test:stable

**Pull request closed without merging**
