### PR TITLE
LPS-168254  [Raylife AP]  - Fix the filter on page greater than one.

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-168254](https://issues.liferay.com/browse/LPS-168254)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:relevant

**Review by joanagrego — APPROVED** [review]
Approved! Thank you @eduardo-diniz :white_check_mark:

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
