### PR TITLE
LPS-153626 Allow child pages in site initializer extender

### PR DESCRIPTION
**Pull request by jkappler**
Dear Team, this adds support for child pages in site initializer extender. Please let me know what you think.

Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
@jkappler
That looks good to me.
Thank you so much!

**Pull request closed without merging**
