### PR TITLE
PRM Automated Test - LPS-173731| master

### PR DESCRIPTION
**Pull request by juliosilveira77**
https://issues.liferay.com/browse/LPS-173731

### CODE REVIEW

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by juliosilveira77** [comment]
ci:reopen

**Comment by AfonsoHSantos** [comment]
resent here #3210 3270

**Pull request closed without merging**
