### PR TITLE
LPS-158282 [Raylife AP] correction of capturing the values ​​and actions of select components

### PR DESCRIPTION
**Pull request by eliasantosf**
Sub-task: [LPS-158282](https://issues.liferay.com/browse/LPS-158282)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :fire:

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
