### PR TITLE
LPS-160898 Add Tests for Testray Projects - Administrator

### PR DESCRIPTION
**Pull request by thaiscabrals**

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Review by barrosdennys — COMMENTED** [review]
LGTM

**Comment by barrosdennys** [comment]
ci:forward

**Pull request closed without merging**
