### PR TITLE
LPS-181181 [Raylife Ap] Claims details should only appear on auto policies.

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-181181](https://issues.liferay.com/browse/LPS-181181)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Good job! :white_check_mark:

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
