### PR TITLE
LPS-146113 Add RaylifeLoadingPageMobile macro, paths and tests

### PR DESCRIPTION
**Pull request by thaiscabrals**
- LPS-146174 Add initial Raylife Mobile tests, paths & macros
- LPS-146174 SF
- LPS-146113 Add RaylifeLoadingPageMobile macro, paths and tests
- LPS-146113 SF

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:test:site-initializer-raylife

**Comment by Paulovcaselli** [comment]
ci:test:site-initializer-raylife

**Comment by thaiscabrals** [comment]
ci:forward

**Pull request closed without merging**
