### PR TITLE
LPS-156794 [Raylife] Adapt Raylife Quote with the new data structure changes

### PR DESCRIPTION
**Pull request by silasbsi**
Story: [LPS-156431](https://issues.liferay.com/browse/LPS-156431)

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @silasbsi

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Pull request closed without merging**
