### PR TITLE
LPS-184870 | Adjustments to LXC - SM activation form

### PR DESCRIPTION
**Pull request by gabrielargomes**
[LPS-184814](https://issues.liferay.com/browse/LPS-184814)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Good job @gabrielargomes , can you format source the code? thanks

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by gabrielargomes** [comment]
ci:test:sf

**Comment by gabrielargomes** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
