### PR TITLE
LPS-163132 [EVP] Create EVP Process Section

### PR DESCRIPTION
**Pull request by juliocezarjc**

### CODE REVIEW

**Comment by juliocezarjc** [comment]
ci:test:sf

**Comment by juliocezarjc** [comment]
ci:test:sf

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @juliocezarjc

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
Just starting reviewing :)

**Pull request closed without merging**
