### PR TITLE
LPS-134781 Create unit tests for EnvelopeView

### PR DESCRIPTION
**Pull request by MateusCastro**

### CODE REVIEW

**Comment by MateusCastro** [comment]
ci:test:sf

**Comment by MateusCastro** [comment]
ci:test:relevant

**Comment by MateusCastro** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
Just started reviewing :)

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
c:forward

**Comment by kevenleone** [comment]
ci:forward

**Review by joseabelenda — APPROVED** [review]

**Comment by joseabelenda** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just started reviewing :)

**Comment by kevenleone** [comment]
ci:reevaluate:1257401_2220

**Comment by kevenleone** [comment]
resent: #52

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by MateusCastro** [comment]
ci:test:sf

**Comment by MateusCastro** [comment]
ci:test:relevant

**Comment by MateusCastro** [comment]
ci:test:relevant

**Comment by MateusCastro** [comment]
ci:test:sf

**Comment by MateusCastro** [comment]
ci:test:relevant

**Pull request closed without merging**
