### PR TITLE
LPS-185838 | Automate test for Customer Portal | Provide Guide To All Users

### PR DESCRIPTION
**Pull request by styller1**
Ticket:
[LPS-185838](https://issues.liferay.com/browse/LPS-185838)

### CODE REVIEW

**Comment by styller1** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:sf

**Comment by styller1** [comment]
ci:test:sf

**Review by LuanaKSilva — APPROVED** [review]
Hey @styller1, thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by LuanaKSilva** [comment]
ci:forward

**Pull request closed without merging**
