### PR TITLE
LPS-160051 [ASK] Suspicious Activity 

### PR DESCRIPTION
**Pull request by velosofelipe64**

### CODE REVIEW

**Comment by velosofelipe64** [comment]
ci:test:sf

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Comment by velosofelipe64** [comment]
ci:test:stable

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by velosofelipe64** [comment]
Ci:test:relevant

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Comment by velosofelipe64** [comment]
ci:test:stable

**Comment by joseabelenda** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/121893

**Pull request closed without merging**
