### PR TITLE
LPS-192777 [Marketplace] Solution pages

### PR DESCRIPTION
**Pull request by silasbsi**

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by LuanaKSilva** [comment]
Hey @silasbsi, analyzing the flaws of the relevant... none of them are related to your PR. Feel free to send the code forward.

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by silasbsi** [comment]
ci:forward:force

**Pull request closed without merging**
