### PR TITLE
LPS-173377 [Raylife AP] Refactoring Applications Chart

### PR DESCRIPTION
**Pull request by claricebrasil**

### CODE REVIEW

**Comment by claricebrasil** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Approved! Thank you @claricebrasil :white_check_mark:

**Comment by claricebrasil** [comment]
ci:forward

**Comment by claricebrasil** [comment]
ci:reevaluate:1357401_3394

**Comment by claricebrasil** [comment]
ci:reevaluate:1357401_3394

**Pull request closed without merging**
