### PR TITLE
LPS-182256 Status "NOT_FOUND" when edit subtask with Testray administrator role

### PR DESCRIPTION
**Pull request by rafaelfs98**

### CODE REVIEW

**Review by welitonpe — APPROVED** [review]
Good Job :fire:

**Review by EugenioAntunes — APPROVED** [review]
Nice job, Man

**Review by alvarolealdl — APPROVED** [review]
Great job @rafaelfs98

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Thanks!

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
