### PR TITLE
LPS-150973 Add site-initializer-testray to ci.properties

### PR DESCRIPTION
**Pull request by thaiscabrals**

### CODE REVIEW

**Comment by thaiscabrals** [comment]
ci:test:sf

**Comment by thaiscabrals** [comment]
ci:forward

**Comment by thaiscabrals** [comment]
ci:stop

**Comment by Paulovcaselli** [comment]
ci:relevant

**Comment by Paulovcaselli** [comment]
ci:reevaluate:1257401_2227

**Comment by rodrigocunhaa** [comment]
ci:forward

**Pull request closed without merging**
