### PR TITLE
LPS-168878 [Questions] View count, votes and comments does not reproduce on Activities page

### PR DESCRIPTION
**Pull request by manuelecastro**
[LPS-168878](https://issues.liferay.com/browse/LPS-168878)

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
@manuelecastro thank you sending this PR for us.

Discussing with Guilherme, QA from Solutions we decided to close this bug, because the intended behavior will not exist in the future.

The page will have this look:
image

As you can see, there's no View, Comment and Vote to display

I'll close the PR and Guilherme the Issue, btw your code looks great! thank you anyway 😄

**Comment by manuelecastro** [comment]
@kevenleone alright Keven! Thanks for the feedback on the code! :smile:

**Pull request closed without merging**
