### PR TITLE
LPS-144915 Add CP 2.0 Properties for Poshi Tests

### PR DESCRIPTION
**Pull request by Paulovcaselli**

### CODE REVIEW

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by Paulovcaselli** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by Paulovcaselli** [comment]
ci:test:sf

**Comment by Paulovcaselli** [comment]
ci:forward

**Pull request closed without merging**
