### PR TITLE
LPS-189348 [CP 2.0] Applied Rounding to the Image

### PR DESCRIPTION
**Pull request by samuelleolopes**
[LPS-188690](https://liferay.atlassian.net/browse/LPS-188690)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
