### PR TITLE
LPS-196212, LPS-196343 - [PRM] Fix Deal Registration and Activities required fields

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/4805

**Pull request closed without merging**
