### PR TITLE
LPS-163848 [Raylife AP] Create Policies Table with Data Requests from Raylife Policies

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-163848](https://issues.liferay.com/browse/LPS-163848)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
