### PR TITLE
LPS-156525 [Raylife D2C] Refactor in D2C flow to generate a new policy

### PR DESCRIPTION
**Pull request by joanagrego**
[LPS-156525](https://issues.liferay.com/browse/LPS-156525)
Refactor in D2C flow to generate a new policy

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :fire:

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
