### PR TITLE
LPS-172900 [EVP] Implementation of the Bank Info field

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-172900](https://issues.liferay.com/browse/LPS-172900)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:relevant

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @juliocezar96

**Comment by juliocezar96** [comment]
ci:forward

**Pull request closed without merging**
