### PR TITLE
LPS-186932 [CP 2.0] Not Activated status to include Future durations instead of Deactivated keys

### PR DESCRIPTION
**Pull request by samuelleolopes**
[LPS-186059](https://issues.liferay.com/browse/LPS-186059)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
