### PR TITLE
LPS-188057 [CP 2.0] Fix Can't invite a user that as already an account

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-188057](https://liferay.atlassian.net/browse/LPS-188057)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:stop

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: https://github.com/pt-liferay-solutions/liferay-portal/pull/4365

**Pull request closed without merging**
