### PR TITLE
LPS-191867 [CP 2.0] Add skeleton to display card count

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-191867](https://liferay.atlassian.net/browse/LPS-191867)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just starting reviewing :)

**Pull request closed without merging**
