### PR TITLE
LPS-172108 Links are missing in display pages and page templates

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to task](https://issues.liferay.com/browse/LPS-172108)

In [LPS-143303](https://issues.liferay.com/browse/LPS-143303) we split the way we added layouts through the site initializer. First we create the entry, and then we specify the content. This is done so that we could add links in page templates and display pages.

This was changed in [LPS-168479](https://issues.liferay.com/browse/LPS-168479) by accident, so in this PR que are using the correct order again.

## Change summary:

* Move the method to create the display pages and page templates so it's executed after the layouts are created

## Test Scenario

* Follow the steps in the ticket

extranet

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
Hi @jkappler 
Thank you for your PR.
Unfortunately is failing on relevant test (LocalFile.LiferayOnline#VerifyRemoteAppsInLiferayOnline), but PR https://github.com/brianchandotcom/liferay-portal/pull/128280 fixes this error.
Please, can you send directly to Brian?
Thx

**Comment by jkappler** [comment]
I will do it tomorrow first hour and cc you. Thanks as always @joseabelenda!

**Pull request closed without merging**
