### PR TITLE
LPS-147081 LPS-147082 [CP 2.0] Adding download developer key alert and adjusting license downloaded file name

### PR DESCRIPTION
**Pull request by igordmf**
**How it was developed?**

It was implemented an alert to show download status when user try download an developer key.
If download goes successfully it will show a success alert.
If download fails it will show a danger alert.
The download file name is specific to selected DXP version and project name

**Downloaded file and alert:**

image

**What has been affected by the development ?**
DeveloperKeysInputs has one more state and an rendering verification to show or no an alert.
Nothing was added on data mock up.

### Test Plan
1. Enter in a project with DXP subscription.
2. Click on "Product Activation" on side menu, and click in DXP or DXP Cloud.
3. On Developer Keys session, select a version and click in download button.
4. This should download the file.
5. If download works fine, see if a success alert appears, and license file starts download.
6. If not, see if a fail alert appears.

PS: Make sure that you're authenticated with Okta sign in. (User Garrett)

### CODE REVIEW

**Review by joanagrego — APPROVED** [review]
Nice job!

**Review by claricebrasil — APPROVED** [review]
Great job, Igor! I just miss an example of the error message on your description.

**Review by thaynam — APPROVED** [review]
Good job!

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward

**Review by iagochaves — APPROVED** [review]

**Pull request closed without merging**
