### PR TITLE
LPS-182751 - All buttons disappear when editing a case result without status

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-182751](https://issues.liferay.com/browse/LPS-182751)

### CODE REVIEW

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Review by kevenleone — COMMENTED** [review]
Hi @Artartur , thank you for sending the PR with the fix for us

I was reviewing the task and I couldn't find any relationship between the problem and this code, but I'll recheck with the team the behavior and see If this is the best way to fix the issue

Thank you so much, I'll update you soon

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Thanks @Artartur

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
