### PR TITLE
LPS-175459 [EVP] Shouldn't be possible to submit an invoice to a request with Closed status

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-175459](https://issues.liferay.com/browse/LPS-175459)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @juliocezar96

**Comment by eliasantosf** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
