### PR TITLE
LPS-189222 Add aria-label on ClayTableRow checkboxes

### PR DESCRIPTION
**Pull request by ilzamcmed**
[Jira issue - LPS-189222](https://liferay.atlassian.net/browse/LPS-189222)

### CODE REVIEW

**Comment by ilzamcmed** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-189222 Checkbox in ClayTable has no row title associated with its aria-label</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-189222">Checkbox in ClayTable has no row title associated with its aria-label</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Medium</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Peer Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Ilza Medeiros</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Ilza Medeiros</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

2 files changed, 40 insertions(+)

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
Hey @kevenleone, this PR is related to changes on Clay Tables by adding `aria-label`  on checkboxes.
Could you review it, please? 
Thank you! :smiley:

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Thank you @ilzamcmed

**Pull request closed without merging**
