### PR TITLE
LPS-187831 [EVP] Create Edit Page for Requests

### PR DESCRIPTION
**Pull request by Mylena-Rodrigues**
Ticket: [LPS-187831](https://liferay.atlassian.net/browse/LPS-187831)

### CODE REVIEW

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @Mylena-Rodrigues

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by Mylena-Rodrigues** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:relevant

**Comment by Mylena-Rodrigues** [comment]
ci:test:relevant

**Comment by Mylena-Rodrigues** [comment]
ci:test:relevant

**Comment by Mylena-Rodrigues** [comment]
Link: [brianchandotcom#136990](https://github.com/brianchandotcom/liferay-portal/pull/136990)

**Pull request closed without merging**
