### PR TITLE
LPS-159022 [Raylife AP] Analysis of the data in the commission chart

### PR DESCRIPTION
**Pull request by silasbsi**
Sub-task: [LPS-159022](https://issues.liferay.com/browse/LPS-159022)

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Great job! :up: Thanks @silasbsi

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:stop

**Comment by silasbsi** [comment]
ci:test:stop

**Pull request closed without merging**
