### PR TITLE
LPS-152315 [Questions] Recent activities return results that didn't recently changed

### PR DESCRIPTION
**Pull request by gleicelisbino**

### CODE REVIEW

**Comment by gleicelisbino** [comment]
ci:test:sf

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
@gleicelisbino , please sort lastPostDate on modules/apps/headless/headless-delivery/headless-delivery-test/src/testIntegration/java/com/liferay/headless/delivery/resource/v1_0/test/MessageBoardMessageResourceTest.java ad push change.

**Comment by gleicelisbino** [comment]
@joseabelenda Done :) Thank you and sorry.

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
