### PR TITLE
LPS-141305 Avoid NPE

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:site-initializer-raylife

**Comment by rafaprax** [comment]
ci:test:site-initializer-raylife

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:forward

**Pull request closed without merging**
