### PR TITLE
Raylife AP Automated Test - LPS-161338 | master 

### PR DESCRIPTION
**Pull request by itstali**
https://issues.liferay.com/browse/LPS-161338

### CODE REVIEW

**Comment by styller1** [comment]
ci:test:sf

**Comment by itstali** [comment]
ci:test:sf

**Comment by styller1** [comment]
:fire: LGTM!! :fire:

**Comment by luanakarla** [comment]
LGTM! :fire:

**Comment by luanakarla** [comment]
ci:forward

**Pull request closed without merging**
