### PR TITLE
LPS-177873 [EVP] Creation of Modal and Buttons, with Approve and Reject functionalities

### PR DESCRIPTION
**Pull request by juliocezar96**
[LPS-177873](https://issues.liferay.com/browse/LPS-177873)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by EuniceTravassos** [comment]
Just starting reviewing :)

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]

**Comment by eliasantosf** [comment]
ci:forward
ci:forward

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
