### PR TITLE
ISSITES-6093 update widget/info templates

### PR DESCRIPTION
**Pull request by jotchon**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
LGTM :heavy_check_mark:

**Comment by kevenleone** [comment]
@jotchon can you safe and push it here?

**Comment by jotchon** [comment]
@kevenleone i merged the changes to this commit [2a92332](https://github.com/pt-liferay-solutions/liferay-portal/pull/4329/commits/2a92332e534d19261bd8310db9844ebc76b128a9).  Let me know if you need anything else.

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
Archiving due inactivity

**Pull request closed without merging**
