### PR TITLE
LPS-174994 [PRM] Set activityStatus into MDFRequestForm

### PR DESCRIPTION
**Pull request by Manda-vit**

### CODE REVIEW

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @Manda-vit

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
Just starting reviewing :)

**Review by thaynam — CHANGES_REQUESTED** [review]

**Comment by thaynam** [comment]
resent with additional changes [3323]( https://github.com/pt-liferay-solutions/liferay-portal/pull/3323)

**Pull request closed without merging**
