### PR TITLE
[Site Initializer] User-Organizations

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/1308

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:foward

**Comment by nNilton** [comment]
ci:forward

**Pull request closed without merging**
