### PR TITLE
LPS-170456 [PRM] Replace Web Contents for Enablement course with fragments

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:forward

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
