### PR TITLE
LPS-155898 | master

### PR DESCRIPTION
**Pull request by sontruongces**
Hi team,

This is the fix for the [LPS-155898](https://issues.liferay.com/browse/LPS-155898), the original has passed my review at sontruongces#31. Please help me review and give feedback.

Thanks!
cc: @TaiPhamLR

### CODE REVIEW

**Comment by kevenleone** [comment]
Thank you for submitting this PR; @sontruongces 

@silasbsi can you see the last commit ? It's regarding Raylife

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Review by silasbsi — APPROVED** [review]
LGTM :+1: Thansk @TaiPhamLR

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
LGTM :+1: Thanks @TaiPhamLR

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
