### PR TITLE
LPS-184774 [EVP] Filter creation and csv export

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LPS-184774](https://issues.liferay.com/browse/LPS-184774)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by silasbsi — CHANGES_REQUESTED** [review]
I added some suggestions.

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
ci:forward

**Pull request closed without merging**
