### PR TITLE
LPS-189677 Marketplace Automated Tests LPS-189674 | master

### PR DESCRIPTION
**Pull request by itstali**

### CODE REVIEW

**Comment by itstali** [comment]
ci:test:sf

**Review by LuanaKSilva — APPROVED** [review]
Hey @itstali, thanks for working on it!
The code looks good to me!
I'm forwarding it.

**Comment by LuanaKSilva** [comment]
ci:test:site-initializer-liferay-marketplace

**Comment by LuanaKSilva** [comment]
ci:forward

**Pull request closed without merging**
