### PR TITLE
LPS-185813 [PRM] State Manager dropdown is visible even when there is no options available

### PR DESCRIPTION
**Pull request by DiogoNo**

### CODE REVIEW

**Comment by DiogoNo** [comment]
ci:test:sf

**Comment by DiogoNo** [comment]
ci:test:solutions-acceptance

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
