### PR TITLE
LPS-189673 [CP 2.0] [Task] Fixed Activation key form refresh interactions

### PR DESCRIPTION
**Pull request by samuelleolopes**
[LPS-189673](https://liferay.atlassian.net/browse/LPS-189673)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Pull request closed without merging**
