### PR TITLE
LPS-157711 create form validation fields

### PR DESCRIPTION
**Pull request by silasbsi**
Sub-task: [LPS-157711](https://issues.liferay.com/browse/LPS-157711)

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Great job! :up:

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @silasbsi

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
