### PR TITLE
Raylife AP Automation Test: LPS-160728 | master

### PR DESCRIPTION
**Pull request by luanakarla**
Ticket:
https://issues.liferay.com/browse/LPS-160728

Test:
RaylifeAPContactInfo#IfDatePickerWorks
RaylifeAPContactInfo#NextButtonWorksWhenFieldsAreFilled

### CODE REVIEW

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:site-initializer-raylife-ap:nocompile

**Comment by luanakarla** [comment]
Depends on: [#3658](https://github.com/pt-liferay-solutions/liferay-portal/pull/3658)

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
