### PR TITLE
LPS-183685 The case parameters do not remain selected when editing

### PR DESCRIPTION
**Pull request by rafaelfs98**
[LPS-182988](https://issues.liferay.com/browse/LPS-182988)

### CODE REVIEW

**Comment by rafaelfs98** [comment]
ci:test:sf

**Review by EugenioAntunes — APPROVED** [review]
Nice job, Man 🐐

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
