### PR TITLE
LPS-166789 It was added the Declined status to the picklist

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Link da LPS: https://issues.liferay.com/browse/LPS-166789

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Thanks

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Review by joanagrego — APPROVED** [review]
Approved! Thank you @Valmir-unicap :white_check_mark:

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
