### PR TITLE
LPS-134790 Update build.gradle

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Comment by RodrigoCavalcantii** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by alvaroledli** [comment]
Just starting reviewing :)

**Pull request closed without merging**
