### PR TITLE
LPS-159174 Fix creating more than one virtual instance with remote app

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:stable

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:sf

**Pull request closed without merging**
