### PR TITLE
LPS-196572 [PRM] Move Remote App to Client Extention Workspace

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:stable

**Comment by ling-alan-huang** [comment]
@thaynam 
```
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: Incorrect value 'extra/remote-app/package\.json'. Relative path to file (from location of suppressions file) expected for value of property 'files'. File '/opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/extra/remote-app/package.json' does not exist.: /opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/source-formatter-suppressions.xml 6 (SourceCheck:XMLSuppressionsFileCheck)
```
Can you fix the path in
`modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/source-formatter-suppressions.xml`
because the path in xml is already moved to `feray-partner-custom-element/package.json`


---------

```
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 2: Property value 'commons-collections:commons-collections->modules/apps/portal-template/portal-template-velocity/build.gradle' points to file that does not exist: /opt/dev/projects/github/liferay-portal/modules/source-formatter.properties (SourceCheck:PropertiesSourceFormatterFileCheck)
     [java] 3: Property value 'commons-collections:commons-collections->modules/dxp/apps/saml/saml-opensaml-integration/build.gradle' points to file that does not exist: /opt/dev/projects/github/liferay-portal/modules/source-formatter.properties (SourceCheck:PropertiesSourceFormatterFileCheck)

``` 
The fix is alread in BChan's origin branch, see https://github.com/brianchandotcom/liferay-portal/pull/141006

**Comment by thaynam** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:sf

**Review by jairmedeiros — APPROVED** [review]

**Comment by thaynam** [comment]
[resent](https://github.com/pt-liferay-solutions/liferay-portal/pull/4818)

**Pull request closed without merging**
