### PR TITLE
LPS-191529 - LPS-191526 [PRM] Event Collaterals section doesn't shows added attachments

### PR DESCRIPTION
**Pull request by Manda-vit**

### CODE REVIEW

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @Manda-vit

**Comment by Manda-vit** [comment]
ci:test:stable

**Comment by Manda-vit** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
