### PR TITLE
LPS-158501 [Raylife AP] Add button logic for coverage and review

### PR DESCRIPTION
**Pull request by EugenioAntunes**

### CODE REVIEW

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Nice job! :up:

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @EugenioAntunes

**Review by silasbsi — APPROVED** [review]
LGTM :1st_place_medal: Thanks @EugenioAntunes

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
