### PR TITLE
LPS-184893 Fix empty Notification Template content when syncronizing using a .jar file

### PR DESCRIPTION
**Pull request by joseabelenda**
.

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:reevaluate:1267401_10202

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:stable

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/4459

**Pull request closed without merging**
