### PR TITLE
LPS-161640 [Raylife AP] Correcting Bug at REVIEW QUOTE button

### PR DESCRIPTION
**Pull request by EugenioAntunes**
Task: [LPS-161640](https://issues.liferay.com/browse/LPS-161640)

### CODE REVIEW

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Review by joanagrego — CHANGES_REQUESTED** [review]
Please change the commit name to "LPS-161640 Correcting Bug at Review Quote button".

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Nice job! :white_check_mark:

**Review by silasbsi — APPROVED** [review]
LGTM :martial_arts_uniform:

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
