### PR TITLE
LPS-192776 [Marketplace] Page Crosswired

### PR DESCRIPTION
**Pull request by juliocezar96**
Subtask : [LPS-192776](https://liferay.atlassian.net/browse/LPS-192776)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
