### PR TITLE
LPS-163615 [Raylife D2C] Fix application status in D2C flow

### PR DESCRIPTION
**Pull request by pedroliveirav**
[LPS-163615](https://issues.liferay.com/browse/LPS-163615)

### CODE REVIEW

**Review by joanagrego — APPROVED** [review]
Approved! Thank you @pedroliveirav :white_check_mark:

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @pedroliveirav

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
