### PR TITLE
LPS-160630 [Raylife AP] Table access correction

### PR DESCRIPTION
**Pull request by juliocezarjc**
Impedibug: [LPS-160630](https://issues.liferay.com/browse/LPS-160630)

### CODE REVIEW

**Comment by juliocezarjc** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @juliocezarjc

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
