### PR TITLE
Refactor Click to chat LRQA-82505 | Master

### PR DESCRIPTION
**Pull request by MGabriellaS**
[LRQA-82505](https://liferay.atlassian.net/browse/LRQA-82505)

### CODE REVIEW

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:click-to-chat

**Comment by nikki-pru** [comment]
ci:test:click-to-chat

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
