### PR TITLE
LPS-192008 [PRM] The tactic type fields in the details do not match what was requested in the activity

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:stable

**Comment by thaynam** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
[resent to brian](https://github.com/brianchandotcom/liferay-portal/pull/139170)

**Pull request closed without merging**
