### PR TITLE
EVP Automated Test| master LPS-190019

### PR DESCRIPTION
**Pull request by MGabriellaS**
[LPS-190019](https://liferay.atlassian.net/browse/LPS-190019)

### CODE REVIEW

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by MGabriellaS** [comment]
ci:tes:sf

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by renato-araujo-liferay** [comment]
Look good for me @MGabriellaS . thanks.

**Comment by renato-araujo-liferay** [comment]
ci:forward

**Pull request closed without merging**
