### PR TITLE
LPS-186075 | Freeze header (1st row) of Team Members table

### PR DESCRIPTION
**Pull request by gabrielargomes**

### CODE REVIEW

**Comment by gabrielargomes** [comment]
ci:test:sf

**Comment by gabrielargomes** [comment]
ci:test:sf

**Comment by gabrielargomes** [comment]
ci:test:sf

**Comment by gabrielargomes** [comment]
ci:test:sf

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
