### PR TITLE
LPS-161174 [ASK] add new filters for search thread

### PR DESCRIPTION
**Pull request by velosofelipe64**

### CODE REVIEW

**Comment by velosofelipe64** [comment]
ci:test:sf

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Comment by gleicelisbino** [comment]
ci:test:relevant

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Comment by velosofelipe64** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 


TOPPPPP 🔝

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
