### PR TITLE
LPS-175703 The Status filters not working with In Progress and Test Fix

### PR DESCRIPTION
**Pull request by rafaelfs98**
[LPS-175703](https://issues.liferay.com/browse/LPS-175703)

### CODE REVIEW

**Comment by rafaelfs98** [comment]
ci:test:sf

**Review by welitonpe — APPROVED** [review]
Good job :fire::fire::fire:

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Review by samuelleolopes — APPROVED** [review]

**Review by Elvinho — APPROVED** [review]

**Comment by Elvinho** [comment]
LGTM 👍🏾

**Comment by kevenleone** [comment]
ci:forward

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Pull request closed without merging**
