### PR TITLE
CP2 Fix Tests | LPS-179314 | master

### PR DESCRIPTION
**Pull request by luanakarla**
Ticket:
https://issues.liferay.com/browse/LPS-179314

### CODE REVIEW

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:osb-site-initializer-customer-portal:nocompile

**Comment by nikki-pru** [comment]
Forwarding this since most of the tests addressed in this pull are now passing. These are the remaining failures for the test suite:
[LocalFile.CP2ACFormSent#MessageConfirmingFormHasAlreadyBeenSent](https://testray.liferay.com/home/-/testray/case_results/2243326494?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2243326385%26testrayRunId%3D2243326485%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) - Apart from the failure, this test needs to be renamed to ```CannotSendAPreviouslySubmittedFormToAC```
[LocalFile.CP2DXPCloudFormSent#CanViewAUsefulMessage](https://testray.liferay.com/home/-/testray/case_results/2243326648?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2243326385%26testrayRunId%3D2243326485%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) - Apart from the failure, this test needs to be renamed to ```CannotSendAPreviouslySubmittedFormToDXPCloud```
[LocalFile.CP2SetupAC#CanViewTheSuccessMessage](https://testray.liferay.com/home/-/testray/case_results/2243326599?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2243326385%26testrayRunId%3D2243326485%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) - Apart from the failure, this needs to be renamed to ```CanSubmitRequestForm```

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
