### PR TITLE
LPS-173393

### PR DESCRIPTION
**Pull request by itstali**
https://issues.liferay.com/browse/LPS-173393

### CODE REVIEW

**Comment by itstali** [comment]
ci:test:sf

**Comment by itstali** [comment]
ci:test:site-initializer-raylife-d2c:nocompile

**Comment by nikki-pru** [comment]
Changes looks good! Ready to forward :1st_place_medal:

**Comment by nikki-pru** [comment]
[Test is passing](https://testray.liferay.com/home/-/testray/case_results/2232382033?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2232380813%26testrayRunId%3D2232381442%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)!

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
