### PR TITLE
LPS-158009 [Raylife AP] Fix application products chart

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :fire: Thanks @joanagrego

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Pull request closed without merging**
