### PR TITLE
LPS-176684 TR2 Automated Test - LPS-176684 | master

### PR DESCRIPTION
**Pull request by luanakarla**
Tickets:
https://issues.liferay.com/browse/LPS-174555
https://issues.liferay.com/browse/LPS-176684

### CODE REVIEW

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:site-initializer-testray

**Comment by luanakarla** [comment]
ci:test:site-initializer-testray

**Comment by nikki-pru** [comment]
> ci:test:site-initializer-testray

Thank you

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Comment by luanakarla** [comment]
ci:test:sf

**Comment by luanakarla** [comment]
ci:test:site-initializer-testray

**Comment by luanakarla** [comment]
ci:close

**Pull request closed without merging**
