### PR TITLE
LPS-174056 [Raylife AP] Enable Account Functionality for User Avatar

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-174056](https://issues.liferay.com/browse/LPS-174056)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
Good job :heavy_check_mark:

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
ci:stop

**Comment by silasbsi** [comment]
ci:stop

**Comment by raquelpaiva** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:reevaluate:1397401_3881

**Pull request closed without merging**
