### PR TITLE
LPS-191970 [Marketplace] Fix New User Dashboard hangs on No Apps Screen and Clarity Page Alignments

### PR DESCRIPTION
**Pull request by joanagrego**

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:stop

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:stop

**Pull request closed without merging**
