### PR TITLE
LPS-178107 [CP 2.0] Enable text following user name for Japanese greeting

### PR DESCRIPTION
**Pull request by kiwm**
Related issue: https://issues.liferay.com/browse/LPS-172015

### CODE REVIEW

**Comment by kiwm** [comment]
ci:test:sf

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @kiwm

**Comment by JoMaAlves** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:forward

**Pull request closed without merging**
