### PR TITLE
LPS-192746 [Marketplace] Solutions-Thank-You page

### PR DESCRIPTION
**Pull request by silasbsi**
Subtask: [LPS-192746](https://liferay.atlassian.net/browse/LPS-192746)

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:forward

**Comment by juliocezar96** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
Just starting reviewing :)

**Comment by juliocezar96** [comment]
ci:stop

**Comment by juliocezar96** [comment]
Just starting reviewing :)

**Comment by juliocezar96** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by silasbsi** [comment]
ci:forward:force

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by juliocezar96** [comment]
ci:forward:force

**Pull request closed without merging**
