### PR TITLE
LPS-142812 Update phrase in Quote Comparison Card

### PR DESCRIPTION
**Pull request by kevenleone**
Closed:

https://github.com/brianchandotcom/liferay-portal/pull/111113
https://github.com/brianchandotcom/liferay-portal/pull/111130
https://github.com/brianchandotcom/liferay-portal/pull/111145
https://github.com/brianchandotcom/liferay-portal/pull/111160
https://github.com/brianchandotcom/liferay-portal/pull/111161
https://github.com/brianchandotcom/liferay-portal/pull/111171
https://github.com/brianchandotcom/liferay-portal/pull/111172
https://github.com/brianchandotcom/liferay-portal/pull/111187
https://github.com/pt-liferay-solutions/liferay-portal/pull/546
https://github.com/pt-liferay-solutions/liferay-portal/pull/545
https://github.com/pt-liferay-solutions/liferay-portal/pull/544
https://github.com/pt-liferay-solutions/liferay-portal/pull/541

### CODE REVIEW

**Comment by kevenleone** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-142812 Raylife UI Enhancement</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-142812">Raylife UI Enhancement</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Story</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>0/7 Completed</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Development</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Keven Leone</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Evelyne Duarte</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-143330 [REACT] Update Card component with Dialect theme</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-143330">[REACT] Update Card component with Dialect theme</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Ilza Medeiros</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Silas Silva</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-143909 Update numbers to show 2 decimal digits</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-143909">Update numbers to show 2 decimal digits</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Ilza Medeiros</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Eduardo Gusmão Filho</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-143689 [REACT] Update Payment method component with Dialect theme</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-143689">[REACT] Update Payment method component with Dialect theme</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Wellington Barbosa</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Eduardo Gusmão Filho</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-143685 Update Selected Quote fragment with Dialect</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-143685">Update Selected Quote fragment with Dialect</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Closed</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Eduardo Gusmão Filho</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Eduardo Gusmão Filho</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-143883 Fix redirection of "back to edit" button</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-143883">Fix redirection of "back to edit" button</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Silas Silva</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Silas Silva</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-143327 [REACT] Update Radio group with Dialect theme</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-143327">[REACT] Update Radio group with Dialect theme</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>Closed</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Wellington Barbosa</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Silas Silva</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-143905 Remove auto fill background color from Zip input</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-143905">Remove auto fill background color from Zip input</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Ilza Medeiros</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Eduardo Gusmão Filho</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-143906 Add line through on Our Philosophy phrase</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-143906">Add line through on Our Philosophy phrase</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Ilza Medeiros</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Eduardo Gusmão Filho</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-143687 [REACT] Update Create account component with Dialect theme</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-143687">[REACT] Update Create account component with Dialect theme</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Joao Alves</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Eduardo Gusmão Filho</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-143688 [REACT] Update Upload documents component with Dialect theme</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-143688">[REACT] Update Upload documents component with Dialect theme</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Rosinaldo Guedes</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Eduardo Gusmão Filho</td>
        </tr>
                </table>
          </details><details><summary>More details about: <b>LPS-143981 [REACT] Update modal component with Dialect theme</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-143981">[REACT] Update modal component with Dialect theme</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Technical Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Silas Silva</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Silas Silva</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

60 files changed, 503 insertions(+), 785 deletions(-)

**Comment by kevenleone** [comment]
ci:forward

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
