### PR TITLE
LPS-161842 [Raylife D2C/AP] Create Raylife's Products, Channels, Catalog & Vocabularies New Architecture

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-161842](https://issues.liferay.com/browse/LPS-161842)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @joanagrego

**Review by silasbsi — APPROVED** [review]
LGTM :martial_arts_uniform: Thanks @joanagrego

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
