### PR TITLE
LPS-170635 [TR2] Automation Test | master

### PR DESCRIPTION
**Pull request by joelrocha68**
Tickets:
[LPS-170637](https://issues.liferay.com/browse/LPS-170637)
[LPS-170638](https://issues.liferay.com/browse/LPS-170638)
[LPS-170639](https://issues.liferay.com/browse/LPS-170639)
[LPS-170641](https://issues.liferay.com/browse/LPS-170641)

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray:nocompile

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:test:site-initializer-testray

**Review by luanakarla — APPROVED** [review]
Hey @joelrocha68, thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by joelrocha68** [comment]
ci:forward

**Comment by joelrocha68** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:forward

**Pull request closed without merging**
