### PR TITLE
LPS-184360 [PRM] Missing Partner Info and incorrect Country name on the email body for Deal Reg.

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:stop

**Comment by JoMaAlves** [comment]
Find an error on the code, the site was mocked. Just changed.

**Comment by JoMaAlves** [comment]
ci:forward

**Pull request closed without merging**
