### PR TITLE
LPS-146878 SF

### PR DESCRIPTION
**Pull request by kevenleone**
# How it was developed?
   This PR contains a lot of tasks created by me and @welitonpe to build Testray Interface, we had to build:

- GraphQL Queries
- Page Templates
- Few Components, such as: ProgressBar, Avatar, Charts: PieChart and BarChart

# What has been affected by the development?
   Many pages, such as Overview, Routine, Testflow, Build etc

# Screenshots

image
image
image

For now, using in the most pages with Mock datas

### CODE REVIEW

**Comment by kevenleone** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-146878 Populate Testray pages with Objects</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-146878">Populate Testray pages with Objects</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Progress</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>SE Support</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Keven Leone</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

46 files changed, 2002 insertions(+), 499 deletions(-)

This PR is too huge for one to review :broken_heart: 

Batman

**Comment by welitonpe** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:stop

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
