### PR TITLE
LPS-170932 [PRM] Some erros are being displayed on MDF Detail page edit mode

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
https://issues.liferay.com/browse/LPS-170932

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
