### PR TITLE
LPS-143318 Email adjustments on margins

### PR DESCRIPTION
**Pull request by ilzamcmed**

### CODE REVIEW

**Comment by silasbsi** [comment]
ci-test-sf

**Review by silasbsi — APPROVED** [review]
LGTM :fire:

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
