### PR TITLE
LPS-167795 [CP 2.0] - Allow selected dropdown items to be translated into other languages

### PR DESCRIPTION
**Pull request by luisacmn**

### CODE REVIEW

**Comment by luisacmn** [comment]
ci:test:sf

**Comment by luisacmn** [comment]
ci:test:sf

**Comment by luisacmn** [comment]
ci:test:osb-site-initializer-customer-portal

**Review by claricebrasil — APPROVED** [review]

**Comment by claricebrasil** [comment]
ci:forward

**Comment by claricebrasil** [comment]
ci:forward

**Pull request closed without merging**
