### PR TITLE
LPS-192721 [CP 2.0] Do not display expired subscriptions in generate key order and sort list by available keys

### PR DESCRIPTION
**Pull request by Mylena-Rodrigues**
Ticket: [LPS-192050](https://liferay.atlassian.net/browse/LPS-192050)

### CODE REVIEW

**Comment by Mylena-Rodrigues** [comment]
ci:test:sf

**Comment by Mylena-Rodrigues** [comment]
ci:test:sf

**Review by samuelleolopes — APPROVED** [review]
Good Job! :fire:

**Review by EugenioAntunes — APPROVED** [review]
Nice job, @Mylena-Rodrigues  ⚡

**Review by pedroliveirav — APPROVED** [review]

**Review by Aline160 — APPROVED** [review]

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward:force

**Comment by kevenleone** [comment]
Pull Request forwarded: https://github.com/brianchandotcom/liferay-portal/pull/138960

**Comment by kevenleone** [comment]
ci:stop

**Pull request closed without merging**
