### PR TITLE
LPS-156065 [PRM] MDF Request - Workflow

### PR DESCRIPTION
**Pull request by thaynam**
[LPS-156065](https://issues.liferay.com/browse/LPS-156065)
MDF Request - Workflow

[LPS-156066](https://issues.liferay.com/browse/LPS-156066)
MDF Claim - Workflow

[LPS-171420](https://issues.liferay.com/browse/LPS-171420)
Add Loading in Submit Buttons

[LPS-171418](https://issues.liferay.com/browse/LPS-171418)
Unable to change status of MDF Request

### CODE REVIEW

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @thaynam

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
