### PR TITLE
LPS-162672 [EVP] Adjusting Header Layout

### PR DESCRIPTION
**Pull request by juliocezarjc**
[LPS-162672](https://issues.liferay.com/browse/LPS-162672)

### CODE REVIEW

**Comment by juliocezarjc** [comment]
ci:test:sf

**Comment by juliocezarjc** [comment]
ci:test:relevant

**Comment by juliocezarjc** [comment]
ci:test:sf

**Comment by juliocezarjc** [comment]
ci:test:sf

**Comment by juliocezarjc** [comment]
ci:test:relevant

**Comment by juliocezarjc** [comment]
ci:test:relevant

**Review by silasbsi — APPROVED** [review]
LGTM :martial_arts_uniform:

**Comment by juliocezarjc** [comment]
ci:test:relevant

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @juliocezarjc

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
