### PR TITLE
LPS-188441 [PRM] Add dynamic fields for proof of performance on MDF Claim

### PR DESCRIPTION
**Pull request by jairmedeiros**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:test:relevant

**Comment by thaynam** [comment]
ci:test:relevant

**Comment by jairmedeiros** [comment]
ci:test:osb-site-initializer-partner-portal

**Comment by jairmedeiros** [comment]
resent https://github.com/pt-liferay-solutions/liferay-portal/pull/4497

**Pull request closed without merging**
