### PR TITLE
EVP Automated Test LPS-182727, LPS-166360, LPS-166361, LPS-166359, LPS-184437|master

### PR DESCRIPTION
**Pull request by juliosilveira77**
[LPS-182727](https://liferay.atlassian.net/browse/LPS-182727)
[LPS-184437](https://liferay.atlassian.net/browse/LPS-184437)

These tests are in the commit EVPRequestListing
[LPS-166359](https://liferay.atlassian.net/browse/LPS-166359)
[LPS-166361](https://liferay.atlassian.net/browse/LPS-166361)
[LPS-166360](https://liferay.atlassian.net/browse/LPS-166360)

### CODE REVIEW

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by juliosilveira77** [comment]
ci:test:sf

**Comment by joelrocha68** [comment]
ci:forward

**Pull request closed without merging**
