### PR TITLE
LPS-181734 [Raylife AP/D2C] Fix Raylife's B2C Accounts Log Error

### PR DESCRIPTION
**Pull request by joanagrego**
Related to --> [LPS-181734](https://issues.liferay.com/browse/LPS-181734)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
