### PR TITLE
LPS-180811 [BUG] [PRM] Allow Partner Manager to see Claim List

### PR DESCRIPTION
**Pull request by Manda-vit**

### CODE REVIEW

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:sf

**Comment by Manda-vit** [comment]
ci:test:stable
ci:test:relevant

**Comment by claricebrasil** [comment]
ci:test:stable

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
