### PR TITLE
LPS-192008 The tactic type fields in the details do not match what was requested in the activity

### PR DESCRIPTION
**Pull request by caiosouza15**

### CODE REVIEW

**Comment by caiosouza15** [comment]
ci:test:sf

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by Manda-vit** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
