### PR TITLE
LPS-164327 [EVP] Create MyEVP Table Staff View

### PR DESCRIPTION
**Pull request by juliocezarjc**
[LPS-164327](https://issues.liferay.com/browse/LPS-164327)

### CODE REVIEW

**Comment by juliocezarjc** [comment]
ci:test:sf

**Comment by juliocezarjc** [comment]
ci:test:relevant

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
Just starting reviewing :)

**Pull request closed without merging**
