### PR TITLE
Refactor Click to chat LRQA-82645 | Master 

### PR DESCRIPTION
**Pull request by MGabriellaS**
[LRQA-82645](https://liferay.atlassian.net/browse/LRQA-82645)

### CODE REVIEW

**Comment by MGabriellaS** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:questions

**Comment by nikki-pru** [comment]
ci:test:questions

**Comment by nikki-pru** [comment]
ci:test:click-to-chat

**Comment by nikki-pru** [comment]
Failures are not related.

**Comment by nikki-pru** [comment]
ci:forward

**Comment by MGabriellaS** [comment]
ci:forward

**Pull request closed without merging**
