### PR TITLE
LPS-187997 [Marketplace]  Fix the permissions issues

### PR DESCRIPTION
**Pull request by ytuik**
https://liferay.atlassian.net/browse/LPS-187997

### CODE REVIEW

**Comment by ytuik** [comment]
ci:test:sf

**Comment by ytuik** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]

**Comment by joanagrego** [comment]
ci:test:relevant

**Comment by claricebrasil** [comment]
ci:test:relevant

**Comment by ytuik** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:forward

**Comment by claricebrasil** [comment]
ci:test:stable

**Comment by joanagrego** [comment]
ci:forward

**Comment by claricebrasil** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
ci:stop

**Pull request closed without merging**
