### PR TITLE
LPS-174531 [CP 2.0] Download Portal Key has spaces in the name

### PR DESCRIPTION
**Pull request by kiwm**
Related issue: https://issues.liferay.com/browse/LPS-174531

### CODE REVIEW

**Comment by kiwm** [comment]
ci:test:sf

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:relevant

**Review by jairmedeiros — APPROVED** [review]

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jairmedeiros** [comment]
ci:forward

**Pull request closed without merging**
