### PR TITLE
EVP Automated Test - LPS-184946 | master

### PR DESCRIPTION
**Pull request by alexmds2004**
**Jira** 
EVPOrganization#ManagerCanApproveOrganization
https://issues.liferay.com/browse/LPS-184946

### CODE REVIEW

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
@nikki-pru

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by alexmds2004** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:osb-site-initializer-evp

**Pull request closed without merging**
