### PR TITLE
LPS-181804 [TR2] Automation Test | master

### PR DESCRIPTION
**Pull request by joelrocha68**
Case Result Permissions
Jira ticket: [LPS-181803](https://issues.liferay.com/browse/LPS-181803)

### CODE REVIEW

**Comment by joelrocha68** [comment]
ci:test:sf

**Review by luanakarla — APPROVED** [review]

**Comment by luanakarla** [comment]
Hey @joelrocha68 , thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by joelrocha68** [comment]
ci:forward

**Comment by joelrocha68** [comment]
ci:forward

**Pull request closed without merging**
