### PR TITLE
LPS-159834 [Raylife AP]  Creating PRODUCT PERFORMANCE Period Filters

### PR DESCRIPTION
**Pull request by eduardo-diniz**
[LPS-159835](https://issues.liferay.com/browse/LPS-159835)

### CODE REVIEW

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by EugenioAntunes** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Great job! :white_check_mark:

**Review by silasbsi — APPROVED** [review]
LGTM :+1:

**Comment by silasbsi** [comment]
ci:forward

**Comment by pedroliveirav** [comment]
good job!

**Pull request closed without merging**
