### PR TITLE
LPS-189536 [CP 2.0] [Impedibug] Fixed Key Type and Subscription values are refreshing when select a new version

### PR DESCRIPTION
**Pull request by samuelleolopes**
[LPS-187936](https://liferay.atlassian.net/browse/LPS-187936)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:sf

**Review by Aline160 — APPROVED** [review]

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward:force

**Pull request closed without merging**
