### PR TITLE
[Site Initializer] LPS-159610 Update add Organization

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:reevaluate:1327401_5506

**Comment by nNilton** [comment]
ci:reevaluate:1327401_5506

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/2017

**Pull request closed without merging**
