### PR TITLE
LPS-140153 [CP 2.0]

### PR DESCRIPTION
**Pull request by claricebrasil**

### CODE REVIEW

**Comment by jairmedeiros** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward

**Comment by jpince** [comment]
ci:test:stable - retesting this test suite per CII Team [Slack thread](https://liferay.slack.com/archives/C19PWQ74J/p1659995338721949?thread_ts=1659994925.136369&cid=C19PWQ74J)

**Comment by michaelhashimoto** [comment]
ci:forward

**Pull request closed without merging**
