### PR TITLE
LPS-167868 Create unchecked action for selected subtasks

### PR DESCRIPTION
**Pull request by rafaelfs98**

### CODE REVIEW

**Comment by rafaelfs98** [comment]
ci:test:sf

**Comment by rafaelfs98** [comment]
Just starting reviewing :)

**Review by welitonpe — APPROVED** [review]
LGTM :fire:

**Review by samuelleolopes — APPROVED** [review]

**Comment by rafaelfs98** [comment]
@kevenleone

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

Good job!

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
