### PR TITLE
LPS-159130 [Raylife AP] Exit button set Application Status to Incomplete

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-159130](https://issues.liferay.com/browse/LPS-159130)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :1st_place_medal: Thanks @joanagrego

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
