### PR TITLE
LPS-192764 [Marketplace] Page Open Square IoT

### PR DESCRIPTION
**Pull request by juliocezar96**
Subtask : [LPS-192764](https://liferay.atlassian.net/browse/LPS-192764)

### CODE REVIEW

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
ci:test:sf

**Comment by juliocezar96** [comment]
ci:test:relevant

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
