### PR TITLE
LPS-168193 [Raylife AP] Adjustments on Claim Table code

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-146314](https://issues.liferay.com/browse/LPS-146314)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
