### PR TITLE
LPS-161199 [Raylife AP] Adjustments Policy chart

### PR DESCRIPTION
**Pull request by silasbsi**
Subtask: [LPS-161199](https://issues.liferay.com/browse/LPS-161199)

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Nice job! :white_check_mark:

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​Thanks @silasbsi !

**Comment by silasbsi** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
