### PR TITLE
LPS-143164 Add validations of CA to Retrieve an existing quote

### PR DESCRIPTION
**Pull request by ilzamcmed**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by eduardobbgf** [comment]
Just starting reviewing :)

**Comment by eduardobbgf** [comment]
Just starting reviewing :)

**Comment by kevenleone** [comment]
resent: #414

**Pull request closed without merging**
