### PR TITLE
LPS-150897 [Raylife AP] Adjustments in the titles and buttons of the  layout

### PR DESCRIPTION
**Pull request by silasbsi**

### CODE REVIEW

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
@kevenleone could you make another review?

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Comment by silasbsi** [comment]
ci:test:sf

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
