### PR TITLE
LPS-166822  [Raylife AP] Create Policies Expiring Chart layout

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-146255](https://issues.liferay.com/browse/LPS-146255)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @joanagrego

**Comment by silasbsi** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
