### PR TITLE
LPS-184588 [Marketplace] Add Commerce Order Type through Site Initializer

### PR DESCRIPTION
**Pull request by joseabelenda**
.

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:forward

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:forward

**Comment by joanagrego** [comment]
Just starting reviewing :)

**Comment by joanagrego** [comment]
resent --> [PR](https://github.com/brianchandotcom/liferay-portal/pull/135424)

**Pull request closed without merging**
