### PR TITLE
LPS-169352 [Raylife AP] Set delete disable action to app tables

### PR DESCRIPTION
**Pull request by joanagrego**
Related with --> [LPS-169352](https://issues.liferay.com/browse/LPS-169352)

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Review by eliasantosf — APPROVED** [review]
LGTM :fire: Thanks @pedroliveirav

**Review by kevenleone — APPROVED** [review]
LGTM 🔥 

The code looks beautiful 🗡️

**Comment by kevenleone** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by kevenleone** [comment]
ci:forward

**Comment by joanagrego** [comment]
ci:forward

**Pull request closed without merging**
