### PR TITLE
LPS-190132 Update Request Status When Organization Is Review

### PR DESCRIPTION
**Pull request by Elvinho**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:sf

**Comment by Elvinho** [comment]
ci:test:sf

**Comment by eliasantosf** [comment]
Just starting reviewing :)

**Comment by Elvinho** [comment]
resent [4636](https://github.com/pt-liferay-solutions/liferay-portal/pull/4636)

**Pull request closed without merging**
