### PR TITLE
LPS-167580 [PRM] Add column field for Partner Rep and Liferay Rep in Deal Registration Listing

### PR DESCRIPTION
**Pull request by thaynam**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Review by JoMaAlves — APPROVED** [review]
LGTM ​🦖​🌋​ 
Thank you @thaynam

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:forward

**Comment by thaynam** [comment]
ci:reevaluate:1327401_7230

**Comment by thaynam** [comment]
ci:forward

**Pull request closed without merging**
