### PR TITLE
LPS-166373 [Raylife D2C] The heading is not as expected

### PR DESCRIPTION
**Pull request by eliasantosf**

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by silasbsi — APPROVED** [review]
LGTM :martial_arts_uniform: :heavy_check_mark:

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by joanagrego — APPROVED** [review]
Approved! Thanks @eliasantosf :white_check_mark:

**Comment by silasbsi** [comment]
ci:forward

**Pull request closed without merging**
