### PR TITLE
LPS-166126 Testray TestFlow DispatchTrigger and Testray AutoFill Dispatch Trigger

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by nNilton** [comment]
ci:reevaluate:1297401_5821

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
resent:https://github.com/pt-liferay-solutions/liferay-portal/pull/2971

**Pull request closed without merging**
