### PR TITLE
LPS-131425 Add DIGITAL_SIGNATURE Portlet Name in AddDSEnvelopeMVCResourceCommand

### PR DESCRIPTION
**Pull request by MateusCastro**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:test:sf

**Comment by kevenleone** [comment]
ci:test:relevant

**Review by kevenleone — CHANGES_REQUESTED** [review]
@MateusCastro in general is really good.

Just minor changes to make

**Comment by MateusCastro** [comment]
ci:test:relevant

**Review by kevenleone — APPROVED** [review]
LGTM 🔥

**Comment by kevenleone** [comment]
ci:forward

**Pull request closed without merging**
