### PR TITLE
LPS-168855 [PRM] Fixing MDF Fields can be filled with blank spaces

### PR DESCRIPTION
**Pull request by biellopes00**

### CODE REVIEW

**Comment by thaynam** [comment]
ci:test:sf

**Review by ytuik — COMMENTED** [review]
LGTM!!! :fire:

**Review by thaynam — CHANGES_REQUESTED** [review]
@biellopes00 esta faltando alguns campos com a validacao

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward

**Review by ytuik — COMMENTED** [review]
LGTM

**Pull request closed without merging**
