### PR TITLE
LPS-189545 [BUG] DDM's replacement of the template is not reflected on the display of UI.

### PR DESCRIPTION
**Pull request by joaodamasceno2001**

### CODE REVIEW

**Comment by joaodamasceno2001** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by joanagrego** [comment]
Just starting reviewing :)

**Comment by silasbsi** [comment]
Just starting reviewing :)

**Comment by nNilton** [comment]
Fixed by https://github.com/brianchandotcom/liferay-portal/pull/138704

**Pull request closed without merging**
